/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivityFeed: typeof import('./src/components/Deployments/ActivityFeed.vue')['default']
    Alert: typeof import('./src/components/Modals/Popups/Alert.vue')['default']
    AppButton: typeof import('./src/components/Buttons/AppButton.vue')['default']
    BaseModal: typeof import('./src/components/Modals/BaseModal.vue')['default']
    DeploymentList: typeof import('./src/components/Deployments/DeploymentList.vue')['default']
    MobileSidebar: typeof import('./src/components/MobileSidebar.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsHeader: typeof import('./src/components/SettingsHeader.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    Toast: typeof import('./src/components/Modals/Popups/Toast.vue')['default']
    ToastWrapper: typeof import('./src/components/Modals/ToastWrapper.vue')['default']
  }
}
