import type { GdprErasureAction, GdprLawfulBasis, GdprModelPlan, GdprPlan } from './types'

/**
 * The processing register: a record of what personal data the application
 * holds, whose it is, why, and what happens to it (GDPR Article 30).
 *
 * Generated, never edited. A hand-kept register is accurate on the day it is
 * written and wrong from the first migration after; deriving it from the same
 * declarations the erasure and retention code reads means the document cannot
 * describe behaviour the application does not have. The output is stable - no
 * timestamp, everything sorted - so a committed copy can be checked for drift
 * the way the other generated documents are (`buddy gdpr:register:check`).
 */

export interface GdprRegisterEntry {
  model: string
  table: string
  /** How a row is tied to a data subject, in words. */
  subject: string
  personal: string[]
  /** Personal columns left out of an access export. */
  notExported: string[]
  erasure: GdprErasureAction | null
  retention: string | null
  basis: GdprLawfulBasis | null
  purpose: string | null
}

export interface GdprProcessingRegister {
  entries: GdprRegisterEntry[]
  /** Models that point at the User model and declare nothing about it. */
  unclassified: string[]
}

export type GdprRegisterFormat = 'markdown' | 'json'

function describeSubject(model: GdprModelPlan): string {
  const link = model.subject
  if (!link)
    return 'none (not reachable by access or erasure)'
  if (link.kind === 'via')
    return `via ${link.model} (\`${link.foreignKey}\`)`
  if (link.kind === 'email')
    return `email address in \`${link.column}\``
  const columns = link.columns.map(column => `\`${column}\``).join(' or ')
  const where = Object.entries(link.where).map(([key, value]) => `${key} = ${String(value)}`).join(', ')
  return where ? `${columns} where ${where}` : columns
}

export function buildProcessingRegister(plan: GdprPlan): GdprProcessingRegister {
  const entries = plan.models
    .map((model): GdprRegisterEntry => ({
      model: model.model,
      table: model.table,
      subject: describeSubject(model),
      personal: model.personal.map(field => field.column),
      notExported: model.personal.filter(field => !field.export).map(field => field.column),
      // Erasure cannot reach a model with no subject, so it has no erasure behaviour to state.
      erasure: model.subject ? model.erasure : null,
      retention: model.retention
        ? `${model.retention.action} after ${model.retention.days} days (\`${model.retention.column}\`)`
        : null,
      basis: model.basis,
      purpose: model.purpose,
    }))
    .sort((a, b) => a.model.localeCompare(b.model))

  return { entries, unclassified: [...plan.unclassified].sort() }
}

function cell(value: string | null): string {
  return (value ?? '-').replaceAll('|', '\\|').replaceAll('\n', ' ')
}

export function renderProcessingRegister(register: GdprProcessingRegister, format: GdprRegisterFormat = 'markdown'): string {
  if (format === 'json')
    return `${JSON.stringify(register, null, 2)}\n`

  const lines: string[] = [
    '# Processing register',
    '',
    '<!-- Generated by `buddy gdpr:register` from the model declarations. Do not edit by hand. -->',
    '',
    'Every model that declares personal data or a `gdpr` trait, what erasure does to its rows, and how long they are kept. Change the model, then regenerate this file.',
    '',
    '| Model | Table | Subject | Personal data | Erasure | Retention | Basis | Purpose |',
    '| --- | --- | --- | --- | --- | --- | --- | --- |',
  ]

  for (const entry of register.entries) {
    const personal = entry.personal.length
      ? entry.personal.map(column => entry.notExported.includes(column) ? `\`${column}\` (not exported)` : `\`${column}\``).join(', ')
      : '-'
    lines.push(`| ${[
      entry.model,
      `\`${entry.table}\``,
      cell(entry.subject),
      personal,
      cell(entry.erasure),
      cell(entry.retention),
      cell(entry.basis),
      cell(entry.purpose),
    ].join(' | ')} |`)
  }

  lines.push('')
  lines.push('## Unclassified')
  lines.push('')
  if (register.unclassified.length) {
    lines.push('These models belong to a user but declare neither personal attributes nor a `gdpr` trait, so access and erasure do not reach them. Classify each one, even if only as `erasure: \'keep\'`.')
    lines.push('')
    for (const model of register.unclassified)
      lines.push(`- ${model}`)
  }
  else {
    lines.push('None. Every model that belongs to a user is classified.')
  }
  lines.push('')

  return lines.join('\n')
}
