/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'Carbon:cafe': typeof import('~icons/carbon/cafe')['default']
    'Carbon:logoTwitter': typeof import('~icons/carbon/logo-twitter')['default']
    Expand: typeof import('./src/components/Demo/Expand.vue')['default']
    Footer: typeof import('./src/components/Demo/Footer.vue')['default']
    HeadlessToast: typeof import('./src/components/HeadlessToast.vue')['default']
    HeadlessToastWithProps: typeof import('./src/components/HeadlessToastWithProps.vue')['default']
    Hero: typeof import('./src/components/Demo/Hero.vue')['default']
    Installation: typeof import('./src/components/Demo/Installation.vue')['default']
    Loader: typeof import('./src/components/icons/Loader.vue')['default']
    'Mdi:heart': typeof import('~icons/mdi/heart')['default']
    Others: typeof import('./src/components/Demo/Others.vue')['default']
    Position: typeof import('./src/components/Demo/Position.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    Styling: typeof import('./src/components/Demo/Styling.vue')['default']
    Theming: typeof import('./src/components/Demo/Theming.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    Toaster: typeof import('./src/components/Toaster.vue')['default']
    Types: typeof import('./src/components/Demo/Types.vue')['default']
    Usage: typeof import('./src/components/Demo/Usage.vue')['default']
  }
}
