name: Export Size

on:
  pull_request:
    branches:
      - main

jobs:
  size:
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Pantry
        uses: pantry-pm/pantry/packages/action@485c7b102fe14f8af00b57441a13dc3daa1505e7 # v0.10.39
        with:
          install: 'false'
