#!/bin/sh

# TODO: implement parallelism

# Get the script's directory
script_dir=$(readlink -f $(dirname "$0"))

# Get all directories in the core path & sort them alphabetically
dirs=$(find "$script_dir/../core" -type d -maxdepth 1 | sort)

# Check if no directories found
if [ -z "$dirs" ]; then
  echo "No core packages found"
  exit 1
fi

# Loop through each directory
for dir in $dirs; do
  # Skip the ../core directory because it has no package.json
  if [ "$dir" = "$script_dir/../core" ] || [ "$dir" = "$script_dir/../core/bun-create" ]; then
    continue
  fi

#  echo ""
#  echo "🏗️  Building..."
#  echo "📦 $dir"

  # Change to the directory
  cd $dir

  # Build the package
  bun build.ts

  # Check if the build command was successful
  if [ $? -ne 0 ]; then
    echo "Failed to build $dir"
    exit 1
  fi

#  echo "✅ Build complete"
  echo ""

  # Change back to the original directory
  cd - >/dev/null
done
