#!/bin/sh

# Get the script's directory
script_dir=$(readlink -f $(dirname "$0"))

# Get the number of CPU cores to determine parallelism level
# Adjust this as needed or dynamically determine it
num_cores=$(nproc --all)

# Find all directories in the core path, excluding the ones without package.json
# and pass them to xargs to run builds in parallel
find "$script_dir/../core" -mindepth 1 -maxdepth 1 -type d ! -name 'bun-create' -print0 | xargs -0 -n 1 -P $num_cores sh -c '
dir=$1
echo ""
echo "🏗️  Building..."
echo "📦 $dir"

# Change to the directory
cd $dir

# Build the package
if bun run build; then
  echo "✅ Build complete"
else
  echo "❌ Failed to build $dir"
  exit 1
fi
' sh
