#!/bin/sh

# delete ../../../bun.lock
rm ../../bun.lock

# delete all node_modules and dist folders
bunx --bun rimraf ../../**/dist
bunx --bun rimraf ../../**/node_modules # ensure this runs last or else rimraf will delete itself

# install dependencies via Bun
bun install

# link all core packages
# ./link.sh
