#!/bin/sh

pkgx deintegrate
sudo rm /usr/local/bin/pkgx
rm -rf ~/.pkgx

if [[ "$(uname)" == "Darwin" ]]; then
  # on macOS
  rm -rf "${XDG_CACHE_HOME:-$HOME/Library/Caches}/pkgx"
  rm -rf "${XDG_DATA_HOME:-$HOME/Library/Application Support}/pkgx"
else
  # non macOS
  rm -rf "${XDG_CACHE_HOME:-$HOME/.cache}/pkgx"
  rm -rf "${XDG_DATA_HOME:-$HOME/.local/share}/pkgx"
fi
