# preload these modules before running bun
preload = [ "./storage/framework/defaults/resources/plugins/preloader.ts" ]

[test]
preload = [ "./tests/setup.ts" ]
coverage = false

[run]
# equivalent to `bun --bun` for all `bun run` commands
bun = true

[serve.static]
plugins = [ "bun-plugin-stx" ]

[install]
registry = { url = "https://registry.npmjs.org/", token = "$BUN_AUTH_TOKEN" }
linker = "hoisted"
