# preload these modules before running bun
preload = [ "./storage/framework/defaults/resources/plugins/preloader.ts" ]

[test]
preload = [ "./tests/setup.ts" ]
coverage = true

[run]
# equivalent to `bun --bun` for all `bun run` commands
bun = true

[serve.static]
plugins = [ "bun-plugin-tailwind" ]
