/* eslint-disable */
// AUTO-GENERATED by `buddy generate:db-types --framework` — do not edit.
//
// The shapes of the tables the framework itself ships, so framework code gets
// real rows from `db.selectFrom(...)` without asserting them. An application's
// own tables (and its overrides of these) live in `DatabaseSchema`, which takes
// precedence - see `RowOf` in `./utils`.

export interface FrameworkSchema {
  activities: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    type: string
    description: string
    subject_type: string
    subject_id: number
    causer: string
    properties: string
    ip_address: string
    user_id: number
    createdAt: string
    updatedAt: string | null
    subjectType: string
    subjectId: number
    ipAddress: string
    userId: number
  }
  analytics_events: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    category: string
    path: string
    value: number
    currency: string
    properties: string
    createdAt: string
    updatedAt: string | null
  }
  auction_items: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    lot_number: number
    title: string
    description: string
    image_url: string
    category: string
    donor_name: string
    fair_market_value: number
    starting_bid: number
    min_increment: number
    buy_now_price: number
    reserve_price: number
    status: "open" | "closed" | "sold" | "passed"
    closes_at: string
    extension_count: number
    auction_id: number
    createdAt: string
    updatedAt: string | null
    lotNumber: number
    imageUrl: string
    donorName: string
    fairMarketValue: number
    startingBid: number
    minIncrement: number
    buyNowPrice: number
    reservePrice: number
    closesAt: string
    extensionCount: number
    auctionId: number
  }
  auctions: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    event_id: number
    title: string
    description: string
    status: "draft" | "preview" | "open" | "closed" | "settled"
    currency: string
    goal_amount: number
    opens_at: string
    closes_at: string
    anti_snipe_minutes: number
    extend_on_bid_window_minutes: number
    max_extensions: number
    createdAt: string
    updatedAt: string | null
    eventId: number
    goalAmount: number
    opensAt: string
    closesAt: string
    antiSnipeMinutes: number
    extendOnBidWindowMinutes: number
    maxExtensions: number
  }
  authors: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    email: string
    bio: string
    avatar: string
    user_id: number
    createdAt: string
    updatedAt: string | null
    userId: number
  }
  automation_runs: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    status: "queued" | "running" | "waiting" | "completed" | "failed" | "cancelled"
    current_node_id: string
    version: number
    subject_type: string
    subject_id: string
    context: unknown
    idempotency_key: string
    started_at: string
    finished_at: string
    error: string
    team_id: number
    automation_id: number
    createdAt: string
    updatedAt: string | null
    currentNodeId: string
    subjectType: string
    subjectId: string
    idempotencyKey: string
    startedAt: string
    finishedAt: string
    teamId: number
    automationId: number
  }
  automations: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    status: "draft" | "active" | "paused" | "archived"
    version: number
    trigger: unknown
    graph: unknown
    published_at: string
    team_id: number
    createdAt: string
    updatedAt: string | null
    publishedAt: string
    teamId: number
  }
  bids: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    bidder_name: string
    bidder_email: string
    amount: number
    max_amount: number
    status: "leading" | "outbid" | "won" | "lost" | "invalid"
    placed_at: string
    auction_id: number
    auction_item_id: number
    createdAt: string
    updatedAt: string | null
    bidderName: string
    bidderEmail: string
    maxAmount: number
    placedAt: string
    auctionId: number
    auctionItemId: number
  }
  board_columns: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    board_id: number
    name: string
    position: number
    card_limit: number
    color: string
    createdAt: string
    updatedAt: string | null
    boardId: number
    cardLimit: number
  }
  boards: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    description: string
    icon: string
    color: string
    position: number
    archived: boolean
    createdAt: string
    updatedAt: string | null
  }
  campaign_sends: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    campaign_id: number
    subscriber_id: number
    email_list_id: number
    status: "queued" | "deferred" | "sending" | "sent" | "delivered" | "failed" | "undelivered" | "bounced" | "complained" | "suppressed" | "cancelled"
    channel: "email" | "sms" | "push"
    recipient: string
    idempotency_key: string
    provider_message_id: string
    error: string
    sent_at: string
    opened_at: string
    clicked_at: string
    delivered_at: string
    failed_at: string
    segments: number
    cost: number
    metadata: unknown
    team_id: number
    campaign_variant_id: number
    createdAt: string
    updatedAt: string | null
    campaignId: number
    subscriberId: number
    emailListId: number
    idempotencyKey: string
    providerMessageId: string
    sentAt: string
    openedAt: string
    clickedAt: string
    deliveredAt: string
    failedAt: string
    teamId: number
    campaignVariantId: number
  }
  campaign_variants: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    subject: string
    content: unknown
    allocation: number
    sent_count: number
    open_count: number
    click_count: number
    conversion_count: number
    is_winner: boolean
    team_id: number
    campaign_id: number
    createdAt: string
    updatedAt: string | null
    sentCount: number
    openCount: number
    clickCount: number
    conversionCount: number
    isWinner: boolean
    teamId: number
    campaignId: number
  }
  campaigns: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    description: string
    type: "email" | "sms" | "push" | "social" | "multi-channel"
    status: "draft" | "scheduled" | "sending" | "sent" | "paused" | "cancelled" | "failed" | "active" | "completed" | "archived"
    subject: string
    template: string
    text: string
    content: unknown
    channel_settings: unknown
    segment_definition: unknown
    from_name: string
    from_address: string
    reply_to: string
    timezone: string
    recurrence: string
    experiment_metric: "open_rate" | "click_rate" | "conversion_rate"
    email_list_id: number
    scheduled_at: string
    sent_at: string
    audience_size: number
    sent_count: number
    open_rate: number
    click_rate: number
    conversion_rate: number
    budget: number
    spent: number
    currency: string
    start_date: string
    end_date: string
    team_id: number
    createdAt: string
    updatedAt: string | null
    channelSettings: unknown
    segmentDefinition: unknown
    fromName: string
    fromAddress: string
    replyTo: string
    experimentMetric: "open_rate" | "click_rate" | "conversion_rate"
    emailListId: number
    scheduledAt: string
    sentAt: string
    audienceSize: number
    sentCount: number
    openRate: number
    clickRate: number
    conversionRate: number
    startDate: string
    endDate: string
    teamId: number
  }
  card_comments: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    card_id: number
    user_id: number
    body: string
    createdAt: string
    updatedAt: string | null
    cardId: number
    userId: number
  }
  cards: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    column_id: number
    board_id: number
    title: string
    description: string
    position: number
    created_by_user_id: number
    due_date: string
    archived: boolean
    board_column_id: number
    user_id: number
    createdAt: string
    updatedAt: string | null
    columnId: number
    boardId: number
    createdByUserId: number
    dueDate: string
    boardColumnId: number
    userId: number
  }
  cart_items: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    quantity: number
    unit_price: number
    total_price: number
    tax_rate: number
    tax_amount: number
    discount_percentage: number
    discount_amount: number
    product_name: string
    product_sku: string
    product_image: string
    notes: string
    cart_id: number
    createdAt: string
    updatedAt: string | null
    unitPrice: number
    totalPrice: number
    taxRate: number
    taxAmount: number
    discountPercentage: number
    discountAmount: number
    productName: string
    productSku: string
    productImage: string
    cartId: number
  }
  carts: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    status: "active" | "abandoned" | "converted" | "expired"
    total_items: number
    subtotal: number
    tax_amount: number
    discount_amount: number
    total: number
    expires_at: string
    currency: string
    notes: string
    applied_coupon_id: string
    customer_id: number
    coupon_id: number
    createdAt: string
    updatedAt: string | null
    totalItems: number
    taxAmount: number
    discountAmount: number
    expiresAt: string
    appliedCouponId: string
    customerId: number
    couponId: number
  }
  categories: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    description: string
    slug: string
    image_url: string
    is_active: boolean
    parent_category_id: string
    display_order: number
    createdAt: string
    updatedAt: string | null
    imageUrl: string
    isActive: boolean
    parentCategoryId: string
    displayOrder: number
  }
  categorizable_models: {
    // columns
    id: number
    category_id: number
    categorizable_id: number
    categorizable_type: string
    created_at: string
    updated_at: string | null
  }
  comments: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    author_name: string
    author_email: string
    content: string
    body: string
    post_title: string
    status: "pending" | "approved" | "spam" | "trash"
    ip_address: string
    user_agent: string
    is_approved: number
    post_id: number
    user_id: number
    createdAt: string
    updatedAt: string | null
    authorName: string
    authorEmail: string
    postTitle: string
    ipAddress: string
    userAgent: string
    isApproved: number
    postId: number
    userId: number
  }
  communication_suppressions: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    recipient: string
    channel: "email" | "sms" | "push"
    reason: "unsubscribe" | "bounce" | "complaint" | "carrier" | "manual" | "legal"
    source: string
    suppressed_at: string
    lifted_at: string
    team_id: number
    createdAt: string
    updatedAt: string | null
    suppressedAt: string
    liftedAt: string
    teamId: number
  }
  consent_events: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    recipient: string
    channel: "email" | "sms" | "push"
    action: "requested" | "granted" | "revoked" | "confirmed" | "suppressed"
    purpose: string
    source: string
    jurisdiction: string
    policy_version: string
    idempotency_key: string
    proof: unknown
    ip_address: string
    occurred_at: string
    team_id: number
    createdAt: string
    updatedAt: string | null
    policyVersion: string
    idempotencyKey: string
    ipAddress: string
    occurredAt: string
    teamId: number
  }
  coupons: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    code: string
    description: string
    status: "Active" | "Scheduled" | "Expired"
    is_active: boolean
    discount_type: "fixed_amount" | "percentage"
    discount_value: number
    min_order_amount: number
    max_discount_amount: number
    free_product_id: string
    usage_limit: number
    usage_count: number
    start_date: string
    end_date: string
    product_id: number
    createdAt: string
    updatedAt: string | null
    isActive: boolean
    discountType: "fixed_amount" | "percentage"
    discountValue: number
    minOrderAmount: number
    maxDiscountAmount: number
    freeProductId: string
    usageLimit: number
    usageCount: number
    startDate: string
    endDate: string
    productId: number
  }
  customers: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    email: string
    phone: string
    total_spent: number
    last_order: string
    status: "Active" | "Inactive"
    avatar: string
    user_id: number
    createdAt: string
    updatedAt: string | null
    totalSpent: number
    lastOrder: string
    userId: number
  }
  delivery_routes: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    driver: string
    vehicle: string
    stops: number
    delivery_time: number
    total_distance: number
    last_active: number
    status: "planned" | "active" | "completed" | "cancelled"
    started_at: string
    completed_at: string
    driver_id: number
    createdAt: string
    updatedAt: string | null
    deliveryTime: number
    totalDistance: number
    lastActive: number
    startedAt: string
    completedAt: string
    driverId: number
  }
  delivery_stops: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    sequence: number
    status: "pending" | "en_route" | "arrived" | "completed" | "failed" | "skipped"
    address: string
    latitude: number
    longitude: number
    recipient_name: string
    recipient_phone: string
    eta_at: string
    notified_nearby_at: string
    arrived_at: string
    completed_at: string
    notes: string
    delivery_route_id: number
    order_id: number
    createdAt: string
    updatedAt: string | null
    recipientName: string
    recipientPhone: string
    etaAt: string
    notifiedNearbyAt: string
    arrivedAt: string
    completedAt: string
    deliveryRouteId: number
    orderId: number
  }
  deployments: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    commit_hash: string
    commit_message: string
    branch: string
    status: string
    environment: string
    duration: number
    author: string
    url: string
    error_log: string
    createdAt: string
    updatedAt: string | null
    commitHash: string
    commitMessage: string
    errorLog: string
  }
  digital_deliveries: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    description: string
    download_limit: number
    expiry_days: number
    requires_login: boolean
    automatic_delivery: boolean
    status: "active" | "inactive"
    createdAt: string
    updatedAt: string | null
    downloadLimit: number
    expiryDays: number
    requiresLogin: boolean
    automaticDelivery: boolean
  }
  driver_pings: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    latitude: number
    longitude: number
    heading: number
    speed: number
    accuracy: number
    recorded_at: string
    driver_id: number
    delivery_route_id: number
    createdAt: string
    updatedAt: string | null
    recordedAt: string
    driverId: number
    deliveryRouteId: number
  }
  drivers: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    phone: string
    vehicle_number: string
    license: string
    status: "active" | "on_delivery" | "on_break" | "offline"
    latitude: number
    longitude: number
    heading: number
    speed: number
    last_ping_at: string
    user_id: number
    createdAt: string
    updatedAt: string | null
    vehicleNumber: string
    lastPingAt: string
    userId: number
  }
  email_idempotency: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    idempotency_key: string
    message_id: string
    recipient: string
    subject: string
    provider: string
    success: boolean
    createdAt: string
    updatedAt: string | null
    idempotencyKey: string
    messageId: string
  }
  email_list_subscribers: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    email_list_id: number
    subscriber_id: number
    status: "subscribed" | "unsubscribed" | "pending" | "bounced"
    source: string
    subscribed_at: string
    unsubscribed_at: string
    createdAt: string
    updatedAt: string | null
    emailListId: number
    subscriberId: number
    subscribedAt: string
    unsubscribedAt: string
  }
  email_lists: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    slug: string
    description: string
    subscriber_count: number
    active_count: number
    unsubscribed_count: number
    bounced_count: number
    status: "active" | "inactive" | "archived"
    is_public: number
    double_opt_in: number
    createdAt: string
    updatedAt: string | null
    subscriberCount: number
    activeCount: number
    unsubscribedCount: number
    bouncedCount: number
    isPublic: number
    doubleOptIn: number
  }
  email_suppressions: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    email: string
    type: "bounce" | "complaint" | "unsubscribe" | "manual"
    reason: string
    createdAt: string
    updatedAt: string | null
  }
  email_webhook_events: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    provider: "mailgun" | "postmark" | "ses" | "sendgrid"
    event_id: string
    processed_at: string
    createdAt: string
    updatedAt: string | null
    eventId: string
    processedAt: string
  }
  errors: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    type: string
    message: string
    stack: string
    status: number
    additional_info: string
    createdAt: string
    updatedAt: string | null
    additionalInfo: string
  }
  failed_jobs: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    connection: string
    queue: string
    payload: string
    exception: string
    attempts: number
    max_attempts: number
    duration_ms: number
    failed_at: string
    createdAt: string
    updatedAt: string | null
    maxAttempts: number
    durationMs: number
    failedAt: string
  }
  form_fields: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    name: string
    label: string
    type: "text" | "textarea" | "email" | "phone" | "select" | "checkbox" | "radio" | "date" | "file" | "currency" | "section_break"
    required: boolean
    position: number
    width: "full" | "half"
    options: unknown
    conditions: unknown
    form_id: number
    createdAt: string
    updatedAt: string | null
    formId: number
  }
  form_submissions: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    data: unknown
    email: string
    name: string
    status: "pending_payment" | "complete" | "spam"
    amount_cents: number
    payment_intent_id: string
    ip: string
    submitted_at: string
    form_id: number
    site_id: number
    createdAt: string
    updatedAt: string | null
    amountCents: number
    paymentIntentId: string
    submittedAt: string
    formId: number
    siteId: number
  }
  forms: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    handle: string
    status: "draft" | "active" | "closed"
    settings: unknown
    site_id: number
    createdAt: string
    updatedAt: string | null
    siteId: number
  }
  gift_cards: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    code: string
    initial_balance: number
    current_balance: number
    currency: string
    status: "ACTIVE" | "USED" | "EXPIRED" | "DEACTIVATED"
    purchaser_id: string
    recipient_email: string
    recipient_name: string
    personal_message: string
    is_digital: boolean
    is_reloadable: boolean
    is_active: boolean
    expiry_date: string
    last_used_date: string
    template_id: string
    customer_id: number
    createdAt: string
    updatedAt: string | null
    initialBalance: number
    currentBalance: number
    purchaserId: string
    recipientEmail: string
    recipientName: string
    personalMessage: string
    isDigital: boolean
    isReloadable: boolean
    isActive: boolean
    expiryDate: string
    lastUsedDate: string
    templateId: string
    customerId: number
  }
  jobs: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    queue: string
    payload: string
    attempts: number
    available_at: number
    reserved_at: number
    createdAt: string
    updatedAt: string | null
    availableAt: number
    reservedAt: number
  }
  labels: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    board_id: number
    name: string
    color: string
    createdAt: string
    updatedAt: string | null
    boardId: number
  }
  license_keys: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    key: string
    template: "Standard License" | "Premium License" | "Enterprise License"
    expiry_date: string
    status: "active" | "inactive" | "unassigned"
    customer_id: number
    product_id: number
    order_id: number
    createdAt: string
    updatedAt: string | null
    expiryDate: string
    customerId: number
    productId: number
    orderId: number
  }
  logs: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    timestamp: number
    type: "warning" | "error" | "info" | "success"
    source: "file" | "cli" | "system"
    message: string
    project: string
    stacktrace: string
    file: string
    createdAt: string
    updatedAt: string | null
  }
  loyalty_points: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    wallet_id: string
    points: number
    source: string
    source_reference_id: string
    description: string
    expiry_date: string
    is_used: boolean
    createdAt: string
    updatedAt: string | null
    walletId: string
    sourceReferenceId: string
    expiryDate: string
    isUsed: boolean
  }
  loyalty_rewards: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    description: string
    points_required: number
    reward_type: string
    discount_percentage: number
    free_product_id: string
    is_active: boolean
    expiry_days: number
    image_url: string
    product_id: number
    createdAt: string
    updatedAt: string | null
    pointsRequired: number
    rewardType: string
    discountPercentage: number
    freeProductId: string
    isActive: boolean
    expiryDays: number
    imageUrl: string
    productId: number
  }
  magic_link_tokens: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    email: string
    token: string
    expires_at: string
    consumed_at: string
    redirect_to: string
    site_id: number
    user_id: number
    createdAt: string
    updatedAt: string | null
    expiresAt: string
    consumedAt: string
    redirectTo: string
    siteId: number
    userId: number
  }
  mail_preferences: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    mailbox: string
    account_name: string
    signature: string
    display_density: "comfortable" | "default" | "compact"
    theme: "light" | "dark" | "system"
    language: "en" | "fr" | "de" | "es" | "ja"
    default_reply_behavior: "reply" | "replyAll"
    send_and_archive: boolean
    auto_advance: "newer" | "older" | "back"
    desktop_notifications: boolean
    notification_sound: "default" | "subtle" | "none"
    notification_preview: boolean
    filters: string
    blocked_senders: string
    labels: string
    load_remote_images: boolean
    show_external_content: boolean
    vacation_enabled: boolean
    vacation_start_date: string
    vacation_end_date: string
    vacation_subject: string
    vacation_message: string
    createdAt: string
    updatedAt: string | null
    accountName: string
    displayDensity: "comfortable" | "default" | "compact"
    defaultReplyBehavior: "reply" | "replyAll"
    sendAndArchive: boolean
    autoAdvance: "newer" | "older" | "back"
    desktopNotifications: boolean
    notificationSound: "default" | "subtle" | "none"
    notificationPreview: boolean
    blockedSenders: string
    loadRemoteImages: boolean
    showExternalContent: boolean
    vacationEnabled: boolean
    vacationStartDate: string
    vacationEndDate: string
    vacationSubject: string
    vacationMessage: string
  }
  manufacturers: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    manufacturer: string
    description: string
    country: string
    featured: boolean
    createdAt: string
    updatedAt: string | null
  }
  menu_items: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    label: string
    url: string
    target: "_self" | "_blank"
    parent_id: number
    position: number
    visibility: "public" | "auth"
    menu_id: number
    page_id: number
    createdAt: string
    updatedAt: string | null
    parentId: number
    menuId: number
    pageId: number
  }
  menus: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    handle: string
    name: string
    site_id: number
    createdAt: string
    updatedAt: string | null
    siteId: number
  }
  notification_deliveries: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    user_id: number
    channel: "email" | "sms" | "chat" | "database" | "push" | "broadcast"
    recipient: string
    subject: string
    body: string
    status: "pending" | "sent" | "delivered" | "failed"
    error: string
    metadata: string
    sent_at: string
    createdAt: string
    updatedAt: string | null
    userId: number
    sentAt: string
  }
  notifications: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    type: string
    data: string
    read_at: string
    user_id: number
    createdAt: string
    updatedAt: string | null
    readAt: string
    userId: number
  }
  order_idempotency: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    idempotency_key: string
    order_id: number
    createdAt: string
    updatedAt: string | null
    idempotencyKey: string
    orderId: number
  }
  order_items: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    quantity: number
    price: number
    special_instructions: string
    order_id: number
    product_id: number
    createdAt: string
    updatedAt: string | null
    specialInstructions: string
    orderId: number
    productId: number
  }
  orders: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    status: string
    total_amount: number
    currency: string
    tax_amount: number
    discount_amount: number
    delivery_fee: number
    tip_amount: number
    order_type: string
    delivery_address: string
    special_instructions: string
    estimated_delivery_time: string
    tracking_token: string
    delivery_latitude: number
    delivery_longitude: number
    applied_coupon_id: string
    customer_id: number
    coupon_id: number
    createdAt: string
    updatedAt: string | null
    totalAmount: number
    taxAmount: number
    discountAmount: number
    deliveryFee: number
    tipAmount: number
    orderType: string
    deliveryAddress: string
    specialInstructions: string
    estimatedDeliveryTime: string
    trackingToken: string
    deliveryLatitude: number
    deliveryLongitude: number
    appliedCouponId: string
    customerId: number
    couponId: number
  }
  page_revisions: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    revision: number
    title: string
    blocks: unknown
    meta_description: string
    note: string
    page_id: number
    author_id: number
    createdAt: string
    updatedAt: string | null
    metaDescription: string
    pageId: number
    authorId: number
  }
  pages: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    title: string
    slug: string
    path: string
    parent_id: number
    template: string
    blocks: unknown
    meta_description: string
    status: "draft" | "published" | "scheduled" | "archived"
    scheduled_at: string
    views: number
    published_at: string
    conversions: number
    author_id: number
    site_id: number
    createdAt: string
    updatedAt: string | null
    parentId: number
    metaDescription: string
    scheduledAt: string
    publishedAt: string
    authorId: number
    siteId: number
  }
  payment_methods: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    type: string
    last_four: number
    brand: string
    exp_month: number
    exp_year: number
    is_default: boolean
    provider_id: string
    user_id: number
    createdAt: string
    updatedAt: string | null
    lastFour: number
    expMonth: number
    expYear: number
    isDefault: boolean
    providerId: string
    userId: number
  }
  payment_products: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    description: string
    key: string
    unit_price: number
    status: string
    image: string
    provider_id: string
    createdAt: string
    updatedAt: string | null
    unitPrice: number
    providerId: string
  }
  payment_transactions: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    description: string
    amount: number
    type: string
    provider_id: string
    user_id: number
    payment_method_id: number
    createdAt: string
    updatedAt: string | null
    providerId: string
    userId: number
    paymentMethodId: number
  }
  payments: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    amount: number
    method: "cash" | "creditCard" | "debitCard" | "paypal" | "applePay" | "googlePay" | "bankTransfer" | "giftCard"
    status: "pending" | "processing" | "completed" | "failed" | "refunded" | "partiallyRefunded" | "succeeded"
    currency: string
    reference_number: string
    card_last_four: string
    card_brand: string
    billing_email: string
    transaction_id: string
    payment_provider: string
    refund_amount: number
    notes: string
    order_id: number
    customer_id: number
    createdAt: string
    updatedAt: string | null
    referenceNumber: string
    cardLastFour: string
    cardBrand: string
    billingEmail: string
    transactionId: string
    paymentProvider: string
    refundAmount: number
    orderId: number
    customerId: number
  }
  pledges: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    donor_name: string
    donor_email: string
    amount: number
    level: string
    status: "pending" | "confirmed" | "cancelled"
    auction_id: number
    createdAt: string
    updatedAt: string | null
    donorName: string
    donorEmail: string
    auctionId: number
  }
  posts: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    title: string
    slug: string
    poster: string
    content: string
    excerpt: string
    focus_keyword: string
    meta_description: string
    canonical_url: string
    views: number
    published_at: string
    status: "published" | "draft" | "archived"
    is_featured: number
    author_id: number
    site_id: number
    createdAt: string
    updatedAt: string | null
    focusKeyword: string
    metaDescription: string
    canonicalUrl: string
    publishedAt: string
    isFeatured: number
    authorId: number
    siteId: number
  }
  print_devices: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    mac_address: string
    location: string
    terminal: string
    status: "online" | "offline" | "warning"
    last_ping: number
    print_count: number
    createdAt: string
    updatedAt: string | null
    macAddress: string
    lastPing: number
    printCount: number
  }
  product_units: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    abbreviation: string
    type: string
    description: string
    is_default: boolean
    product_id: number
    createdAt: string
    updatedAt: string | null
    isDefault: boolean
    productId: number
  }
  product_variants: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    variant: string
    type: string
    description: string
    options: string
    status: "active" | "inactive" | "draft"
    product_id: number
    createdAt: string
    updatedAt: string | null
    productId: number
  }
  products: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    description: string
    price: number
    image_url: string
    is_available: boolean
    inventory_count: number
    preparation_time: number
    allergens: string
    nutritional_info: string
    category_id: number
    manufacturer_id: number
    createdAt: string
    updatedAt: string | null
    imageUrl: string
    isAvailable: boolean
    inventoryCount: number
    preparationTime: number
    nutritionalInfo: string
    categoryId: number
    manufacturerId: number
  }
  query_logs: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    query: string
    normalized_query: string
    duration: number
    connection: string
    status: "completed" | "failed" | "slow"
    error: string
    executed_at: string
    bindings: string
    trace: string
    model: string
    method: string
    file: string
    line: number
    memory_usage: number
    rows_affected: number
    transaction_id: string
    tags: string
    affected_tables: string
    indexes_used: string
    missing_indexes: string
    explain_plan: string
    optimization_suggestions: string
    createdAt: string
    updatedAt: string | null
    normalizedQuery: string
    executedAt: string
    memoryUsage: number
    rowsAffected: number
    transactionId: string
    affectedTables: string
    indexesUsed: string
    missingIndexes: string
    explainPlan: string
    optimizationSuggestions: string
  }
  receipts: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    printer: string
    document: string
    timestamp: string
    status: "success" | "failed" | "warning"
    size: number
    pages: number
    duration: number
    metadata: string
    print_device_id: number
    createdAt: string
    updatedAt: string | null
    printDeviceId: number
  }
  redirects: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    from_path: string
    to_path: string
    status_code: number
    source: "slug-change" | "manual"
    site_id: number
    createdAt: string
    updatedAt: string | null
    fromPath: string
    toPath: string
    statusCode: number
    siteId: number
  }
  releases: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    version: string
    type: string
    status: string
    notes: string
    downloads: number
    author: string
    createdAt: string
    updatedAt: string | null
  }
  requests: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    deleted_at: string | null
    method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS" | "HEAD"
    path: string
    status_code: number
    duration_ms: number
    ip_address: string
    memory_usage: number
    user_agent: string
    error_message: string
    createdAt: string
    updatedAt: string | null
    deletedAt: string | null
    statusCode: number
    durationMs: number
    ipAddress: string
    memoryUsage: number
    userAgent: string
    errorMessage: string
  }
  reviews: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    rating: number
    title: string
    content: string
    is_verified_purchase: boolean
    is_approved: boolean
    is_featured: boolean
    helpful_votes: number
    unhelpful_votes: number
    purchase_date: string
    images: string
    product_id: number
    customer_id: number
    createdAt: string
    updatedAt: string | null
    isVerifiedPurchase: boolean
    isApproved: boolean
    isFeatured: boolean
    helpfulVotes: number
    unhelpfulVotes: number
    purchaseDate: string
    productId: number
    customerId: number
  }
  sender_domains: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    domain: string
    status: "pending" | "verified" | "failed" | "disabled"
    selector: string
    dns_records: unknown
    verified_at: string
    last_checked_at: string
    team_id: number
    createdAt: string
    updatedAt: string | null
    dnsRecords: unknown
    verifiedAt: string
    lastCheckedAt: string
    teamId: number
  }
  shipping_methods: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    description: string
    base_rate: number
    free_shipping: number
    status: "active" | "inactive" | "draft"
    createdAt: string
    updatedAt: string | null
    baseRate: number
    freeShipping: number
  }
  shipping_rates: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    weight_from: number
    weight_to: number
    rate: number
    shipping_method_id: number
    shipping_zone_id: number
    createdAt: string
    updatedAt: string | null
    weightFrom: number
    weightTo: number
    shippingMethodId: number
    shippingZoneId: number
  }
  shipping_zones: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    countries: string
    regions: string
    postal_codes: string
    status: "active" | "inactive" | "draft"
    shipping_method_id: number
    createdAt: string
    updatedAt: string | null
    postalCodes: string
    shippingMethodId: number
  }
  site_domains: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    domain: string
    is_primary: boolean
    verified_at: string
    ssl_status: "pending" | "issued" | "failed"
    site_id: number
    createdAt: string
    updatedAt: string | null
    isPrimary: boolean
    verifiedAt: string
    sslStatus: "pending" | "issued" | "failed"
    siteId: number
  }
  sites: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    subdomain: string
    status: "active" | "suspended" | "archived"
    settings: unknown
    timezone: string
    team_id: number
    createdAt: string
    updatedAt: string | null
    teamId: number
  }
  sms_opt_outs: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    phone: string
    reason: string
    opted_out_at: string
    createdAt: string
    updatedAt: string | null
    optedOutAt: string
  }
  social_accounts: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    provider: string
    provider_user_id: string
    provider_email: string
    user_id: number
    createdAt: string
    updatedAt: string | null
    providerUserId: string
    providerEmail: string
    userId: number
  }
  social_posts: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    content: string
    platform: "twitter" | "facebook" | "instagram" | "linkedin" | "tiktok" | "youtube"
    status: "draft" | "scheduled" | "published" | "failed"
    scheduled_at: string
    published_at: string
    likes: number
    shares: number
    comments: number
    reach: number
    image_url: string
    external_id: string
    user_id: number
    createdAt: string
    updatedAt: string | null
    scheduledAt: string
    publishedAt: string
    imageUrl: string
    externalId: string
    userId: number
  }
  subscriber_emails: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    email: string
    source: string
    subscriber_id: number
    createdAt: string
    updatedAt: string | null
    subscriberId: number
  }
  subscribers: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    email: string
    status: "subscribed" | "unsubscribed" | "pending" | "bounced"
    source: string
    unsubscribed_at: string
    user_id: number
    createdAt: string
    updatedAt: string | null
    unsubscribedAt: string
    userId: number
  }
  subscriptions: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    type: string
    plan: string
    provider_id: string
    provider_status: string
    unit_price: number
    provider_type: string
    provider_price_id: string
    quantity: number
    trial_ends_at: string
    ends_at: string
    last_used_at: string
    user_id: number
    createdAt: string
    updatedAt: string | null
    providerId: string
    providerStatus: string
    unitPrice: number
    providerType: string
    providerPriceId: string
    trialEndsAt: string
    endsAt: string
    lastUsedAt: string
    userId: number
  }
  taggable_models: {
    // columns
    id: number
    tag_id: number
    taggable_id: number
    taggable_type: string
    created_at: string
    updated_at: string | null
  }
  tags: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    slug: string
    description: string
    color: string
    createdAt: string
    updatedAt: string | null
  }
  tax_rates: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    rate: number
    type: string
    country: string
    region: "North America" | "South America" | "Europe" | "Asia" | "Africa" | "Oceania" | "Antarctica"
    status: "active" | "inactive"
    is_default: boolean
    code: string
    exemptible: boolean
    createdAt: string
    updatedAt: string | null
    isDefault: boolean
  }
  team_invitations: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    team_id: number
    email: string
    role: "admin" | "member" | "viewer"
    token_hash: string
    pending_key: string
    invited_by_user_id: number
    accepted_by_user_id: number
    status: "pending" | "accepted" | "revoked" | "expired"
    delivery_status: "pending" | "sent" | "failed"
    delivery_error: string
    expires_at: string
    delivered_at: string
    accepted_at: string
    createdAt: string
    updatedAt: string | null
    teamId: number
    tokenHash: string
    pendingKey: string
    invitedByUserId: number
    acceptedByUserId: number
    deliveryStatus: "pending" | "sent" | "failed"
    deliveryError: string
    expiresAt: string
    deliveredAt: string
    acceptedAt: string
  }
  team_members: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    team_id: number
    user_id: number
    role: "owner" | "admin" | "member" | "viewer"
    status: "active" | "suspended"
    createdAt: string
    updatedAt: string | null
    teamId: number
    userId: number
  }
  teams: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    description: string
    member_count: number
    status: string
    createdAt: string
    updatedAt: string | null
    memberCount: number
  }
  transactions: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    amount: number
    status: string
    payment_method: string
    payment_details: string
    transaction_reference: string
    loyalty_points_earned: number
    loyalty_points_redeemed: number
    order_id: number
    createdAt: string
    updatedAt: string | null
    paymentMethod: string
    paymentDetails: string
    transactionReference: string
    loyaltyPointsEarned: number
    loyaltyPointsRedeemed: number
    orderId: number
  }
  usage_events: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    meter: "contacts" | "email_sends" | "sms_segments" | "ai_generations" | "storage_bytes"
    quantity: number
    idempotency_key: string
    metadata: unknown
    occurred_at: string
    team_id: number
    createdAt: string
    updatedAt: string | null
    idempotencyKey: string
    occurredAt: string
    teamId: number
  }
  users: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    email: string
    password: string
    avatar: string
    createdAt: string
    updatedAt: string | null
  }
  waitlist_products: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    email: string
    phone: string
    quantity: number
    notification_preference: "sms" | "email" | "both"
    source: string
    notes: string
    status: "waiting" | "purchased" | "notified" | "cancelled"
    notified_at: string
    purchased_at: string
    cancelled_at: string
    product_id: number
    customer_id: number
    createdAt: string
    updatedAt: string | null
    notificationPreference: "sms" | "email" | "both"
    notifiedAt: string
    purchasedAt: string
    cancelledAt: string
    productId: number
    customerId: number
  }
  waitlist_restaurants: {
    // columns
    id: number
    uuid: string
    created_at: string
    updated_at: string | null
    name: string
    email: string
    phone: string
    party_size: number
    check_in_time: string
    table_preference: "indoor" | "bar" | "booth" | "no_preference"
    status: "waiting" | "seated" | "cancelled" | "no_show"
    quoted_wait_time: number
    actual_wait_time: number
    queue_position: number
    seated_at: string
    no_show_at: string
    cancelled_at: string
    customer_id: number
    createdAt: string
    updatedAt: string | null
    partySize: number
    checkInTime: string
    tablePreference: "indoor" | "bar" | "booth" | "no_preference"
    quotedWaitTime: number
    actualWaitTime: number
    queuePosition: number
    seatedAt: string
    noShowAt: string
    cancelledAt: string
    customerId: number
  }
  websockets: {
    // columns
    id: number
    created_at: string
    updated_at: string | null
    type: "disconnection" | "error" | "success"
    socket: string
    details: string
    time: number
    createdAt: string
    updatedAt: string | null
  }
}
