import { readFileSync } from 'node:fs'
import { join } from 'node:path'

export const GENERATED_MIGRATION_MARKER = [
  // The runner's own marker, first because it is only recognized at the very
  // start of the file.
  //
  // These files are executed by `bun-query-builder`, which keeps its own idea
  // of which migrations it generated: a generated file whose change is already
  // in place is recorded and skipped, and an authored one fails loudly. Two
  // markers for one corpus meant every file this generator wrote read as
  // hand-authored to the tool running it, so MySQL - which has no
  // `ADD CONSTRAINT IF NOT EXISTS` - stopped the whole corpus on a foreign key
  // that was already there.
  'qb:generated',
  '@generated by `buddy migrate:regenerate` - edits will be overwritten',
].map(line => `-- ${line}`).join('\n')

/** Whether a migration file was emitted by the corpus generator. */
export function isGeneratedMigration(dir: string, file: string): boolean {
  try {
    // The marker sits at the head of the file - `qb:generated` first, this note
    // on the line under it - so only the head needs reading.
    return readFileSync(join(dir, file), 'utf8').slice(0, 200).includes('@generated by `buddy migrate:regenerate`')
  }
  catch {
    // Unreadable means "cannot prove it is ours", which must mean "keep it".
    return false
  }
}

