/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('../../components/Docs/Home.vue')['default']
    HomeContributors: typeof import('../../components/Docs/HomeContributors.vue')['default']
    HomeSponsors: typeof import('../../components/Docs/HomeSponsors.vue')['default']
    HomeTeam: typeof import('../../components/Docs/HomeTeam.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    TeamMember: typeof import('../../components/Docs/TeamMember.vue')['default']
  }
}
