// Generated by bun-plugin-auto-imports
// This file provides global type declarations for auto-imported functions and models

import type * as AutoImports from './index'

declare global {
  // Re-export all types from auto-imports as globals
  export import haversineDistance = AutoImports.haversineDistance
  export import calculatePolygonArea = AutoImports.calculatePolygonArea
  export import pointInPolygon = AutoImports.pointInPolygon
  export import isClosedLoop = AutoImports.isClosedLoop
  export import simplifyTrack = AutoImports.simplifyTrack
  export import getBoundingBox = AutoImports.getBoundingBox
  export import getCentroid = AutoImports.getCentroid
  export import calculatePerimeter = AutoImports.calculatePerimeter
  export import coordinatesToGeoJson = AutoImports.coordinatesToGeoJson
  export import geoJsonToCoordinates = AutoImports.geoJsonToCoordinates
  export import boundingBoxesOverlap = AutoImports.boundingBoxesOverlap
  export import routeIntersectsPolygon = AutoImports.routeIntersectsPolygon
  export import splitPolygonByRoute = AutoImports.splitPolygonByRoute
  export import parseGpx = AutoImports.parseGpx
  export import parseGpsData = AutoImports.parseGpsData
  export import validateGpsDataForClaim = AutoImports.validateGpsDataForClaim
}

export {}
