// Generated by bun-plugin-auto-imports
//
// Name to file, relative to this file. The resolvers read it, and the name
// types are `keyof` over it - so a name that type-checks is a name that
// resolves. Values are paths rather than import thunks on purpose: thunks
// would make every compilation that touches a name resolve every module.
export const policies = {
  'PostPolicy': '../defaults/app/Policies/PostPolicy.ts',
} as const
