/**
 * The interactive-content section of the capability matrix (stacksjs/stacks#877).
 *
 * Generated from the probe records, the same way `docs:capabilities` generates
 * the driver matrix from `capabilityRegistry`: `buddy docs:capabilities` writes
 * it and `docs:capabilities:check` fails CI when the page and the records
 * disagree. What it cannot do is re-measure - a record is one run on one
 * machine - so every column carries its date, host version, OS and machine,
 * which is what makes a stale measurement visible rather than silently trusted.
 */

import type { InteractiveProbeRecord, ProbeName, ProbeResult } from './schema'
import { PROBE_NAMES } from './schema'

export const INTERACTIVE_BEGIN = '<!-- interactive-capability:begin -->'
export const INTERACTIVE_END = '<!-- interactive-capability:end -->'

/** The command that produces a record, named once so the page and the CLI agree. */
export const PROBE_COMMAND = 'buddy desktop:probe'

const OS_NAMES: Record<string, string> = { darwin: 'macOS', linux: 'Linux', win32: 'Windows' }

/** The column heading for one record: the host and its version. */
export function recordLabel(record: InteractiveProbeRecord): string {
  return record.host.kind === 'craft' ? `Craft ${record.host.version}` : `${record.host.name} ${record.host.version}`
}

function environment(record: InteractiveProbeRecord): string {
  const os = OS_NAMES[record.os.platform] ?? record.os.name
  return `${os} ${record.os.version} ${record.os.arch}, ${record.machine.cpu} (${record.machine.model})`
}

/** Records in the order the page shows them: Craft first, then browsers, each by name. */
export function orderRecords(records: readonly InteractiveProbeRecord[]): InteractiveProbeRecord[] {
  return [...records].sort((a, b) => {
    if (a.host.kind !== b.host.kind)
      return a.host.kind === 'craft' ? -1 : 1
    return `${a.host.name} ${a.os.platform} ${a.os.arch}`.localeCompare(`${b.host.name} ${b.os.platform} ${b.os.arch}`)
  })
}

function number(value: unknown): number | null {
  return typeof value === 'number' && Number.isFinite(value) ? value : null
}

function nested(data: Record<string, unknown> | undefined, ...path: string[]): unknown {
  let current: unknown = data
  for (const key of path) {
    if (typeof current !== 'object' || current === null)
      return undefined
    current = (current as Record<string, unknown>)[key]
  }
  return current
}

/** The one figure worth putting in a table cell, when the probe has one. */
export function headline(name: ProbeName, probe: ProbeResult): string | null {
  const data = probe.data
  if (probe.status !== 'measured' || !data)
    return null

  switch (name) {
    case 'framePacing': {
      const raf = number(data.rafHz)
      const display = number(data.displayHz)
      const p99 = number(nested(data, 'load', 'p99Ms'))
      if (raf === null || display === null || p99 === null)
        return null
      return `${raf} Hz rAF on a ${display} Hz display, p99 ${p99} ms under load`
    }
    case 'inputLatency': {
      for (const kind of ['pointerdown', 'keydown', 'pointermove']) {
        const p50 = number(nested(data, kind, 'toFrame', 'p50Ms'))
        if (p50 !== null)
          return `${kind} p50 ${p50} ms to next frame`
      }
      return null
    }
    case 'audioLatency': {
      const snapshot = (data.afterGesturedResume ?? data.afterUngesturedResume) as Record<string, unknown> | null | undefined
      const base = number(snapshot?.baseLatency)
      const output = number(snapshot?.outputLatency)
      const format = (seconds: number | null) => seconds === null ? 'n/a' : `${Math.round(seconds * 10_000) / 10} ms`
      return `base ${format(base)}, output ${format(output)}`
    }
    default:
      return null
  }
}

function cell(name: ProbeName, probe: ProbeResult | undefined): string {
  if (!probe)
    return 'not probed'
  const figure = headline(name, probe)
  return figure ? `**${probe.status}** - ${figure}` : `**${probe.status}**`
}

function escapeCell(text: string): string {
  return text.replaceAll('|', '\\|').replaceAll('\n', ' ')
}

/** The generated block, markers included. */
export function renderInteractiveCapabilities(records: readonly InteractiveProbeRecord[]): string {
  const ordered = orderRecords(records)
  const lines: string[] = [
    INTERACTIVE_BEGIN,
    '',
    '<!-- Generated by `buddy docs:capabilities` from the records in',
    '     storage/framework/core/desktop/src/probe/results/. Re-measure with',
    `     \`${PROBE_COMMAND} --record\`; do not edit this by hand. -->`,
    '',
    'Whether a Craft window can host a game or other frame-driven content that somebody else',
    'builds, measured by the probe harness in `@stacksjs/desktop-build`',
    '([stacksjs/stacks#877](https://github.com/stacksjs/stacks/issues/877)). Ordinary browsers',
    'on the same machine are measured alongside it for comparison.',
    '',
    '> **How current is this?** Unlike the driver tables above, these are measurements, not',
    '> claims CI can re-check. Each column is one run on one machine, and says when, against',
    '> which host version, on which OS and hardware. If your Craft is newer than the column,',
    `> the numbers describe something you are not running: re-measure with \`${PROBE_COMMAND} --record\`.`,
    '',
  ]

  if (ordered.length === 0) {
    lines.push(`No measurement has been recorded yet. Run \`${PROBE_COMMAND} --record\`.`, '', INTERACTIVE_END)
    return lines.join('\n')
  }

  lines.push(
    `| Probe | ${ordered.map(record => escapeCell(recordLabel(record))).join(' | ')} |`,
    `|---|${ordered.map(() => '---').join('|')}|`,
  )
  for (const [name, label] of PROBE_NAMES)
    lines.push(`| ${label} | ${ordered.map(record => escapeCell(cell(name, record.probes[name]))).join(' | ')} |`)
  lines.push(
    `| Measured on | ${ordered.map(record => escapeCell(environment(record))).join(' | ')} |`,
    `| Measured at | ${ordered.map(record => record.measuredAt.slice(0, 10)).join(' | ')} |`,
    '',
    '- **available** / **measured** - the API exists and the probe exercised it.',
    '- **unavailable** - the API is missing, or creating it failed.',
    '- **requires-interaction** - needs a real click, key press or controller that the run did not have. What was still observable is in the notes; no number is invented.',
    '- **denied** - requested from a real click and refused.',
    '',
  )

  for (const record of ordered) {
    const refresh = record.machine.display.refreshHz === null ? 'unknown refresh rate' : `${record.machine.display.refreshHz} Hz display`
    lines.push(`**${recordLabel(record)}** - ${environment(record)}, ${refresh}`, '')
    for (const [name, label] of PROBE_NAMES) {
      const probe = record.probes[name]
      if (probe)
        lines.push(`- **${label}** - ${probe.note}`)
    }
    lines.push('')
  }

  lines.push(
    '**Out of scope.** Stacks is not shipping a game engine, a physics engine, an audio mixer or',
    'an asset pipeline. This section establishes what a Craft window gives an engine somebody',
    'else wrote; it is not a plan to write one.',
    '',
    INTERACTIVE_END,
  )
  return lines.join('\n')
}
