import type { BuddyCommandInventoryEntry, BuddyCommandInventoryOption } from '../../storage/framework/core/buddy/src/commands/list'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

interface BuddyInventory {
  commands: BuddyCommandInventoryEntry[]
  total: number
}

const root = resolve(import.meta.dir, '../..')
const outputPath = resolve(root, 'docs/guide/buddy/commands.md')
const cliPath = resolve(root, 'storage/framework/core/buddy/src/cli.ts')

function markdown(value: unknown): string {
  return String(value).replaceAll('\\', '\\\\').replaceAll('|', '\\|').replaceAll('\n', '<br>')
}

function code(value: unknown): string {
  return `\`${String(value).replaceAll('`', '\\`')}\``
}

function optionFlags(option: BuddyCommandInventoryOption): string {
  return option.flags.map(flag => code(`${flag.length === 1 ? '-' : '--'}${flag}`)).join(', ')
}

function optionKind(option: BuddyCommandInventoryOption): string {
  const traits = [
    option.boolean ? 'boolean' : 'value',
    option.required ? 'required' : 'optional',
    ...(option.negated ? ['negated'] : []),
  ]
  return traits.join(', ')
}

function argumentSyntax(argument: BuddyCommandInventoryEntry['arguments'][number]): string {
  const value = `${argument.name}${argument.variadic ? '...' : ''}`
  return code(argument.required ? `<${value}>` : `[${value}]`)
}

function commandSection(command: BuddyCommandInventoryEntry): string {
  const lines = [
    `### ${code(command.name)}`,
    '',
    command.description || 'No description provided.',
    '',
    `- Usage: ${code(command.usage)}`,
    `- Namespace: ${command.namespace ? code(command.namespace) : 'none'}`,
    `- Aliases: ${command.aliases.length ? command.aliases.map(code).join(', ') : 'none'}`,
    `- Arguments: ${command.arguments.length ? command.arguments.map(argumentSyntax).join(', ') : 'none'}`,
  ]

  if (command.options.length) {
    lines.push(
      '',
      '| Option | Description | Contract | Default |',
      '| --- | --- | --- | --- |',
      ...command.options.map(option => `| ${optionFlags(option)} | ${markdown(option.description || '—')} | ${optionKind(option)} | ${option.default === undefined ? '—' : code(JSON.stringify(option.default))} |`),
    )
  }

  if (command.examples.length) {
    lines.push('', 'Examples:', '', '```bash', ...command.examples, '```')
  }

  return lines.join('\n')
}

export function renderBuddyCommandReference(inventory: BuddyInventory): string {
  const commands = [...inventory.commands].sort((a, b) => a.name.localeCompare(b.name))
  if (inventory.total !== commands.length)
    throw new Error(`Buddy inventory total ${inventory.total} does not match ${commands.length} commands`)
  if (new Set(commands.map(command => command.name)).size !== commands.length)
    throw new Error('Buddy inventory contains duplicate canonical command names')

  const groups = new Map<string, BuddyCommandInventoryEntry[]>()
  for (const command of commands) {
    const group = command.namespace || (command.name.includes(':') ? command.name.split(':')[0]! : 'general')
    const entries = groups.get(group) || []
    entries.push(command)
    groups.set(group, entries)
  }

  const groupSummary = [...groups.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([group, entries]) => `| ${code(group)} | ${entries.length} |`)

  const document = [
    '---',
    'title: Buddy Command Reference',
    'description: Generated reference for every Buddy command, argument, option, alias, default, and example.',
    '---',
    '<!-- Generated by scripts/docs/buddy-commands.ts. Do not edit by hand. -->',
    '',
    '# Buddy Command Reference',
    '',
    `This reference is generated from Buddy's runtime command registry and currently contains **${commands.length} commands**. Run \`bun run docs:buddy\` after changing the registry; CI rejects stale output.`,
    '',
    '## Command groups',
    '',
    '| Group | Commands |',
    '| --- | ---: |',
    ...groupSummary,
    '',
    '## Commands',
    '',
    ...commands.flatMap(command => [commandSection(command), '']),
  ].join('\n')

  return `${document.split('\n').map(line => line.trimEnd()).join('\n').trimEnd()}\n`
}

export function loadBuddyInventory(): BuddyInventory {
  const result = Bun.spawnSync([process.execPath, cliPath, 'list', '--json'], {
    cwd: root,
    env: { ...process.env, NO_COLOR: '1' },
    stdout: 'pipe',
    stderr: 'pipe',
  })
  if (result.exitCode !== 0)
    throw new Error(`Buddy command inventory failed (${result.exitCode}): ${result.stderr.toString().trim()}`)

  const inventory = JSON.parse(result.stdout.toString()) as BuddyInventory
  if (!Array.isArray(inventory.commands) || !Number.isInteger(inventory.total))
    throw new Error('Buddy command inventory returned an invalid payload')
  return inventory
}

if (import.meta.main) {
  const mode = process.argv.includes('--write') ? 'write' : process.argv.includes('--check') ? 'check' : null
  if (!mode) {
    console.error('usage: bun scripts/docs/buddy-commands.ts --write | --check')
    process.exit(2)
  }

  const expected = renderBuddyCommandReference(loadBuddyInventory())
  if (mode === 'write') {
    mkdirSync(dirname(outputPath), { recursive: true })
    writeFileSync(outputPath, expected)
    console.log(`Wrote ${outputPath}`)
  }
  else {
    if (!existsSync(outputPath)) throw new Error('Buddy command reference is missing; run bun run docs:buddy')
    if (readFileSync(outputPath, 'utf8') !== expected)
      throw new Error('Buddy command reference is stale; run bun run docs:buddy')
    console.log('Buddy command reference matches the runtime registry')
  }
}
