/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'Carbon:cafe': typeof import('~icons/carbon/cafe')['default']
    'Carbon:logoTwitter': typeof import('~icons/carbon/logo-twitter')['default']
    Example: typeof import('./src/components/Example.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Installation: typeof import('./src/components/Installation.vue')['default']
    'Mdi:heart': typeof import('~icons/mdi/heart')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    Step: typeof import('./src/components/Step.vue')['default']
    Stepper: typeof import('./src/components/Stepper.vue')['default']
    Usage: typeof import('./src/components/Usage.vue')['default']
  }
}
