/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export type {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Hero: typeof import('./src/components/Hero.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    Step: typeof import('./src/components/Step.vue')['default']
    Stepper: typeof import('./src/components/Stepper.vue')['default']
  }
}
