export const pages = [
  {
    page: '/',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/contact',
    title: 'CareFree — Contact Us',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/about',
    title: 'CareFree — About CareFree',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/events',
    title: 'CareFree — Upcoming Events',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/carecompare',
    title: 'CareFree — CareCompare',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/carrier',
    title: 'CareFree — Carriers',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/compliance',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/continuingeducation',
    title: 'CareFree — Continuing Education',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/reportscenter',
    title: 'CareFree — Reports Center',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/agentonboarding',
    title: 'CareFree — New Agent Onboarding',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/quotes',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/site-builder',
    title: 'CareFree — Site Builder',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/brokersales',
    title: 'CareFree — Broker Sales Management',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/services',
    title: 'CareFree — CareFree Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/team',
    title: 'CareFree — Team Members',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/testimonials',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/whycarefree',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/trainingevents',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/virtualmeetandgreet',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/winners-circle-2023',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/product',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/terms',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/faq',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/get-contracted',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/reportscenter\/login',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/login',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/aetna',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/alignment',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/afsc',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/amfirst',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/Anthem',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/bcbs',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/brighthealthplan',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/Cigna',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/clear-spring',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/delta',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/devoted',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/Empire',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/FreedomHealth',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/HealthSun',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/humana',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/hap',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/imperial_insurance',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/Medica',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/mhh',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/Molina',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/mutual',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/FreedomOptimum',
    title: 'CareFree Insurance Services',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/oscar',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/PCP',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/renaissance',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/Molina',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/scan',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/SimplyHealthcare',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/solis',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/UHC',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/vsp',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/WellCare',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MTS_Telesales',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MTS_Onboarding',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MTS_Medicare',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MTS_Sales_Process',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MTS_Industry',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MTS_Compliance',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MTS_Technology',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MTS_CSRs',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MTS_Onboarding_Csr',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MTS_Medicare_Csr',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MTS_Sales_Process_Csr',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MTS_Compliance_Csr',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MTS_Technology_Csr',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MTS_Captive_Agents',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MSC_Telesales',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MSC_Onboarding',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MSC_Medicare',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MSC_Sales_Process',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MSC_Industry',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MSC_Compliance',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MSC_Technology',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MSC_CSRs',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MSC_Onboarding_Csr',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MSC_Medicare_Csr',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MSC_Sales_Process_Csr',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MSC_Compliance_Csr',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/MSC_Technology_Csr',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/Vendor_Telesales',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/Vendor_Medicare',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/Vendor_Sales_Process',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/Vendor_Industry',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/Vendor_Compliance',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: 'Vendor_Onboarding',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Captive',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Onboarding',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Medicare',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Industry',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Technology',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Sales_Process',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Compliance',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Relationship',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_SP',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Onboarding_SP',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Medicare_SP',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Industry_SP',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Technology_SP',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Sales_Process_SP',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Compliance_SP',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Relationship_SP',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Ind',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Ind_Onboarding',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Ind_Medicare',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Ind_Industry',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Ind_Technology',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Ind_Sales_Process',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Ind_Compliance',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
  {
    page: '/CF_Ind_Relationship',
    title: 'CareFree — Testimonials',
    description: 'CareFree Insurance Services is your best choice to get the products, innovation and support you need to dominate the Senior Health Market.',
    keywords: 'CareFree, Insurance, Services, Free, E&O, AHIP, Training',
  },
]
