import { Action } from '@stacksjs/actions'

export default new Action({
  name: 'Buddy Command Info',
  description: 'This command displays the available buddy command information.',

  handle() {
    return {
      commands: [
        {
          signature: 'buddy --version',
          description: 'Get the Stacks version',
          notes: null,
          synopsis: 'buddy --version',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy --help',
          description: 'View help menu',
          notes: 'Please note: you may suffix any command with the e.g `command --help` flag to review the help menu',
          synopsis: 'buddy --help',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy install',
          description: 'Installs dependencies',
          notes: '',
          synopsis: 'buddy install',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy add',
          description: 'Adds a stack or dependency',
          notes: '',
          synopsis: 'buddy add',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy fresh',
          description: 'Fresh reinstall of all dependencies',
          notes: '',
          synopsis: 'buddy fresh',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy clean',
          description: 'Removes all dependencies',
          notes: '',
          synopsis: 'buddy clean',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy upgrade',
          description: 'Upgrades all dependencies',
          notes: '',
          synopsis: 'buddy upgrade',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy upgrade -i',
          description: 'Prompts you to select which updates to apply (wip)',
          notes: '',
          synopsis: 'buddy upgrade -i',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy upgrade:dependencies',
          description: 'Auto-upgrades dependencies & the Stacks framework',
          notes: '',
          synopsis: 'buddy upgrade:dependencies',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy upgrade:framework',
          description: 'Auto-upgrades dependencies & the Stacks framework',
          notes: '',
          synopsis: 'buddy upgrade:framework',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy upgrade:search-engine',
          description: 'Auto-upgrades configured search engine',
          notes: '',
          synopsis: 'buddy upgrade:search-engine',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy upgrade:bun',
          description: 'Upgrades to latest project-defined Bun version',
          notes: '',
          synopsis: 'buddy upgrade:bun',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy upgrade:all',
          description: 'Auto-upgrades all of the above',
          notes: '',
          synopsis: 'buddy upgrade:all',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy dev',
          description: 'Starts the frontend dev server',
          notes: '',
          synopsis: 'buddy dev',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy dev -i',
          description: 'Prompts any of the dev servers (components, functions, views, or docs)',
          notes: '',
          synopsis: 'buddy dev -i',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy dev:api',
          description: 'Starts the API dev server',
          notes: '',
          synopsis: 'buddy dev:api',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy dev:dashboard',
          description: 'Starts the Admin/Dashboard dev server',
          notes: '',
          synopsis: 'buddy dev:dashboard',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy dev:desktop',
          description: 'Starts the Desktop dev server',
          notes: '',
          synopsis: 'buddy dev:desktop',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy dev:views',
          description: 'Starts frontend dev server',
          notes: '',
          synopsis: 'buddy dev:views',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy dev:components',
          description: 'Starts component dev server',
          notes: '',
          synopsis: 'buddy dev:components',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy dev:functions',
          description: 'Stubs functions',
          notes: '',
          synopsis: 'buddy dev:functions',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy dev:docs',
          description: 'Starts local docs dev server',
          notes: '',
          synopsis: 'buddy dev:docs',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy dev docs',
          description: 'Also starts the local docs dev server (colon is optional)',
          notes: '',
          synopsis: 'buddy dev docs',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy development',
          description: '`buddy dev` alias',
          notes: '',
          synopsis: 'buddy development',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy build',
          description: 'Select a specific build (follow CLI prompts)',
          notes: '',
          synopsis: 'buddy build',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy build:views',
          description: 'Builds SSG views',
          notes: '',
          synopsis: 'buddy build:views',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy build:desktop',
          description: 'Builds the Desktop application',
          notes: '',
          synopsis: 'buddy build:desktop',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy build:library',
          description: 'Builds any or all libraries',
          notes: '',
          synopsis: 'buddy build:library',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy build:functions',
          description: 'Builds the function library',
          notes: '',
          synopsis: 'buddy build:functions',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy build:components',
          description: 'Builds Vue component library & Web Component library',
          notes: '',
          synopsis: 'buddy build:components',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy build:web-components',
          description: 'Builds framework-agnostic Web Component library (i.e. Custom Elements)',
          notes: '',
          synopsis: 'buddy build:web-components',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy build:vue-components',
          description: 'Builds Vue 2 & 3-ready Component library',
          notes: '',
          synopsis: 'buddy build:vue-components',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy build:all',
          description: 'Builds all your code',
          notes: '',
          synopsis: 'buddy build:all',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy key:generate',
          description: 'Generates your application key',
          notes: '',
          synopsis: 'buddy key:generate',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy make:component',
          description: 'Bootstraps a <name> component',
          notes: '',
          synopsis: 'buddy make:component <name>',
          aliases: [],
          arguments: [
            {
              name: 'name',
              description: 'The component to be created',
              value_required: true,
            },
          ],
          options: [],
        },
        {
          signature: 'buddy make:function',
          description: 'Bootstraps a <name> function',
          notes: '',
          synopsis: 'buddy make:function <name>',
          aliases: [],
          arguments: [
            {
              name: 'name',
              description: 'The function name to be created. Must be in <snake-case>',
              value_required: true,
            },
          ],
          options: [],
        },
        {
          signature: 'buddy make:view',
          description: 'Bootstraps a <name> page',
          notes: '',
          synopsis: 'buddy make:view <name>',
          aliases: [],
          arguments: [
            {
              name: 'name',
              description: 'The component to be created. Must be in <snake-case>',
              value_required: true,
            },
          ],
          options: [],
        },
        {
          signature: 'buddy make:model',
          description: 'Bootstraps a <name> model',
          notes: '',
          synopsis: 'buddy make:model <name>',
          aliases: [],
          arguments: [
            {
              name: 'name',
              description: 'The model to be created.',
              value_required: true,
            },
          ],
          options: [],
        },
        {
          signature: 'buddy make:database',
          description: 'Creates a new database.',
          notes: '',
          synopsis: 'buddy make:database <name>',
          aliases: [],
          arguments: [
            {
              name: 'name',
              description: 'The database to be created',
              value_required: true,
            },
          ],
          options: [],
        },
        {
          signature: 'buddy make:migration',
          description: 'Creates a new migration file.',
          notes: '',
          synopsis: 'buddy make:migration <name>',
          aliases: [],
          arguments: [
            {
              name: 'name',
              description: 'The migration to be created.',
              value_required: true,
            },
          ],
          options: [],
        },
        {
          signature: 'buddy make:factory',
          description: 'Creates a new factory file',
          notes: '',
          synopsis: 'buddy make:factory <name>',
          aliases: [],
          arguments: [
            {
              name: 'name',
              description: 'The factory to be created.',
              value_required: true,
            },
          ],
          options: [],
        },
        {
          signature: 'buddy make:table',
          description: 'Bootstraps a new data table',
          notes: '',
          synopsis: 'buddy make:table <name>',
          aliases: [],
          arguments: [
            {
              name: 'name',
              description: 'The table to be created.',
              value_required: true,
            },
          ],
          options: [],
        },
        {
          signature: 'buddy make:notification',
          description: 'Bootstraps a new notification email',
          notes: '',
          synopsis: 'buddy make:notification <name>',
          aliases: [],
          arguments: [
            {
              name: 'name',
              description: 'The notification email to be created.',
              value_required: true,
            },
          ],
          options: [],
        },
        {
          signature: 'buddy make:lang',
          description: 'Bootstraps a new yml language file under `lang/<name>.yml`',
          notes: '',
          synopsis: 'buddy make:lang <name>',
          aliases: [],
          arguments: [
            {
              name: 'name',
              description: 'The yml language file to be created.',
              value_required: true,
            },
          ],
          options: [],
        },
        {
          signature: 'buddy make:stack',
          description: 'Shares logic with `bunx stacks new <project-name>`',
          notes: '',
          synopsis: 'buddy make:stack <project-name>',
          aliases: [],
          arguments: [
            {
              name: 'project-name',
              description: 'The name of the project to be created.',
              value_required: true,
            },
          ],
          options: [],
        },
        {
          signature: 'buddy migrate',
          description: 'Runs database migrations',
          notes: '',
          synopsis: 'buddy migrate',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy migrate:dns',
          description: 'Sets the ./config/dns.ts file',
          notes: '',
          synopsis: 'buddy migrate:dns',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy dns',
          description: 'List all DNS records for <example.com>',
          notes: '',
          synopsis: 'buddy dns <site> [--type <type>]',
          aliases: [],
          arguments: [
            {
              name: 'site',
              description: 'The name of the site to list all of its DNS records',
              value_required: true,
            },
          ],
          options: [
            {
              name: 'type',
              description: 'Proxies dog',
              value_required: false,
            },
          ],
        },
        {
          signature: 'buddy lint',
          description: 'Runs linter',
          notes: '',
          synopsis: 'buddy lint',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy lint:fix',
          description: 'Runs linter and fixes issues',
          notes: '',
          synopsis: 'buddy lint:fix',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy commit',
          description: 'Follow CLI prompts for committing staged changes',
          notes: '',
          synopsis: 'buddy commit',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy release',
          description: 'Creates the releases for the stack & triggers the Release Action (workflow)',
          notes: '',
          synopsis: 'buddy release',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy changelog',
          description: 'Generates CHANGELOG.md',
          notes: '',
          synopsis: 'buddy changelog',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy deploy',
          description: 'Select a specific deployment (follow CLI prompts)',
          notes: '',
          synopsis: 'buddy deploy',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy undeploy',
          description: 'Be careful: "undeploys" removes/deletes your deployed resources',
          notes: '',
          synopsis: 'buddy undeploy',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy cloud:remove',
          description: 'Removes cloud setup',
          notes: '',
          synopsis: 'buddy cloud:remove',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy cloud:cleanup',
          description: 'Removes cloud setup & cleans up all potentially leftover resources',
          notes: '',
          synopsis: 'buddy cloud:cleanup',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy cloud:add --jump-box',
          description: 'Adds a jump box to your cloud setup',
          notes: '',
          synopsis: 'buddy cloud:add --jump-box',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy example',
          description: 'Prompts you to select which example to run',
          notes: '',
          synopsis: 'buddy example',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy example:vue',
          description: 'Runs the Vue example',
          notes: '',
          synopsis: 'buddy example:vue',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy example:web-components',
          description: 'Runs the Web Component example',
          notes: '',
          synopsis: 'buddy example:web-components',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy generate',
          description: 'Prompts you to select which generator to run',
          notes: '',
          synopsis: 'buddy generate',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy generate:types',
          description: 'Generates types for your components, functions, & views',
          notes: '',
          synopsis: 'buddy generate:types',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy generate:entries',
          description: 'Generates entry files for components, functions, & views',
          notes: '',
          synopsis: 'buddy generate:entries',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy generate:web-types',
          description: 'Generates Web Component types',
          notes: '',
          synopsis: 'buddy generate:web-types',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy generate:vscode-custom-data',
          description: 'Generates VSCode custom data',
          notes: '',
          synopsis: 'buddy generate:vscode-custom-data',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy generate:ide-helpers',
          description: 'Generates IDE helpers',
          notes: '',
          synopsis: 'buddy generate:ide-helpers',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy generate:component-meta',
          description: 'Generates component meta',
          notes: '',
          synopsis: 'buddy generate:component-meta',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy generate:all',
          description: 'Runs all generators',
          notes: '',
          synopsis: 'buddy generate:all',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy types:generate',
          description: 'Generates types for your components, functions, & views',
          notes: '',
          synopsis: 'buddy types:generate',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy types:fix',
          description: 'Auto-fixes types for your components, functions, & views',
          notes: '',
          synopsis: 'buddy types:fix',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy domains',
          description: 'Alias for `buddy domains:list`',
          notes: '',
          synopsis: 'buddy domains',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy domains:add stacksjs.org',
          description: 'Adds a domain',
          notes: '',
          synopsis: 'buddy domains:add stacksjs.org',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy domains:remove stacksjs.org',
          description: 'Removes a domain',
          notes: '',
          synopsis: 'buddy domains:remove stacksjs.org',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy domains:list',
          description: 'Lists all domains',
          notes: '',
          synopsis: 'buddy domains:list',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy domains:update',
          description: 'Apply ./config/dns.ts updates',
          notes: '',
          synopsis: 'buddy domains:update',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy domains:purchase stacksjs.org',
          description: 'Purchase a new domain',
          notes: '',
          synopsis: 'buddy domains:purchase stacksjs.org',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy test',
          description: 'Runs test suite (unit & e2e)',
          notes: '',
          synopsis: 'buddy test',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy test:coverage',
          description: 'Runs test coverage',
          notes: '',
          synopsis: 'buddy test:coverage',
          aliases: [],
          arguments: [],
          options: [],
        },
        {
          signature: 'buddy test:types',
          description: 'Runs typecheck',
          notes: '',
          synopsis: 'buddy test:types',
          aliases: [],
          arguments: [],
          options: [],
        },
      ],
    }
  },
})
