/**
 * Code generation templates for the make command
 *
 * These templates use the {0}, {1}, etc. format for template substitution
 * which works with the @stacksjs/strings template function
 */

export const CODE_TEMPLATES = {
  action: `import { Action } from '@stacksjs/actions'

export default new Action({
  name: '{0}',
  description: '{0} action',

  handle() {
    return 'Hello World action'
  },
})`,

  // Stub variants emitted when the user passes --with-validation
  // or --with-auth to `buddy make:action`. Both share the basic Action
  // shape and add the relevant scaffolding inline rather than via
  // additional imports the user has to wire up themselves.
  actionWithValidation: `import { Action } from '@stacksjs/actions'
import { schema, validate } from '@stacksjs/validation'

export default new Action({
  name: '{0}',
  description: '{0} action',

  async handle(request) {
    // Replace these rules with whatever this action expects. The
    // returned object is typed to the rule shape; type-narrow further
    // by passing a generic to validate&lt;Payload&gt;().
    const data = await validate(request, {
      // example: title: schema.string().required().min(1),
    })

    return { ok: true, data }
  },
})`,

  actionWithAuth: `import { Action } from '@stacksjs/actions'

export default new Action({
  name: '{0}',
  description: '{0} action (authenticated)',

  async handle(request) {
    const user = await request.user()
    if (!user) {
      return new Response('Unauthorized', { status: 401 })
    }

    return { ok: true, userId: user.id }
  },
})`,

  actionWithBoth: `import { Action } from '@stacksjs/actions'
import { schema, validate } from '@stacksjs/validation'

export default new Action({
  name: '{0}',
  description: '{0} action (authenticated + validated)',

  async handle(request) {
    const user = await request.user()
    if (!user) {
      return new Response('Unauthorized', { status: 401 })
    }

    const data = await validate(request, {
      // example: title: schema.string().required().min(1),
    })

    return { ok: true, userId: user.id, data }
  },
})`,

  component: `<script setup lang="ts">
console.log('Hello World component created')
</script>

<template>
  <div>
    Some HTML block
  </div>
</template>`,

  page: `<script setup lang="ts">
console.log('Hello World page created')
</script>

<template>
  <div>
    Visit http://127.0.0.1/{0}
  </div>
</template>`,

  function: `// reactive state
const {0} = ref(0)

// functions that mutate state and trigger updates
function increment() {
  {0}.value++
}

export {
  {0},
  increment,
}`,

  language: `button:
  text: Copy`,

  notification: `import type { {0} } from '@stacksjs/types'

function content(): string {
  return 'example'
}

function send(): {0} {
  return {
    content: content(),
  }
}`,

  // {0} = PascalCase class name, {1} = kebab-case template name.
  // Scaffolded by \`buddy make:mail <Name>\` (stacksjs/stacks#1899).
  // The companion stx template lives in resources/emails/<kebab>.stx.
  mail: `import { Mailable } from '@stacksjs/email'

/**
 * Props passed into the {0} email. Add the fields your template
 * needs and they'll flow through to the stx template's \`props\` —
 * \`Mailable<{0}Props>\` ensures \`.template()\` and \`this.props\`
 * type-check against this shape (stacksjs/stacks#1903).
 */
export interface {0}Props extends Record<string, unknown> {
  /** Recipient email address. */
  to: string
  /** Display name for the greeting (falls back to 'there'). */
  userName?: string
}

/**
 * {0} mailable. Subclass of \`Mailable<{0}Props>\` — \`build()\` wires the
 * recipient / subject / template (props typed against \`{0}Props\`),
 * then \`send()\` (inherited) dispatches via the configured mail driver.
 *
 * @example
 * \`\`\`ts
 * await new {0}({ to: 'user@example.com', userName: 'Ada' }).send()
 * \`\`\`
 */
export class {0} extends Mailable<{0}Props> {
  constructor(private readonly props: {0}Props) {
    super()
  }

  build(): this {
    return this
      .to(this.props.to)
      .subject('{0}')
      .template('{1}', {
        to: this.props.to,
        userName: this.props.userName ?? 'there',
      })
  }
}`,

  // {0} = PascalCase class name (used in title + heading), {1} = same
  // kebab-name as the .ts file references. Mirrors the welcome.stx
  // shape so styles + Outlook conditionals match the bundled templates.
  mailTemplate: `<script server>
// Generated by \`buddy make:mail {0}\`. Edit freely — \`props\` is the
// object passed by the Mailable's \`build()\`.
const appName = props.appName || 'Stacks'
const appUrl = props.appUrl || 'https://stacksjs.com'
const userName = props.userName || 'there'
const primaryColor = props.primaryColor || '#3451b2'
const primaryColorDark = props.primaryColorDark || '#2a4198'
const subject = props.subject || '{0}'
const year = props.year || new Date().getFullYear()
</script>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{{ subject }}</title>
  <style>
    .button { display: inline-block; padding: 14px 32px; background-color: {{ primaryColor }}; color: #ffffff !important; text-decoration: none; border-radius: 6px; font-weight: 600; font-size: 16px; text-align: center; }
    .button:hover { background-color: {{ primaryColorDark }}; }
    @media only screen and (max-width: 600px) {
      .container { width: 100% !important; padding: 20px !important; }
      .content { padding: 24px !important; }
      .button { display: block !important; width: 100% !important; }
    }
  </style>
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f4f4f5; line-height: 1.6;">
  <table role="presentation" cellpadding="0" cellspacing="0" style="width: 100%; border-collapse: collapse;">
    <tr>
      <td style="padding: 40px 20px;">
        <table role="presentation" cellpadding="0" cellspacing="0" class="container" style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);">
          <tr>
            <td style="background-color: {{ primaryColor }}; padding: 30px 40px; text-align: center;">
              <h1 style="margin: 0; color: #ffffff; font-size: 24px; font-weight: 600;">{{ appName }}</h1>
            </td>
          </tr>
          <tr>
            <td class="content" style="padding: 40px;">
              <h2 style="margin: 0 0 20px; color: #111827; font-size: 20px; font-weight: 600;">{0}</h2>
              <p style="margin: 0 0 20px; color: #4b5563; font-size: 16px;">Hi {{ userName }},</p>
              <p style="margin: 0 0 20px; color: #4b5563; font-size: 16px;">Your message body goes here.</p>
              <table role="presentation" cellpadding="0" cellspacing="0" style="margin: 30px 0;">
                <tr><td><a href="{{ appUrl }}" class="button">Open {{ appName }}</a></td></tr>
              </table>
            </td>
          </tr>
          <tr>
            <td style="padding: 20px 40px; background-color: #f9fafb; border-top: 1px solid #e5e7eb;">
              <p style="margin: 0; color: #6b7280; font-size: 12px; text-align: center;">This is an automated message from {{ appName }}.</p>
              <p style="margin: 10px 0 0; color: #9ca3af; font-size: 11px; text-align: center;">&copy; {{ year }} {{ appName }}. All rights reserved.</p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`,

  middleware: `import type { Request } from '@stacksjs/router'
import { Middleware } from '@stacksjs/router'

export default new Middleware({
  name: '{0}',
  priority: 1,
  async handle(request: Request) {
    // Your middleware logic here
  },
})`,

  model: `import { defineModel } from '@stacksjs/orm'
import { schema } from '@stacksjs/validation'

export default defineModel({
  name: '{0}',
  table: '{1}',
  primaryKey: 'id',
  autoIncrement: true,

  traits: {
    useTimestamps: true,

    useSeeder: {
      count: 10,
    },
  },

  attributes: {
    // your attributes here
  },
} as const)`,

  migration: `import type { Database } from '@stacksjs/database'

export async function up(db: Database): Promise<void> {
  await db.schema
    .createTable('{0}')
    .addColumn('id', 'integer', col => col.autoIncrement().primaryKey())
    .execute()
}`,

  stackPackageJson: `{
  "name": "{0}",
  "version": "0.0.1",
  "type": "module",
  "stacks": {
    "name": "{1}",
    "description": "A Stacks extension"
  }
}`,

  // Add more templates as needed
  job: `import { Job } from '@stacksjs/jobs'

export default new Job({
  name: '{0}',
  description: '{0} job',

  async handle() {
    // Your job logic here
    console.log('Job executed')
  },
})`,

  event: `import { Event } from '@stacksjs/events'

export default new Event({
  name: '{0}',
  description: '{0} event',

  async handle(data: any) {
    // Your event handler logic here
    console.log('Event handled:', data)
  },
})`,

  listener: `import { Listener } from '@stacksjs/events'

export default new Listener({
  name: '{0}',
  description: '{0} listener',

  async handle(data: any) {
    // Your listener logic here
    console.log('Listener triggered:', data)
  },
})`,

  command: `import { Command } from '@stacksjs/cli'

export default new Command({
  name: '{0}',
  description: '{0} command',

  async handle() {
    // Your command logic here
    console.log('Command executed')
  },
})`,
} as const

export type TemplateKey = keyof typeof CODE_TEMPLATES
