import { readdir } from 'node:fs/promises'
import { path as p } from '@stacksjs/path'
import { logger } from '@stacksjs/logging'
import { storage } from '@stacksjs/storage'

logger.log('Generating action types...')

const domain = 'Actions'

const files = await readdir(p.appPath(domain), { recursive: true })

const validActions = `// This file is auto-generated by Stacks. Do not edit this file manually.
// If you wish to rename an action, please do so by editing the file name.
//
// For more information, please visit: https://stacksjs.org/docs

export type ActionPath = ${
  files
    .filter(file => file.endsWith('.ts'))
    .map(value => `'${domain}/${value.replace('.ts', '')}'`)
    .join(' | ')
}
`

await storage.writeFile(p.frameworkPath('types/actions.d.ts'), validActions)
