import { env as e, envEnum, parse } from '@stacksjs/env'
import { log } from '@stacksjs/logging'
import { path as p } from '@stacksjs/path'
import { storage } from '@stacksjs/storage'
import { existsSync, readFileSync } from 'node:fs'

/**
 * The keys already declared, read back out of the file this generator writes.
 *
 * Read as text rather than imported. `import { envKeys } from '...'` was how
 * this worked, via a relative path that climbs out of the package — fine in a
 * checkout, where it lands on `storage/framework/env.ts`, and unresolvable in
 * an installed app, where there is no such directory above `node_modules/
 * @stacksjs/actions/dist/`. Reading through `frameworkPath` finds the file
 * wherever the framework actually is, and a text read also avoids serving a
 * stale module from cache on the second pass of a watch run — this generator
 * rewrites that very file.
 */
function previouslyDeclaredKeys(): string[] {
  const file = p.frameworkPath('env.ts')
  if (!existsSync(file))
    return []

  const body = readFileSync(file, 'utf8').match(/export const envKeys = \[([^\]]*)\]/)?.[1] ?? ''

  return [...body.matchAll(/'([A-Z0-9_]+)'/g)].map(match => match[1]!)
}

/**
 * Keys `StacksEnv` already declares.
 *
 * Needed because the augmentation below merges into that interface, and a
 * merged declaration must repeat a property's type exactly or TypeScript
 * rejects the whole file. `APP_NAME` is `string | undefined` there and would
 * be `string` here, so the overlap has to be skipped rather than re-stated.
 *
 * Two locations because both layouts are real: a framework checkout has the
 * source, an installed app has only the shipped declarations.
 */
function frameworkDeclaredKeys(): Set<string> {
  const candidates = [
    p.frameworkPath('core/env/src/types.ts'),
    p.projectPath('node_modules/@stacksjs/env/dist/types.d.ts'),
  ]

  const file = candidates.find(candidate => existsSync(candidate))
  if (!file)
    return new Set()

  const body = readFileSync(file, 'utf8')
  const start = body.indexOf('interface StacksEnv')
  if (start === -1)
    return new Set()

  const block = body.slice(start, body.indexOf('\n}', start))

  return new Set([...block.matchAll(/^\s{2}([A-Z][A-Z0-9_]*)\??:/gm)].map(match => match[1]!))
}

/**
 * Which variables to declare.
 *
 * Read from the project's env files, not from `envKeys` alone — `envKeys`
 * lives in `storage/framework/env.ts`, which this generator writes at the
 * bottom from the same list it read at the top. Seeded that way the set could
 * only ever stay the same size, so a variable added to `.env` was never typed:
 * it fell through to the index signature as `string | number | true`, which is
 * assignable to nothing, and the error landed in `config/` on a line the
 * author had no reason to suspect. erbamarkets had 29 of its 58 variables in
 * that state, TYPESENSE_HOST among them.
 *
 * The previous list is still folded in, so a variable that is typed today does
 * not lose its type by being absent from `.env` on this machine.
 */
function resolveEnvKeys(): string[] {
  const keys = new Set<string>(previouslyDeclaredKeys())

  for (const file of ['.env', '.env.example']) {
    const path = p.projectPath(file)
    if (!existsSync(path))
      continue

    for (const key of Object.keys(parse(readFileSync(path, 'utf8')).parsed))
      keys.add(key)
  }

  return [...keys].sort()
}

/**
 * The text of `storage/framework/types/env.d.ts`.
 *
 * Pure, so the shape can be asserted without writing into the framework.
 */
export function renderEnvTypes(
  keys: string[],
  alreadyDeclared: ReadonlySet<string>,
  typeOf: (key: string) => string,
): string {
  const resolvedKeys = keys
  return `
// This file is auto-generated by Stacks. Do not edit this file manually.
// If you want to change the environment variables, please edit the .env file.
//
// For more information, please visit: https://stacksjs.com/docs

// Marks this file as a module, which is what makes the blocks below
// augmentations. In a global script file \`declare module 'x'\` declares an
// ambient module instead, shadowing the real one — which took '@stacksjs/env'
// down to only the members named here and broke every \`import { env }\` in
// config/ with "has no exported member 'env'".
export {}

declare module 'bun' {
  namespace env {
    ${resolvedKeys
      .map(key => `const ${key}: ${typeOf(key)}`)
      .join('\n    ')}
  }
}

// The \`env\` exported by '@stacksjs/env' is typed by StacksEnv, not by Bun's
// namespace, and its catch-all index signature gives any variable the
// framework does not name the type \`string | number | boolean | undefined\`.
// That is assignable to nothing, so reading a project's own variable in
// \`config/\` failed to typecheck against a plain \`string\` field. Declared
// here, each one gets the type its value implies.
declare module '@stacksjs/env' {
  interface StacksEnv {
    ${resolvedKeys
      .filter(key => !alreadyDeclared.has(key))
      .map(key => `${key}: ${typeOf(key)} | undefined`)
      .join('\n    ')}
  }
}
`
}

/**
 * Write `storage/framework/types/env.d.ts` and `storage/framework/env.ts`.
 *
 * This was a top-level script with nothing importing it — no command, no
 * build step, no test referenced the file — so the declarations it owns were
 * whatever the last person to run it by hand had produced. `generateTypes()`
 * calls it now.
 */
export async function generateEnvFiles(): Promise<void> {
  log.info('Generating type env files...')

  const resolvedKeys = resolveEnvKeys()
  const alreadyDeclared = frameworkDeclaredKeys()

  /** The type a variable's current value implies. */
  function typeOf(key: string): string {
    let type: string | undefined = typeof e[key as keyof typeof e]
    let value: string | boolean | number | undefined = e[key as keyof typeof e]

    if (!value) {
      if (envEnum[key]) {
        type = envEnum[key]?.map(item => `'${item}'`).join(' | ')
        value = envEnum[key]?.[0] // default to the first enum value
      }
      else {
        switch (type) {
          case 'number':
            value = '0'
            break
          case 'boolean':
            value = false
            break
          default:
            value = ''
        }
      }
    }

    type = 'string'
    if (typeof value === 'string') {
      if (value.toLowerCase() === 'true' || value.toLowerCase() === 'false') {
        type = 'boolean'
      }
      else if (!Number.isNaN(Number.parseFloat(value)) && Number.isFinite(Number(value))) {
        type = 'number'
      }
      else if (envEnum[key]) {
        type = envEnum[key].map(item => `'${item}'`).join(' | ')
      }
    }
    else if (typeof value === 'number') {
      type = 'number'
    }
    else if (typeof value === 'boolean') {
      type = 'boolean'
    }

    return type
  }

  const envTypes = renderEnvTypes(resolvedKeys, alreadyDeclared, typeOf)

  await storage.writeFile(p.frameworkPath('types/env.d.ts'), envTypes)

  log.info('  - ./storage/framework/env.ts')

  // generate ./storage/framework/env.ts file based on Bun.env
  const env = `
// This file is auto-generated by Stacks. Do not edit this file manually.
// If you want to change the environment variables, please edit the .env file.
//
// For more information, please visit: https://stacksjs.com/docs

export const envKeys = [
  ${resolvedKeys.map(key => `'${key}'`).join(',\n  ')}
] as const

export type EnvKey = typeof envKeys[number]
`

  await storage.writeFile(p.frameworkPath('env.ts'), env)

  log.info('  - ./storage/framework/env.d.ts')
}
