import { env as e, envEnum, parse } from '@stacksjs/env'
import { log } from '@stacksjs/logging'
import { path as p } from '@stacksjs/path'
import { storage } from '@stacksjs/storage'
import { existsSync, readFileSync } from 'node:fs'

/**
 * The keys already declared, read back out of the file this generator writes.
 *
 * Read as text rather than imported. `import { envKeys } from '...'` was how
 * this worked, via a relative path that climbs out of the package — fine in a
 * checkout, where it lands on `storage/framework/env.ts`, and unresolvable in
 * an installed app, where there is no such directory above `node_modules/
 * @stacksjs/actions/dist/`. Reading through `frameworkPath` finds the file
 * wherever the framework actually is, and a text read also avoids serving a
 * stale module from cache on the second pass of a watch run — this generator
 * rewrites that very file.
 */
function previouslyDeclaredKeys(): string[] {
  const file = p.frameworkPath('env.ts')
  if (!existsSync(file))
    return []

  const body = readFileSync(file, 'utf8').match(/export const envKeys = \[([^\]]*)\]/)?.[1] ?? ''

  return [...body.matchAll(/'([A-Z0-9_]+)'/g)].map(match => match[1]!)
}

/**
 * Which variables to declare.
 *
 * Read from the project's env files, not from `envKeys` alone — `envKeys`
 * lives in `storage/framework/env.ts`, which this generator writes at the
 * bottom from the same list it read at the top. Seeded that way the set could
 * only ever stay the same size, so a variable added to `.env` was never typed:
 * it fell through to the index signature as `string | number | true`, which is
 * assignable to nothing, and the error landed in `config/` on a line the
 * author had no reason to suspect. erbamarkets had 29 of its 58 variables in
 * that state, TYPESENSE_HOST among them.
 *
 * The previous list is still folded in, so a variable that is typed today does
 * not lose its type by being absent from `.env` on this machine.
 */
function resolveEnvKeys(): string[] {
  const keys = new Set<string>(previouslyDeclaredKeys())

  for (const file of ['.env', '.env.example']) {
    const path = p.projectPath(file)
    if (!existsSync(path))
      continue

    for (const key of Object.keys(parse(readFileSync(path, 'utf8')).parsed))
      keys.add(key)
  }

  return [...keys].sort()
}

/**
 * The text of `storage/framework/types/env.d.ts`.
 *
 * Bun's `env` namespace only. The `env` exported by '@stacksjs/env' used to be
 * augmented from here too, and that was the wrong source: the key set came
 * from whichever `.env` was on the machine running the generator, so a
 * variable set only in deploy secrets could never be typed, and each type was
 * read off the variable's live value, so the same variable could be `number`
 * here and `string` on a colleague's checkout. `StacksEnv` is now extended
 * from `config/env.ts`, which declares those variables anyway and is committed.
 *
 * Pure, so the shape can be asserted without writing into the framework.
 */
export function renderEnvTypes(
  keys: string[],
  typeOf: (key: string) => string,
): string {
  return `
// This file is auto-generated by Stacks. Do not edit this file manually.
// If you want to change the environment variables, please edit the .env file.
//
// This types \`Bun.env.SOMETHING\`. The \`env\` exported by '@stacksjs/env' is
// typed from your \`config/env.ts\` instead - declare a variable there and it
// is typed everywhere, with no generation step:
//
//   const envSchema = defineEnv({
//     STRIPE_WEBHOOK_SECRET: { validation: schema.string(), default: '' },
//   })
//
//   declare module '@stacksjs/env' {
//     interface StacksEnv extends InferEnv<typeof envSchema> {}
//   }
//
//   export default envSchema
//
// For more information, please visit: https://stacksjs.com/docs

// Marks this file as a module, which is what makes the block below an
// augmentation. In a global script file \`declare module 'x'\` declares an
// ambient module instead, shadowing the real one — which took '@stacksjs/env'
// down to only the members named here and broke every \`import { env }\` in
// config/ with "has no exported member 'env'".
export {}

declare module 'bun' {
  namespace env {
    ${keys
      .map(key => `const ${key}: ${typeOf(key)}`)
      .join('\n    ')}
  }
}
`
}

/**
 * Write `storage/framework/types/env.d.ts` and `storage/framework/env.ts`.
 *
 * This was a top-level script with nothing importing it — no command, no
 * build step, no test referenced the file — so the declarations it owns were
 * whatever the last person to run it by hand had produced. `generateTypes()`
 * calls it now.
 */
export async function generateEnvFiles(): Promise<void> {
  log.info('Generating type env files...')

  const resolvedKeys = resolveEnvKeys()

  /** The type a variable's current value implies. */
  function typeOf(key: string): string {
    let type: string | undefined = typeof e[key as keyof typeof e]
    let value: string | boolean | number | undefined = e[key as keyof typeof e]

    if (!value) {
      if (envEnum[key]) {
        type = envEnum[key]?.map(item => `'${item}'`).join(' | ')
        value = envEnum[key]?.[0] // default to the first enum value
      }
      else {
        switch (type) {
          case 'number':
            value = '0'
            break
          case 'boolean':
            value = false
            break
          default:
            value = ''
        }
      }
    }

    type = 'string'
    if (typeof value === 'string') {
      if (value.toLowerCase() === 'true' || value.toLowerCase() === 'false') {
        type = 'boolean'
      }
      else if (!Number.isNaN(Number.parseFloat(value)) && Number.isFinite(Number(value))) {
        type = 'number'
      }
      else if (envEnum[key]) {
        type = envEnum[key].map(item => `'${item}'`).join(' | ')
      }
    }
    else if (typeof value === 'number') {
      type = 'number'
    }
    else if (typeof value === 'boolean') {
      type = 'boolean'
    }

    return type
  }

  const envTypes = renderEnvTypes(resolvedKeys, typeOf)

  await storage.writeFile(p.frameworkPath('types/env.d.ts'), envTypes)

  log.info('  - ./storage/framework/env.ts')

  // generate ./storage/framework/env.ts file based on Bun.env
  const env = `
// This file is auto-generated by Stacks. Do not edit this file manually.
// If you want to change the environment variables, please edit the .env file.
//
// For more information, please visit: https://stacksjs.com/docs

export const envKeys = [
  ${resolvedKeys.map(key => `'${key}'`).join(',\n  ')}
] as const

export type EnvKey = typeof envKeys[number]
`

  await storage.writeFile(p.frameworkPath('env.ts'), env)

  log.info('  - ./storage/framework/env.d.ts')
}
