/**
 * `buddy generate:erd` - an entity-relationship diagram derived from models
 * (stacksjs/stacks#439).
 *
 * The rendering lives in `@stacksjs/database` (`./erd`) and is pure. This file
 * is the I/O half: find the models, import them, hand the definitions over,
 * and write the result.
 *
 * Models are collected through `resolveModelSources`, the same helper the
 * migration and VSchema generators use, so the diagram covers exactly the
 * tables the migrations create - the framework's own models included, and the
 * nested ones under `commerce/`, `Content/` and friends. Reading only
 * `app/Models` would draw a schema missing most of itself.
 */

import type { DiagrammableModel } from '@stacksjs/database'
import { dirname } from 'node:path'
import { renderErd, resolveModelSources, toDiagrammableModel } from '@stacksjs/database'
import { log } from '@stacksjs/logging'
import { path } from '@stacksjs/path'
import { fs } from '@stacksjs/storage'

export interface GenerateErdOptions {
  /** Return the diagram without writing it. */
  dryRun?: boolean
  /** Output path, relative to the project root. */
  out?: string
  /** Relationships only, no column lists. */
  noColumns?: boolean
  /** Restrict to these tables or model names, plus their mutual relationships. */
  only?: string[]
}

export type GenerateErdResult =
  | { ok: false, error: string }
  | { ok: true, diagram: string, path: string, modelCount: number, skipped: string[] }

/**
 * Resolve a model file's table name.
 *
 * Mirrors the framework convention: an explicit `table` wins, otherwise the
 * model name is pluralized. Kept local and deliberately simple rather than
 * reaching for the ORM's resolver, which needs a configured database
 * connection this command has no reason to open.
 */
function tableNameFor(definition: any, fileName: string): string {
  if (definition?.table)
    return definition.table

  const name: string = definition?.name ?? fileName
  const snake = name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase()

  if (/(?:s|x|z|ch|sh)$/.test(snake))
    return `${snake}es`
  if (/[^aeiou]y$/.test(snake))
    return `${snake.slice(0, -1)}ies`
  return `${snake}s`
}

/**
 * Wrap the diagram in a fenced Mermaid block when the target is markdown.
 *
 * A `.md` file holding a bare `erDiagram` renders as a paragraph of broken
 * text; a `.mmd` file holding a fence is not a Mermaid file. The extension is
 * the only signal available, and getting it wrong is visible immediately, so
 * this decides rather than asking.
 */
export function wrapForTarget(diagram: string, outPath: string): string {
  return outPath.endsWith('.md')
    ? `# Entity Relationships\n\n<!-- Generated by \`buddy generate:erd\`. Edit your models, not this. -->\n\n\`\`\`mermaid\n${diagram}\n\`\`\`\n`
    : `${diagram}\n`
}

export async function generateErd(options: GenerateErdOptions = {}): Promise<GenerateErdResult> {
  const sources = resolveModelSources()
  if (!sources || sources.models.length === 0)
    return { ok: false, error: 'No models found. The diagram is derived from your models, so there is nothing to generate.' }

  const models: DiagrammableModel[] = []
  const skipped: string[] = []

  for (const source of sources.models) {
    try {
      const definition = (await import(source.file)).default
      if (!definition)
        continue
      models.push(toDiagrammableModel(definition, tableNameFor(definition, source.name)))
    }
    catch (error) {
      // One unreadable model must not sink the command, but it must not vanish
      // either: a missing table in a diagram is indistinguishable from a table
      // that does not exist.
      skipped.push(`${source.name}: ${(error as Error).message}`)
    }
  }

  for (const failure of skipped)
    log.warn(`[generate:erd] skipped ${failure}`)

  if (models.length === 0)
    return { ok: false, error: 'Every model failed to load; nothing to diagram.' }

  const diagram = renderErd(models, {
    columns: !options.noColumns,
    ...(options.only && options.only.length > 0 ? { only: options.only } : {}),
  })

  const outPath = path.projectPath(options.out ?? 'docs/erd.md')

  if (!options.dryRun) {
    fs.mkdirSync(dirname(outPath), { recursive: true })
    await Bun.write(outPath, wrapForTarget(diagram, outPath))
  }

  return { ok: true, diagram, path: outPath, modelCount: models.length, skipped }
}
