name: 💡 Feature request
description: 'For ideas or feature requests: please make a pull request or open an issue.'
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Please describe the feature
      description: A concise description of what you would like to experience.
    validations:
      required: true
