/**
 * A generated `ADD CONSTRAINT` has to displace whatever already holds that
 * column, and two things made it not.
 *
 * The first is the name. A column declared `REFERENCES` inline in CREATE TABLE
 * gets Postgres's own name - `<table>_<column>_fkey` - while the generator
 * emits `<table>_<column>_fk`. Dropping only its own name leaves both in place,
 * and the older one wins every time they disagree: adding ON DELETE CASCADE to
 * a relation that shipped without it appeared to succeed and changed nothing,
 * because the original still refused the delete. That is the worst shape a
 * migration bug can have, because the migration reports success.
 *
 * The second is the header. `buddy generate:migrations` writes a `-- @generated`
 * comment on line one, splitting on `;` glues it to the first statement, and an
 * anchored match then failed on exactly one statement per file - the first. So
 * the first constraint in every generated migration was the one that never
 * became idempotent, and re-running the file failed on its own opening line.
 */

import { describe, expect, it } from 'bun:test'
import { idempotentSql } from '../src/migrations'

const ADD_FK = 'ALTER TABLE "team_members" ADD CONSTRAINT "team_members_team_id_fk" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE;'

describe('a foreign key added over an existing one', () => {
  it('drops the name it is about to use', () => {
    expect(idempotentSql(ADD_FK)).toContain('DROP CONSTRAINT IF EXISTS "team_members_team_id_fk"')
  })

  it('also drops the name Postgres would have given an inline REFERENCES', () => {
    // The one that actually holds the column on a table created before the
    // relation declared a cascade.
    expect(idempotentSql(ADD_FK)).toContain('DROP CONSTRAINT IF EXISTS "team_members_team_id_fkey"')
  })

  it('drops both before adding, not after', () => {
    const out = idempotentSql(ADD_FK)

    expect(out.indexOf('DROP CONSTRAINT IF EXISTS "team_members_team_id_fkey"'))
      .toBeLessThan(out.indexOf('ADD CONSTRAINT'))
  })

  it('leaves a non-foreign-key constraint with only its own drop', () => {
    // A unique or check constraint has no column-level spelling to collide
    // with, so inventing an `_fkey` name for it would drop nothing and read as
    // though it might.
    const out = idempotentSql('ALTER TABLE "t" ADD CONSTRAINT "t_slug_unique" UNIQUE ("slug");')

    expect(out).toContain('DROP CONSTRAINT IF EXISTS "t_slug_unique"')
    expect(out).not.toContain('_fkey')
  })
})

describe('the generated header', () => {
  const withHeader = `-- @generated by \`buddy migrate:regenerate\` - edits will be overwritten\n${ADD_FK}`

  it('does not stop the first statement being made idempotent', () => {
    // The whole bug: one statement per file, always the first, silently skipped.
    expect(idempotentSql(withHeader)).toContain('DROP CONSTRAINT IF EXISTS "team_members_team_id_fk"')
  })

  it('stays at the top of the file', () => {
    expect(idempotentSql(withHeader).startsWith('-- @generated')).toBe(true)
  })

  it('does the same for the second statement, which never had the problem', () => {
    const two = `${withHeader}\nALTER TABLE "team_members" ADD CONSTRAINT "team_members_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE;`
    const out = idempotentSql(two)

    expect(out).toContain('DROP CONSTRAINT IF EXISTS "team_members_user_id_fkey"')
    expect(out).toContain('DROP CONSTRAINT IF EXISTS "team_members_team_id_fkey"')
  })
})

describe('re-applying the transform', () => {
  it('is a no-op, because migrate rewrites the files on disk every run', () => {
    const once = idempotentSql(`-- @generated\n${ADD_FK}`)

    expect(idempotentSql(once)).toBe(once)
  })
})
