/**
 * stacksjs/stacks#2234 — `regenerateMigrationCorpus` unlinked EVERY `.sql` in
 * `database/migrations` before writing, including migrations no model
 * describes and no rerun could ever re-emit.
 *
 * The reporting app enforced a privacy invariant with a hand-written
 * `DROP COLUMN` migration and anchored a CI guardrail to its contents. A
 * regeneration removed both at once, and "rebuild the corpus from the models"
 * had no way to know the difference, because generator output and authored
 * files sit in one directory with no discriminator.
 *
 * The discriminator is now a header on every emitted file. These tests cover
 * the classification directly; the emit/delete wiring that consumes it needs a
 * live model graph and a database, so it is exercised through the CLI rather
 * than here.
 */

import { afterEach, describe, expect, it } from 'bun:test'
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { GENERATED_MIGRATION_MARKER, isGeneratedMigration } from '../src/migrations'

const TMP = join(import.meta.dir, '.tmp-generated-marker')

function write(name: string, body: string): void {
  mkdirSync(TMP, { recursive: true })
  writeFileSync(join(TMP, name), body)
}

afterEach(() => {
  rmSync(TMP, { recursive: true, force: true })
})

describe('isGeneratedMigration (#2234)', () => {
  it('recognises a file the generator wrote', () => {
    write('0000000001-create-users-table.sql', `${GENERATED_MIGRATION_MARKER}\nCREATE TABLE users (id INTEGER);\n`)
    expect(isGeneratedMigration(TMP, '0000000001-create-users-table.sql')).toBe(true)
  })

  it('does NOT recognise a hand-authored file', () => {
    // The exact file from the report: a DROP COLUMN enforcing a privacy
    // invariant, using the generator's own ordinal naming. Filename is not a
    // usable signal — only the marker is.
    write('0000000011-drop-geo-region-city.sql', 'ALTER TABLE page_views DROP COLUMN IF EXISTS region;\n')
    expect(isGeneratedMigration(TMP, '0000000011-drop-geo-region-city.sql')).toBe(false)
  })

  it('does not match a file that merely mentions the word generated', () => {
    write('x.sql', '-- this table is generated by the importer\nCREATE TABLE x (id INTEGER);\n')
    expect(isGeneratedMigration(TMP, 'x.sql')).toBe(false)
  })

  it('treats an unreadable file as NOT generated', () => {
    // "Cannot prove it is ours" has to mean "keep it" — the failure direction
    // matters, because the other one deletes someone's work.
    expect(isGeneratedMigration(TMP, 'no-such-file.sql')).toBe(false)
  })

  it('only reads the head of the file, so a later mention does not count', () => {
    const filler = 'SELECT 1;\n'.repeat(60)
    write('late.sql', `CREATE TABLE y (id INTEGER);\n${filler}${GENERATED_MIGRATION_MARKER}\n`)
    expect(isGeneratedMigration(TMP, 'late.sql')).toBe(false)
  })

  it('every line of the marker is a SQL comment, so a stamped file still parses', () => {
    // If any header line were not a comment it would become a syntax error in
    // every generated migration. The marker is two lines - `qb:generated` for the
    // runner, which only recognizes it at the very start of the file, and the
    // human-facing note under it - so this checks each line rather than just the
    // first, which is what it used to do when the marker was one line.
    const lines = GENERATED_MIGRATION_MARKER.split('\n')
    expect(lines.length).toBeGreaterThan(1)
    for (const line of lines)
      expect(line.startsWith('--')).toBe(true)
  })

  it('leads with the runner\'s own marker, which it only reads at the start', () => {
    // Ordering is load-bearing: bun-query-builder keeps its own record of which
    // migrations it generated, and only honours `qb:generated` on the first line.
    // Behind anything else, every file this generator writes reads as
    // hand-authored, and MySQL - which has no `ADD CONSTRAINT IF NOT EXISTS` -
    // stops the whole corpus on a foreign key that is already there.
    expect(GENERATED_MIGRATION_MARKER.split('\n')[0]).toBe('-- qb:generated')
  })
})

describe('a stamped file still yields its statements', () => {
  it('sqlStatementsOf skips the header and returns the SQL', async () => {
    // The header must not be glued onto the first statement, or every
    // regenerated migration executes a comment instead of its DDL.
    const { sqlStatementsOf } = await import('../src/migrations')
    const body = `${GENERATED_MIGRATION_MARKER}\nCREATE TABLE users (id INTEGER);\nCREATE TABLE posts (id INTEGER);\n`

    const statements = sqlStatementsOf(body)

    expect(statements).toHaveLength(2)
    expect(statements[0]).toContain('CREATE TABLE users')
    expect(statements[1]).toContain('CREATE TABLE posts')
    expect(statements.join(' ')).not.toContain('@generated')
  })

  it('round-trips through a file on disk', () => {
    write('0000000001-create-users-table.sql', `${GENERATED_MIGRATION_MARKER}\nCREATE TABLE users (id INTEGER);\n`)
    const contents = readFileSync(join(TMP, '0000000001-create-users-table.sql'), 'utf8')

    // The whole marker leads the file - not just its first line, and with the
    // body still behind it.
    expect(contents.startsWith(`${GENERATED_MIGRATION_MARKER}\n`)).toBe(true)
    expect(contents).toContain('CREATE TABLE users')
  })
})
