import { describe, expect, it } from 'bun:test'
import { createdTableName, droppedIndexName, generatedStatementIsRedundant, indexCommittedMigrations, indexShape, persistedGroupLabel } from '../src/migrations'

describe('createdTableName', () => {
  it('reads the table out of every spelling a corpus uses', () => {
    expect(createdTableName('CREATE TABLE notification_deliveries (id INTEGER)')).toBe('notification_deliveries')
    expect(createdTableName('CREATE TABLE IF NOT EXISTS "notifications" (id INTEGER)')).toBe('notifications')
    expect(createdTableName('  create table `team_members` (id INTEGER)')).toBe('team_members')
    expect(createdTableName('CREATE TABLE [releases] (id INTEGER)')).toBe('releases')
  })

  it('is not fooled by a statement that merely mentions a table', () => {
    expect(createdTableName('ALTER TABLE releases ADD COLUMN tag TEXT')).toBeUndefined()
    expect(createdTableName('UPDATE notification_deliveries SET channel = \'email\'')).toBeUndefined()
    expect(createdTableName('CREATE INDEX idx_releases_tag ON releases (tag)')).toBeUndefined()
  })
})

describe('generatedStatementIsRedundant', () => {
  it('skips a CREATE for a table the corpus already creates, however it is written', () => {
    // The #2323 case. The committed file and the generator do not have to
    // agree on whitespace, quoting, or column order for the table to already
    // exist, and a textual comparison wrote a second CREATE whenever they
    // differed by so much as a space.
    const index = indexCommittedMigrations([
      `CREATE TABLE notification_deliveries (\n  id INTEGER PRIMARY KEY,\n  channel TEXT\n);`,
    ])

    expect(generatedStatementIsRedundant(
      `CREATE TABLE IF NOT EXISTS "notification_deliveries" (id INTEGER PRIMARY KEY, channel TEXT, status TEXT)`,
      index,
    )).toBe(true)
  })

  it('still writes a CREATE for a table nothing has created', () => {
    const index = indexCommittedMigrations(['CREATE TABLE users (id INTEGER);'])

    expect(generatedStatementIsRedundant('CREATE TABLE teams (id INTEGER)', index)).toBe(false)
  })

  it('compares non-CREATE statements on their text, not their table', () => {
    // An ALTER or an UPDATE is only redundant if it is the same statement.
    // Matching those on the table name would drop every later change to a
    // table the corpus happens to create.
    const index = indexCommittedMigrations([
      'CREATE TABLE releases (id INTEGER);\nALTER TABLE releases ADD COLUMN tag TEXT;',
    ])

    expect(generatedStatementIsRedundant('ALTER TABLE releases ADD COLUMN tag TEXT', index)).toBe(true)
    expect(generatedStatementIsRedundant('ALTER TABLE releases ADD COLUMN channel TEXT', index)).toBe(false)
  })

  it('ignores whitespace differences on the statements it matches textually', () => {
    const index = indexCommittedMigrations(['ALTER TABLE  releases   ADD COLUMN tag TEXT;'])

    expect(generatedStatementIsRedundant('ALTER TABLE releases ADD COLUMN tag TEXT', index)).toBe(true)
  })

  it('treats an empty corpus as creating nothing', () => {
    const index = indexCommittedMigrations([])

    expect(index.createdTables.size).toBe(0)
    expect(generatedStatementIsRedundant('CREATE TABLE users (id INTEGER)', index)).toBe(false)
  })

  it('reads the first statement of a file that opens with a comment', () => {
    // Every generated file opens with its `@generated` header, and every
    // hand-written one with an explanation. Split on `;` alone, the header was
    // glued to the CREATE, which then never matched.
    const index = indexCommittedMigrations([
      '-- qb:generated\n-- @generated by `buddy migrate:regenerate` - edits will be overwritten\nCREATE TABLE IF NOT EXISTS "content_reports" (id INTEGER);',
      '-- The catalog sorts by length.\n-- Comments avoid semicolons.\n\nCREATE INDEX IF NOT EXISTS "trails_trails_distance_index" ON "trails" ("distance");',
    ])

    expect(generatedStatementIsRedundant('CREATE TABLE IF NOT EXISTS "content_reports" ("id" INTEGER PRIMARY KEY, "reason" TEXT)', index)).toBe(true)
    expect(generatedStatementIsRedundant('CREATE INDEX IF NOT EXISTS "trails_distance_index" ON "trails" ("distance")', index)).toBe(true)
  })

  it('indexes every CREATE in a multi-statement file', () => {
    const index = indexCommittedMigrations([
      'CREATE TABLE a (id INTEGER);\nCREATE TABLE IF NOT EXISTS b (id INTEGER);\nALTER TABLE a ADD COLUMN x TEXT;',
    ])

    expect([...index.createdTables].sort()).toEqual(['a', 'b'])
  })
})

describe('indexShape', () => {
  it('ignores the name, the quoting and the whitespace', () => {
    expect(indexShape('CREATE INDEX IF NOT EXISTS "trails_trails_bbox_index" ON "trails" ("min_lat", "max_lat")')?.key)
      .toBe(indexShape('create index trails_bbox_index on trails (min_lat,  max_lat);')?.key)
  })

  it('keeps everything that changes what the index does', () => {
    const plain = indexShape('CREATE INDEX a ON trails (country, distance)')!.key

    expect(indexShape('CREATE UNIQUE INDEX a ON trails (country, distance)')!.key).not.toBe(plain)
    expect(indexShape('CREATE INDEX a ON trails (distance, country)')!.key).not.toBe(plain)
    expect(indexShape('CREATE INDEX a ON trails (country, distance DESC)')!.key).not.toBe(plain)
    expect(indexShape('CREATE INDEX a ON trails (country, distance) WHERE distance IS NOT NULL')!.key).not.toBe(plain)
    expect(indexShape('CREATE INDEX a ON routes (country, distance)')!.key).not.toBe(plain)
  })

  it('treats an explicit ASC as the default it is', () => {
    expect(indexShape('CREATE INDEX a ON t (x ASC)')!.key).toBe(indexShape('CREATE INDEX b ON t (x)')!.key)
  })

  it('reads an expression column to its own closing bracket', () => {
    expect(indexShape('CREATE UNIQUE INDEX users_email ON users (lower(email)) WHERE deleted_at IS NULL')).toEqual({
      name: 'users_email',
      table: 'users',
      key: 'unique users (lower(email)) where deleted_at is null',
    })
  })

  it('reads a statement split across lines', () => {
    expect(indexShape('CREATE UNIQUE INDEX IF NOT EXISTS "events_uuid_unique"\n  ON "events" ("uuid")')?.name).toBe('events_uuid_unique')
  })

  it('is not an index for anything else', () => {
    expect(indexShape('CREATE TABLE trails (id INTEGER)')).toBeUndefined()
    expect(indexShape('DROP INDEX IF EXISTS trails_bbox_index')).toBeUndefined()
  })
})

describe('droppedIndexName', () => {
  it('reads the name in every spelling', () => {
    expect(droppedIndexName('DROP INDEX IF EXISTS "trails_bbox_index"')).toBe('trails_bbox_index')
    expect(droppedIndexName('drop index main.Trails_Bbox_Index')).toBe('trails_bbox_index')
    expect(droppedIndexName('DROP TABLE trails')).toBeUndefined()
  })
})

describe('generatedStatementIsRedundant for indexes', () => {
  // The model names it `trails_bbox_index`; the generator that wrote the corpus
  // prefixed the table again. Without a model snapshot - a fresh checkout - the
  // differ proposes every model index, and each used to be written and applied
  // as a second, identical index beside the committed one.
  const corpus = [
    'CREATE TABLE IF NOT EXISTS "trails" ("id" INTEGER PRIMARY KEY, "uuid" TEXT, "min_lat" REAL, "max_lat" REAL);',
    'CREATE INDEX IF NOT EXISTS "trails_trails_bbox_index" ON "trails" ("min_lat", "max_lat");',
    'CREATE UNIQUE INDEX IF NOT EXISTS "trails_trails_uuid_unique" ON "trails" ("uuid");',
  ]

  it('skips an index the corpus already builds under another name', () => {
    const index = indexCommittedMigrations(corpus)

    expect(generatedStatementIsRedundant('CREATE INDEX IF NOT EXISTS "trails_bbox_index" ON "trails" ("min_lat", "max_lat")', index)).toBe(true)
    expect(generatedStatementIsRedundant('CREATE UNIQUE INDEX IF NOT EXISTS "trails_uuid_unique" ON "trails" ("uuid")', index)).toBe(true)
  })

  it('still writes an index the corpus does not build', () => {
    const index = indexCommittedMigrations(corpus)

    // Same columns, but unique where the corpus is not: a different index.
    expect(generatedStatementIsRedundant('CREATE UNIQUE INDEX IF NOT EXISTS "trails_bbox_unique" ON "trails" ("min_lat", "max_lat")', index)).toBe(false)
    expect(generatedStatementIsRedundant('CREATE UNIQUE INDEX IF NOT EXISTS "events_uuid_unique" ON "events" ("uuid")', index)).toBe(false)
  })

  it('writes an index again once a later migration has dropped it', () => {
    const index = indexCommittedMigrations([...corpus, 'DROP INDEX IF EXISTS "trails_trails_bbox_index";'])

    expect(generatedStatementIsRedundant('CREATE INDEX IF NOT EXISTS "trails_bbox_index" ON "trails" ("min_lat", "max_lat")', index)).toBe(false)
  })

  it('does not let an IF NOT EXISTS on a taken name stand for an index it never built', () => {
    const index = indexCommittedMigrations([
      'CREATE INDEX IF NOT EXISTS "trails_geo" ON "trails" ("min_lat");',
      'CREATE INDEX IF NOT EXISTS "trails_geo" ON "trails" ("max_lat");',
    ])

    expect(generatedStatementIsRedundant('CREATE INDEX "other" ON "trails" ("max_lat")', index)).toBe(false)
  })
})

describe('persistedGroupLabel', () => {
  it('keeps the label of a group that still creates its table', () => {
    expect(persistedGroupLabel('create-events-table', ['CREATE TABLE events (id INTEGER)', 'CREATE INDEX e ON events (id)'])).toBe('create-events-table')
  })

  it('names a lone surviving index after the index', () => {
    expect(persistedGroupLabel('create-events-table', ['CREATE UNIQUE INDEX IF NOT EXISTS "events_uuid_unique" ON "events" ("uuid")']))
      .toBe('create-events_uuid_unique-index-in-events')
  })

  it('names several surviving indexes after the table', () => {
    expect(persistedGroupLabel('create-events-table', ['CREATE INDEX a ON events (x)', 'CREATE INDEX b ON events (y)'])).toBe('create-events-indexes')
  })

  it('leaves every other label alone', () => {
    expect(persistedGroupLabel('alter-events-columns', ['ALTER TABLE events ADD COLUMN x TEXT'])).toBe('alter-events-columns')
  })
})
