/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'Carbon:cafe': typeof import('~icons/carbon/cafe')['default']
    'Carbon:logoTwitter': typeof import('~icons/carbon/logo-twitter')['default']
    'Mdi:heart': typeof import('~icons/mdi/heart')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
  }
}
