await Bun.build({
  entrypoints: ['./src/index.ts'],
  outdir: './dist',
  format: 'esm',
  target: 'bun',

  external: [
    '@stacksjs/cli',
    '@stacksjs/logging',
    '@stacksjs/arrays',
    '@stacksjs/collections',
    '@stacksjs/config',
    '@stacksjs/enums',
    '@stacksjs/env',
    '@stacksjs/error-handling',
    '@stacksjs/objects',
    '@stacksjs/path',
    '@stacksjs/storage',
    '@stacksjs/types',
    '@stacksjs/validation',
    '@stacksjs/strings',
    'bun',
    'dinero.js',
    '@dinero.js/currencies',
    'export-size',
    'hookable',
    'js-yaml',
    'macroable',
    'neverthrow',
    'perfect-debounce',
    'vue',
    'vueuse',
    '@vueuse/core',
    '@vueuse/math',
    '@vueuse/head',
    '@vueuse/shared',
    // 'pretty-bytes',
    'yaml',
    'magic-regexp',
    'vue-demi',
  ],

})
