#!/bin/sh

# Get the script's directory
script_dir=$(realpath $(dirname "$0"))

# Get all directories in the core path
dirs=$(find "$script_dir/../src" -type d)

# Check if no directories found
if [ -z "$dirs" ]; then
  echo "No core packages found"
  exit 1
fi

# Loop through each directory
for dir in $dirs; do
  echo ""
  echo "🏗️  Releasing..."
  echo "📦 $dir"

  # Change to the directory
  cd $dir

  npm publish --access public --no-git-checks

  # Check if the build command was successful
  if [ $? -ne 0 ]; then
    echo "Failed to publish $dir"
    exit 1
  fi

  echo "✅ Build complete"
  echo ""

  # Change back to the original directory
  cd - >/dev/null
done
