#!/bin/sh

# Get the script's directory
script_dir=$(realpath $(dirname "$0"))

# Get all directories in the core path except for src/bun-create
dirs=$(find "$script_dir/../" -type d -maxdepth 1 -not -path "$script_dir/../bun-create")

# Get all directories in src/bun-create up to two levels deep
bun_create_dirs=$(find "$script_dir/../src" -type d -maxdepth 2)

# Combine the two directory lists
dirs="$dirs $bun_create_dirs"

# Check if no directories found
if [ -z "$dirs" ]; then
  echo "No core packages found"
  exit 1
fi

# Loop through each directory
for dir in $dirs; do
  echo ""
  echo "🏗️  Releasing..."
  echo "📦 $dir"

  # Change to the directory
  cd $dir

  npm publish --access public --no-git-checks || echo "Failed to publish $dir"

  # Check if the build command was successful
  if [ $? -ne 0 ]; then
    echo "Failed to publish $dir"
    exit 1
  fi

  echo "✅ Latest is published"
  echo ""

  # Change back to the original directory
  cd - >/dev/null
done
