/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../../../resources/components/Button.vue')['default']
    CallToAction: typeof import('./../../../resources/components/marketing/CallToAction.vue')['default']
    Container: typeof import('./../../../resources/components/Container.vue')['default']
    Faqs: typeof import('./../../../resources/components/marketing/Faqs.vue')['default']
    Feature: typeof import('./../../../resources/components/marketing/Feature.vue')['default']
    Fields: typeof import('./../../../resources/components/marketing/Fields.vue')['default']
    Footer: typeof import('./../../../resources/components/marketing/Footer.vue')['default']
    Header: typeof import('./../../../resources/components/marketing/Header.vue')['default']
    HelloWorld: typeof import('./../../../resources/components/HelloWorld.vue')['default']
    Hero: typeof import('./../../../resources/components/marketing/Hero.vue')['default']
    Layout: typeof import('./../../../resources/components/marketing/Layout.vue')['default']
    Logo: typeof import('./../../../resources/components/Logo.vue')['default']
    NavLink: typeof import('./../../../resources/components/marketing/NavLink.vue')['default']
    Plan: typeof import('./../../../resources/components/marketing/Plan.vue')['default']
    Playground: typeof import('./../../../resources/components/Playground.vue')['default']
    Pricing: typeof import('./../../../resources/components/marketing/Pricing.vue')['default']
    PrimaryFeatures: typeof import('./../../../resources/components/marketing/PrimaryFeatures.vue')['default']
    README: typeof import('./../../../resources/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryFeatures: typeof import('./../../../resources/components/marketing/SecondaryFeatures.vue')['default']
    SlimLayout: typeof import('./../../../resources/components/marketing/SlimLayout.vue')['default']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    Testimonials: typeof import('./../../../resources/components/marketing/Testimonials.vue')['default']
  }
}
