/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./../../../resources/components/Buttons/Counter.vue')['default']
    HelloWorld: typeof import('./../../../resources/components/HelloWorld.vue')['default']
    Logo: typeof import('./../../../resources/components/Logo.vue')['default']
    Playground: typeof import('./../../../resources/components/Playground.vue')['default']
    README: typeof import('./../../../resources/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    TheCounter: typeof import('./../../../resources/components/TheCounter.vue')['default']
    TheFooter: typeof import('./../../../resources/components/TheFooter.vue')['default']
    TheInput: typeof import('./../../../resources/components/TheInput.vue')['default']
    ToggleDark: typeof import('./../../../resources/components/Buttons/ToggleDark.vue')['default']
  }
}
