/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/actions/': RouteRecordInfo<'/actions/', '/actions', Record<never, never>, Record<never, never>>,
    '/buddy/': RouteRecordInfo<'/buddy/', '/buddy', Record<never, never>, Record<never, never>>,
    '/commands/': RouteRecordInfo<'/commands/', '/commands', Record<never, never>, Record<never, never>>,
    '/components/': RouteRecordInfo<'/components/', '/components', Record<never, never>, Record<never, never>>,
    '/components/billing/active-plan': RouteRecordInfo<'/components/billing/active-plan', '/components/billing/active-plan', Record<never, never>, Record<never, never>>,
    '/components/billing/card-brands': RouteRecordInfo<'/components/billing/card-brands', '/components/billing/card-brands', Record<never, never>, Record<never, never>>,
    '/components/billing/payment-method': RouteRecordInfo<'/components/billing/payment-method', '/components/billing/payment-method', Record<never, never>, Record<never, never>>,
    '/components/billing/payment-method-list': RouteRecordInfo<'/components/billing/payment-method-list', '/components/billing/payment-method-list', Record<never, never>, Record<never, never>>,
    '/components/billing/plans': RouteRecordInfo<'/components/billing/plans', '/components/billing/plans', Record<never, never>, Record<never, never>>,
    '/components/skeleton/loading-card': RouteRecordInfo<'/components/skeleton/loading-card', '/components/skeleton/loading-card', Record<never, never>, Record<never, never>>,
    '/components/skeleton/loading-details': RouteRecordInfo<'/components/skeleton/loading-details', '/components/skeleton/loading-details', Record<never, never>, Record<never, never>>,
    '/dependencies/': RouteRecordInfo<'/dependencies/', '/dependencies', Record<never, never>, Record<never, never>>,
    '/deployments/': RouteRecordInfo<'/deployments/', '/deployments', Record<never, never>, Record<never, never>>,
    '/deployments/[id]': RouteRecordInfo<'/deployments/[id]', '/deployments/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dns/': RouteRecordInfo<'/dns/', '/dns', Record<never, never>, Record<never, never>>,
    '/emails/': RouteRecordInfo<'/emails/', '/emails', Record<never, never>, Record<never, never>>,
    '/environment/': RouteRecordInfo<'/environment/', '/environment', Record<never, never>, Record<never, never>>,
    '/functions/': RouteRecordInfo<'/functions/', '/functions', Record<never, never>, Record<never, never>>,
    '/health/': RouteRecordInfo<'/health/', '/health', Record<never, never>, Record<never, never>>,
    '/jobs/': RouteRecordInfo<'/jobs/', '/jobs', Record<never, never>, Record<never, never>>,
    '/logs/': RouteRecordInfo<'/logs/', '/logs', Record<never, never>, Record<never, never>>,
    '/models/': RouteRecordInfo<'/models/', '/models', Record<never, never>, Record<never, never>>,
    '/models/subscribers': RouteRecordInfo<'/models/subscribers', '/models/subscribers', Record<never, never>, Record<never, never>>,
    '/models/teams': RouteRecordInfo<'/models/teams', '/models/teams', Record<never, never>, Record<never, never>>,
    '/models/users': RouteRecordInfo<'/models/users', '/models/users', Record<never, never>, Record<never, never>>,
    '/notifications/': RouteRecordInfo<'/notifications/', '/notifications', Record<never, never>, Record<never, never>>,
    '/releases/': RouteRecordInfo<'/releases/', '/releases', Record<never, never>, Record<never, never>>,
    '/requests/': RouteRecordInfo<'/requests/', '/requests', Record<never, never>, Record<never, never>>,
    '/settings/[name]': RouteRecordInfo<'/settings/[name]', '/settings/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/settings/billing': RouteRecordInfo<'/settings/billing', '/settings/billing', Record<never, never>, Record<never, never>>,
    '/settings/mail': RouteRecordInfo<'/settings/mail', '/settings/mail', Record<never, never>, Record<never, never>>,
    '/teams/[id]': RouteRecordInfo<'/teams/[id]', '/teams/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
