/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. \u203C\uFE0F DO NOT MODIFY THIS FILE \u203C\uFE0F
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/signup': RouteRecordInfo<'/auth/signup', '/auth/signup', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/access-tokens/': RouteRecordInfo<'/dashboard/access-tokens/', '/dashboard/access-tokens', Record<never, never>, Record<never, never>>,
    '/dashboard/actions/': RouteRecordInfo<'/dashboard/actions/', '/dashboard/actions', Record<never, never>, Record<never, never>>,
    '/dashboard/buddy/': RouteRecordInfo<'/dashboard/buddy/', '/dashboard/buddy', Record<never, never>, Record<never, never>>,
    '/dashboard/cloud/': RouteRecordInfo<'/dashboard/cloud/', '/dashboard/cloud', Record<never, never>, Record<never, never>>,
    '/dashboard/commands/': RouteRecordInfo<'/dashboard/commands/', '/dashboard/commands', Record<never, never>, Record<never, never>>,
    '/dashboard/commerce/': RouteRecordInfo<'/dashboard/commerce/', '/dashboard/commerce', Record<never, never>, Record<never, never>>,
    '/dashboard/commerce/analytics/': RouteRecordInfo<'/dashboard/commerce/analytics/', '/dashboard/commerce/analytics', Record<never, never>, Record<never, never>>,
    '/dashboard/commerce/categories/': RouteRecordInfo<'/dashboard/commerce/categories/', '/dashboard/commerce/categories', Record<never, never>, Record<never, never>>,
    '/dashboard/commerce/coupons/': RouteRecordInfo<'/dashboard/commerce/coupons/', '/dashboard/commerce/coupons', Record<never, never>, Record<never, never>>,
    '/dashboard/commerce/customers/': RouteRecordInfo<'/dashboard/commerce/customers/', '/dashboard/commerce/customers', Record<never, never>, Record<never, never>>,
    '/dashboard/commerce/delivery/': RouteRecordInfo<'/dashboard/commerce/delivery/', '/dashboard/commerce/delivery', Record<never, never>, Record<never, never>>,
    '/dashboard/commerce/gift-cards/': RouteRecordInfo<'/dashboard/commerce/gift-cards/', '/dashboard/commerce/gift-cards', Record<never, never>, Record<never, never>>,
    '/dashboard/commerce/manufacturers/': RouteRecordInfo<'/dashboard/commerce/manufacturers/', '/dashboard/commerce/manufacturers', Record<never, never>, Record<never, never>>,
    '/dashboard/commerce/orders/': RouteRecordInfo<'/dashboard/commerce/orders/', '/dashboard/commerce/orders', Record<never, never>, Record<never, never>>,
    '/dashboard/commerce/payments/': RouteRecordInfo<'/dashboard/commerce/payments/', '/dashboard/commerce/payments', Record<never, never>, Record<never, never>>,
    '/dashboard/commerce/products/': RouteRecordInfo<'/dashboard/commerce/products/', '/dashboard/commerce/products', Record<never, never>, Record<never, never>>,
    '/dashboard/commerce/products/detail': RouteRecordInfo<'/dashboard/commerce/products/detail', '/dashboard/commerce/products/detail', Record<never, never>, Record<never, never>>,
    '/dashboard/commerce/reviews/': RouteRecordInfo<'/dashboard/commerce/reviews/', '/dashboard/commerce/reviews', Record<never, never>, Record<never, never>>,
    '/dashboard/commerce/taxes/': RouteRecordInfo<'/dashboard/commerce/taxes/', '/dashboard/commerce/taxes', Record<never, never>, Record<never, never>>,
    '/dashboard/commerce/units/': RouteRecordInfo<'/dashboard/commerce/units/', '/dashboard/commerce/units', Record<never, never>, Record<never, never>>,
    '/dashboard/commerce/variants/': RouteRecordInfo<'/dashboard/commerce/variants/', '/dashboard/commerce/variants', Record<never, never>, Record<never, never>>,
    '/dashboard/components/': RouteRecordInfo<'/dashboard/components/', '/dashboard/components', Record<never, never>, Record<never, never>>,
    '/dashboard/dependencies/': RouteRecordInfo<'/dashboard/dependencies/', '/dashboard/dependencies', Record<never, never>, Record<never, never>>,
    '/dashboard/deployments/': RouteRecordInfo<'/dashboard/deployments/', '/dashboard/deployments', Record<never, never>, Record<never, never>>,
    '/dashboard/deployments/[id]': RouteRecordInfo<'/dashboard/deployments/[id]', '/dashboard/deployments/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/dns/': RouteRecordInfo<'/dashboard/dns/', '/dashboard/dns', Record<never, never>, Record<never, never>>,
    '/dashboard/environment/': RouteRecordInfo<'/dashboard/environment/', '/dashboard/environment', Record<never, never>, Record<never, never>>,
    '/dashboard/errors/': RouteRecordInfo<'/dashboard/errors/', '/dashboard/errors', Record<never, never>, Record<never, never>>,
    '/dashboard/functions/': RouteRecordInfo<'/dashboard/functions/', '/dashboard/functions', Record<never, never>, Record<never, never>>,
    '/dashboard/health/': RouteRecordInfo<'/dashboard/health/', '/dashboard/health', Record<never, never>, Record<never, never>>,
    '/dashboard/inbox/': RouteRecordInfo<'/dashboard/inbox/', '/dashboard/inbox', Record<never, never>, Record<never, never>>,
    '/dashboard/inbox/activity': RouteRecordInfo<'/dashboard/inbox/activity', '/dashboard/inbox/activity', Record<never, never>, Record<never, never>>,
    '/dashboard/inbox/settings': RouteRecordInfo<'/dashboard/inbox/settings', '/dashboard/inbox/settings', Record<never, never>, Record<never, never>>,
    '/dashboard/insights/': RouteRecordInfo<'/dashboard/insights/', '/dashboard/insights', Record<never, never>, Record<never, never>>,
    '/dashboard/jobs/': RouteRecordInfo<'/dashboard/jobs/', '/dashboard/jobs', Record<never, never>, Record<never, never>>,
    '/dashboard/jobs/[id]': RouteRecordInfo<'/dashboard/jobs/[id]', '/dashboard/jobs/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/jobs/history': RouteRecordInfo<'/dashboard/jobs/history', '/dashboard/jobs/history', Record<never, never>, Record<never, never>>,
    '/dashboard/logs/': RouteRecordInfo<'/dashboard/logs/', '/dashboard/logs', Record<never, never>, Record<never, never>>,
    '/dashboard/mailboxes/': RouteRecordInfo<'/dashboard/mailboxes/', '/dashboard/mailboxes', Record<never, never>, Record<never, never>>,
    '/dashboard/models/': RouteRecordInfo<'/dashboard/models/', '/dashboard/models', Record<never, never>, Record<never, never>>,
    '/dashboard/models/subscribers': RouteRecordInfo<'/dashboard/models/subscribers', '/dashboard/models/subscribers', Record<never, never>, Record<never, never>>,
    '/dashboard/models/teams': RouteRecordInfo<'/dashboard/models/teams', '/dashboard/models/teams', Record<never, never>, Record<never, never>>,
    '/dashboard/models/users': RouteRecordInfo<'/dashboard/models/users', '/dashboard/models/users', Record<never, never>, Record<never, never>>,
    '/dashboard/notifications/': RouteRecordInfo<'/dashboard/notifications/', '/dashboard/notifications', Record<never, never>, Record<never, never>>,
    '/dashboard/notifications/history': RouteRecordInfo<'/dashboard/notifications/history', '/dashboard/notifications/history', Record<never, never>, Record<never, never>>,
    '/dashboard/packages/': RouteRecordInfo<'/dashboard/packages/', '/dashboard/packages', Record<never, never>, Record<never, never>>,
    '/dashboard/queue/': RouteRecordInfo<'/dashboard/queue/', '/dashboard/queue', Record<never, never>, Record<never, never>>,
    '/dashboard/realtime/': RouteRecordInfo<'/dashboard/realtime/', '/dashboard/realtime', Record<never, never>, Record<never, never>>,
    '/dashboard/releases/': RouteRecordInfo<'/dashboard/releases/', '/dashboard/releases', Record<never, never>, Record<never, never>>,
    '/dashboard/requests/': RouteRecordInfo<'/dashboard/requests/', '/dashboard/requests', Record<never, never>, Record<never, never>>,
    '/dashboard/serverless/': RouteRecordInfo<'/dashboard/serverless/', '/dashboard/serverless', Record<never, never>, Record<never, never>>,
    '/dashboard/servers/': RouteRecordInfo<'/dashboard/servers/', '/dashboard/servers', Record<never, never>, Record<never, never>>,
    '/dashboard/servers/[id]': RouteRecordInfo<'/dashboard/servers/[id]', '/dashboard/servers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/settings/billing': RouteRecordInfo<'/dashboard/settings/billing', '/dashboard/settings/billing', Record<never, never>, Record<never, never>>,
    '/dashboard/settings/mail': RouteRecordInfo<'/dashboard/settings/mail', '/dashboard/settings/mail', Record<never, never>, Record<never, never>>,
    '/dashboard/teams/[id]': RouteRecordInfo<'/dashboard/teams/[id]', '/dashboard/teams/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/hello-world/[name]': RouteRecordInfo<'/hello-world/[name]', '/hello-world/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/system-tray/': RouteRecordInfo<'/system-tray/', '/system-tray', Record<never, never>, Record<never, never>>,
    '/table/': RouteRecordInfo<'/table/', '/table', Record<never, never>, Record<never, never>>,
  }
}
