import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

export interface SchemaObject {
  [key: string]: unknown
  type?: string
  enum?: unknown[]
  properties?: Record<string, SchemaObject>
  required?: string[]
  items?: SchemaObject
  additionalProperties?: boolean | SchemaObject
}

interface OpenApiParameter {
  name: string
  in: string
  required?: boolean
  schema?: SchemaObject
}

interface OpenApiOperation {
  operationId?: string
  parameters?: OpenApiParameter[]
  requestBody?: { required?: boolean, content?: Record<string, { schema?: SchemaObject }> }
  responses?: Record<string, { content?: Record<string, { schema?: SchemaObject }> }>
}

export interface OpenApiDocument {
  paths?: Record<string, Record<string, OpenApiOperation>>
  components?: { schemas?: Record<string, SchemaObject> }
}

const methods = ['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace'] as const

function literal(value: unknown): string {
  return typeof value === 'string' ? JSON.stringify(value) : String(value)
}

export function schemaType(schema?: SchemaObject): string {
  if (!schema) return 'unknown'
  if (schema.enum?.length) return schema.enum.map(literal).join(' | ')
  if (schema.type === 'string') return 'string'
  if (schema.type === 'number' || schema.type === 'integer') return 'number'
  if (schema.type === 'boolean') return 'boolean'
  if (schema.type === 'null') return 'null'
  if (schema.type === 'array') return `Array<${schemaType(schema.items)}>`
  if (schema.type === 'object' || schema.properties || schema.additionalProperties) {
    const required = new Set(schema.required || [])
    const fields = Object.entries(schema.properties || {}).map(([name, value]) =>
      `${JSON.stringify(name)}${required.has(name) ? '' : '?'}: ${schemaType(value)}`,
    )
    if (schema.additionalProperties) {
      const value = schema.additionalProperties === true ? 'unknown' : schemaType(schema.additionalProperties)
      fields.push(`[key: string]: ${value}`)
    }
    return fields.length ? `{ ${fields.join('; ')} }` : 'Record<string, unknown>'
  }
  return 'unknown'
}

function parameterGroups(parameters: OpenApiParameter[] = []): string {
  const groups = ['query', 'header', 'path', 'cookie'].map((location) => {
    const entries = parameters.filter(parameter => parameter.in === location)
    if (!entries.length) return `      ${location}?: never`
    const fields = entries.map(parameter =>
      `${JSON.stringify(parameter.name)}${parameter.required ? '' : '?'}: ${schemaType(parameter.schema)}`,
    )
    return `      ${location}${entries.every(parameter => !parameter.required) ? '?' : ''}: { ${fields.join('; ')} }`
  })
  return `    parameters: {\n${groups.join('\n')}\n    }`
}

function contentTypes(content?: Record<string, { schema?: SchemaObject }>): string {
  if (!content || !Object.keys(content).length) return 'never'
  return `{ ${Object.entries(content).map(([type, value]) => `${JSON.stringify(type)}: ${schemaType(value.schema)}`).join('; ')} }`
}

function renderOperation(operation: OpenApiOperation): string {
  const requestBody = operation.requestBody
    ? `\n    requestBody${operation.requestBody.required ? '' : '?'}: { content: ${contentTypes(operation.requestBody.content)} }`
    : '\n    requestBody?: never'
  const responses = Object.entries(operation.responses || {}).map(([status, response]) =>
    `      ${JSON.stringify(status)}: { content: ${contentTypes(response.content)} }`,
  )
  return `{\n${parameterGroups(operation.parameters)}${requestBody}\n    responses: {\n${responses.join('\n')}\n    }\n  }`
}

export function renderOpenApiTypes(document: OpenApiDocument): string {
  const paths = Object.entries(document.paths || {}).map(([route, item]) => {
    const operations = methods.map((method) => {
      const operation = item[method]
      return operation ? `    ${method}: ${renderOperation(operation)}` : `    ${method}?: never`
    })
    return `  ${JSON.stringify(route)}: {\n${operations.join('\n')}\n  }`
  })
  const schemas = Object.entries(document.components?.schemas || {}).map(([name, schema]) =>
    `    ${JSON.stringify(name)}: ${schemaType(schema)}`,
  )

  return `/**
 * Generated from storage/framework/api/openapi.json by @stacksjs/api.
 * Do not edit this file directly; run bun run docs:artifacts to regenerate it.
 */

export interface paths {
${paths.join('\n')}
}

export interface components {
  schemas: {
${schemas.join('\n')}
  }
}
`
}

if (import.meta.main) {
  const apiRoot = resolve(import.meta.dir, '../../../api')
  const input = resolve(process.argv[2] || resolve(apiRoot, 'openapi.json'))
  const output = resolve(process.argv[3] || resolve(apiRoot, 'api-types.ts'))
  const document = JSON.parse(readFileSync(input, 'utf8')) as OpenApiDocument
  writeFileSync(output, renderOpenApiTypes(document))
  console.log(`Generated ${output}`)
}
