// Generated by Stacks via unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Demo: typeof import('./../components/Demo.vue')['default']
    Counter: typeof import('./../components/Counter.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
  }
}
