/**
 * Cart cookie helper — signs / verifies the `stacks_cart` token.
 *
 * Storefront cart actions used to set the cookie to a raw UUIDv7. The
 * value is hard to *guess* (122 bits of randomness) but trivially
 * *tamperable* — a hostile client can replace it with any other
 * known token to read someone else's cart. Signing the cookie with
 * an HMAC over APP_KEY closes that hole: on read, we reject any
 * value whose signature doesn't match, falling back to "no cart" so
 * the action mints a fresh one.
 *
 * Format: `<token>.<sig>` where `<sig>` is the first 22 base64url
 * characters of `HMAC-SHA256(APP_KEY, token)` (16 bytes → 128 bits,
 * plenty for tamper detection without bloating the cookie).
 *
 * Backwards compat: legacy unsigned tokens still parse (we treat
 * "no `.`" as unsigned) so existing carts don't get orphaned by the
 * upgrade. Once the cookie expires (30 days) every shopper has the
 * signed form.
 */

import { createHmac } from 'node:crypto'

const SIG_BYTES = 16
const SIG_CHARS = 22 // 16 bytes → 22 base64url chars (no padding)

/**
 * Resolve the APP_KEY at call time so test envs that swap `process.env`
 * pick up the new value. Strips the `base64:` prefix Stacks uses for
 * keys generated by `buddy key:generate`. Falls back to a short
 * sentinel so a missing key doesn't crash the request — but the
 * resulting signature is predictable and easy to forge, so the
 * sentinel doubles as a "fix your env" smell in dev.
 */
function getKey(): string {
  const raw = process.env.APP_KEY || ''
  if (raw.startsWith('base64:'))
    return raw.slice('base64:'.length)
  return raw || 'unsigned-fallback-set-APP_KEY'
}

function sign(token: string): string {
  const sig = createHmac('sha256', getKey())
    .update(token)
    .digest('base64url')
    .slice(0, SIG_CHARS)
  return `${token}.${sig}`
}

/**
 * Constant-time string compare so signature verification doesn't
 * leak timing info. Both sides are the same length here (22 chars),
 * so the early-exit length check is safe.
 */
function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false
  let diff = 0
  for (let i = 0; i < a.length; i++)
    diff |= a.charCodeAt(i) ^ b.charCodeAt(i)
  return diff === 0
}

/**
 * Pull a verified cart token out of the request, or null if the
 * cookie is missing/malformed/forged. Legacy unsigned tokens
 * (no `.`) are accepted once and re-signed on the next write.
 */
export function readCartCookie(request: any, cookieName: string): string | null {
  const raw = request.cookies?.get?.(cookieName)
  if (!raw || typeof raw !== 'string') return null

  // Legacy: unsigned UUID. Accept and let the caller re-sign on write.
  // We can't tell apart "valid legacy" from "client-forged garbage",
  // but the action's existing flow already does a DB lookup that
  // returns no row for unknown tokens — same fallback path.
  if (!raw.includes('.')) return raw

  const dot = raw.lastIndexOf('.')
  const token = raw.slice(0, dot)
  const presented = raw.slice(dot + 1)
  if (!token || presented.length !== SIG_CHARS) return null

  const expected = createHmac('sha256', getKey())
    .update(token)
    .digest('base64url')
    .slice(0, SIG_CHARS)

  return timingSafeEqual(expected, presented) ? token : null
}

/**
 * Write a signed cart token to the response cookies. `opts` mirrors
 * the existing `request.cookies.set(name, value, opts)` shape.
 */
export function writeCartCookie(
  request: any,
  cookieName: string,
  token: string,
  opts: Record<string, unknown>,
): void {
  request.cookies?.set?.(cookieName, sign(token), opts)
}

export const cartCookie = { read: readCartCookie, write: writeCartCookie, sign }
export default cartCookie

// Re-export `SIG_BYTES` so tests can assert the byte budget without
// recomputing it. Not used at runtime in the storefront flow.
export const _internals = { SIG_BYTES, SIG_CHARS }
