CREATE TABLE IF NOT EXISTS `gift_cards` (
  `id` bigint PRIMARY KEY auto_increment,
  `code` varchar(255),
  `initial_balance` real,
  `current_balance` real,
  `currency` varchar(255),
  `status` varchar(255),
  `purchaser_id` varchar(255),
  `recipient_email` varchar(255),
  `recipient_name` varchar(255),
  `personal_message` varchar(255),
  `is_digital` tinyint(1),
  `is_reloadable` tinyint(1),
  `is_active` tinyint(1) default 1,
  `expiry_date` datetime,
  `last_used_date` datetime,
  `template_id` varchar(255),
  `customer_id` bigint,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime
);