-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "pledges" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "donor_name" TEXT not null,
  "donor_email" TEXT not null,
  "amount" INTEGER not null,
  "level" TEXT,
  "status" TEXT CHECK ("status" IN ('pending', 'confirmed', 'cancelled')) not null default 'confirmed',
  "auction_id" INTEGER REFERENCES "auctions"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "pledges_auction_id_index" ON "pledges" ("auction_id");
CREATE INDEX IF NOT EXISTS "pledges_status_index" ON "pledges" ("status");
CREATE UNIQUE INDEX IF NOT EXISTS "pledges_uuid_unique" ON "pledges" ("uuid");
