-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "social_accounts" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "provider" TEXT not null,
  "provider_user_id" TEXT not null,
  "provider_email" TEXT,
  "user_id" INTEGER REFERENCES "users"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "social_accounts_provider_provider_user_id_unique" ON "social_accounts" ("provider", "provider_user_id");
CREATE INDEX IF NOT EXISTS "social_accounts_user_id_index" ON "social_accounts" ("user_id");
