-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "sender_domains" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "domain" TEXT not null,
  "status" TEXT CHECK ("status" IN ('pending', 'verified', 'failed', 'disabled')) not null default 'pending',
  "selector" TEXT not null default 'mail',
  "dns_records" TEXT,
  "verified_at" TEXT,
  "last_checked_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "sender_domains_domain_unique" ON "sender_domains" ("domain");
CREATE UNIQUE INDEX IF NOT EXISTS "sender_domains_uuid_unique" ON "sender_domains" ("uuid");
