-- @generated by `buddy migrate:regenerate` — edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_redirects" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "from_path" TEXT not null,
  "to_path" TEXT not null,
  "status_code" INTEGER default 301,
  "source" TEXT CHECK ("source" IN ('slug-change', 'manual')) default 'manual',
  "site_id" INTEGER REFERENCES "sites"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
INSERT INTO "_qb_tmp_redirects" ("id", "from_path", "to_path", "status_code", "source", "site_id", "created_at", "updated_at") SELECT "id", "from_path", "to_path", "status_code", "source", "site_id", "created_at", "updated_at" FROM "redirects";
DROP TABLE "redirects";
ALTER TABLE "_qb_tmp_redirects" RENAME TO "redirects";
CREATE UNIQUE INDEX IF NOT EXISTS "redirects_site_from_unique" ON "redirects" ("site_id", "from_path");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
