-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "email_idempotency" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "idempotency_key" TEXT not null,
  "message_id" TEXT,
  "recipient" TEXT,
  "subject" TEXT,
  "provider" TEXT,
  "success" INTEGER not null default 1,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "email_idempotency_idempotency_key_unique" ON "email_idempotency" ("idempotency_key");
