-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "page_revisions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "revision" INTEGER not null,
  "title" TEXT not null,
  "blocks" TEXT,
  "meta_description" TEXT,
  "note" TEXT,
  "page_id" INTEGER REFERENCES "pages"("id"),
  "author_id" INTEGER REFERENCES "authors"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "page_revisions_page_revision_unique" ON "page_revisions" ("page_id", "revision");
