-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "pages" ADD COLUMN "slug" TEXT;
ALTER TABLE "pages" ADD COLUMN "path" TEXT;
ALTER TABLE "pages" ADD COLUMN "parent_id" INTEGER;
ALTER TABLE "pages" ADD COLUMN "blocks" TEXT;
ALTER TABLE "pages" ADD COLUMN "meta_description" TEXT;
ALTER TABLE "pages" ADD COLUMN "status" TEXT CHECK ("status" IN ('draft', 'published', 'scheduled', 'archived')) default 'draft';
ALTER TABLE "pages" ADD COLUMN "scheduled_at" TEXT;
ALTER TABLE "pages" ADD COLUMN "site_id" INTEGER REFERENCES "sites"("id");
