-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "automations" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "status" TEXT CHECK ("status" IN ('draft', 'active', 'paused', 'archived')) not null default 'draft',
  "version" INTEGER not null default 1,
  "trigger" TEXT not null,
  "graph" TEXT not null,
  "published_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "automations_uuid_unique" ON "automations" ("uuid");
