-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "orders" ADD COLUMN "tracking_token" TEXT;
ALTER TABLE "orders" ADD COLUMN "delivery_latitude" INTEGER;
ALTER TABLE "orders" ADD COLUMN "delivery_longitude" INTEGER;
