-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "sites" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "subdomain" TEXT not null,
  "status" TEXT CHECK ("status" IN ('active', 'suspended', 'archived')) not null default 'active',
  "settings" TEXT,
  "timezone" TEXT default 'America/New_York',
  "team_id" INTEGER REFERENCES "teams"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "sites_subdomain_unique" ON "sites" ("subdomain");
CREATE UNIQUE INDEX IF NOT EXISTS "sites_uuid_unique" ON "sites" ("uuid");
