-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "campaigns" ADD COLUMN "content" TEXT;
ALTER TABLE "campaigns" ADD COLUMN "channel_settings" TEXT;
ALTER TABLE "campaigns" ADD COLUMN "segment_definition" TEXT;
ALTER TABLE "campaigns" ADD COLUMN "reply_to" TEXT;
ALTER TABLE "campaigns" ADD COLUMN "timezone" TEXT not null default 'UTC';
ALTER TABLE "campaigns" ADD COLUMN "recurrence" TEXT;
ALTER TABLE "campaigns" ADD COLUMN "experiment_metric" TEXT CHECK ("experiment_metric" IN ('open_rate', 'click_rate', 'conversion_rate'));
ALTER TABLE "campaigns" ADD COLUMN "team_id" INTEGER REFERENCES "teams"("id");
