-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "referrals" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "referrer_id" INTEGER not null,
  "referred_user_id" INTEGER not null,
  "code" TEXT not null,
  "status" TEXT CHECK ("status" IN ('registered', 'qualified')) not null default 'registered',
  "qualified_at" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE INDEX IF NOT EXISTS "referrals_referrer_status" ON "referrals" ("referrer_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "referrals_referred_user_id_unique" ON "referrals" ("referred_user_id");
