-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "menu_items" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "label" TEXT not null,
  "url" TEXT,
  "target" TEXT CHECK ("target" IN ('_self', '_blank')) default '_self',
  "parent_id" INTEGER,
  "position" INTEGER default 0,
  "visibility" TEXT CHECK ("visibility" IN ('public', 'auth')) default 'public',
  "menu_id" INTEGER REFERENCES "menus"("id"),
  "page_id" INTEGER REFERENCES "pages"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
