-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "storage_item_tasks" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "disk" TEXT not null,
  "path" TEXT not null,
  "kind" TEXT CHECK ("kind" IN ('optimize', 'transcode', 'tag')),
  "state" TEXT CHECK ("state" IN ('queued', 'running', 'done', 'failed')) default 'queued',
  "attempts" INTEGER default 0,
  "error" TEXT,
  "started_at" TEXT,
  "finished_at" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "storage_item_tasks_disk_path_kind_unique" ON "storage_item_tasks" ("disk", "path", "kind");
CREATE UNIQUE INDEX IF NOT EXISTS "storage_item_tasks_uuid_unique" ON "storage_item_tasks" ("uuid");
