-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "consent_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "recipient" TEXT not null,
  "channel" TEXT CHECK ("channel" IN ('email', 'sms', 'push')) not null,
  "action" TEXT CHECK ("action" IN ('requested', 'granted', 'revoked', 'confirmed', 'suppressed')) not null,
  "purpose" TEXT not null,
  "source" TEXT not null,
  "jurisdiction" TEXT,
  "policy_version" TEXT not null,
  "proof" TEXT,
  "ip_address" TEXT,
  "occurred_at" TEXT not null,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "consent_events_lookup" ON "consent_events" ("team_id", "channel", "recipient", "occurred_at");
CREATE UNIQUE INDEX IF NOT EXISTS "consent_events_uuid_unique" ON "consent_events" ("uuid");
