-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE UNIQUE INDEX IF NOT EXISTS "consent_events_idempotency_unique" ON "consent_events" ("team_id", "idempotency_key");
