-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "magic_link_tokens" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "email" TEXT not null,
  "token" TEXT not null,
  "expires_at" TEXT not null,
  "consumed_at" TEXT,
  "redirect_to" TEXT,
  "site_id" INTEGER,
  "user_id" INTEGER REFERENCES "users"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "magic_link_tokens_token_unique" ON "magic_link_tokens" ("token");
CREATE UNIQUE INDEX IF NOT EXISTS "magic_link_tokens_token_unique" ON "magic_link_tokens" ("token");
