-- @generated by `buddy migrate:regenerate` — edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_couriers" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "phone" TEXT not null,
  "vehicle_number" TEXT not null,
  "license" TEXT not null,
  "status" TEXT CHECK ("status" IN ('active', 'on_delivery', 'on_break', 'offline')) default 'active',
  "latitude" INTEGER,
  "longitude" INTEGER,
  "heading" INTEGER,
  "speed" INTEGER default 0,
  "last_ping_at" TEXT,
  "user_id" INTEGER REFERENCES "users"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_couriers" ("id", "name", "phone", "vehicle_number", "license", "status", "user_id", "created_at", "updated_at", "uuid") SELECT "id", "name", "phone", "vehicle_number", "license", "status", "user_id", "created_at", "updated_at", "uuid" FROM "couriers";
DROP TABLE "couriers";
ALTER TABLE "_qb_tmp_couriers" RENAME TO "couriers";
CREATE UNIQUE INDEX IF NOT EXISTS "couriers_uuid_unique" ON "couriers" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
