-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "form_fields" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "label" TEXT not null,
  "type" TEXT CHECK ("type" IN ('text', 'textarea', 'email', 'phone', 'select', 'checkbox', 'radio', 'date', 'file', 'currency', 'section_break')) not null,
  "required" INTEGER default 0,
  "position" INTEGER default 0,
  "width" TEXT CHECK ("width" IN ('full', 'half')) default 'full',
  "options" TEXT,
  "conditions" TEXT,
  "form_id" INTEGER REFERENCES "forms"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "form_fields_form_name_unique" ON "form_fields" ("form_id", "name");
