-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "redirects" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "from_path" TEXT not null,
  "to_path" TEXT not null,
  "status_code" TEXT CHECK ("status_code" IN ('301', '302')) default 301,
  "source" TEXT CHECK ("source" IN ('slug-change', 'manual')) default 'manual',
  "site_id" INTEGER REFERENCES "sites"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "redirects_site_from_unique" ON "redirects" ("site_id", "from_path");
