-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "referral_codes" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "user_id" INTEGER not null REFERENCES "users"("id"),
  "code" TEXT not null,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "referral_codes_user_id_unique" ON "referral_codes" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "referral_codes_code_unique" ON "referral_codes" ("code");
