-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "delivery_stops" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "sequence" INTEGER not null default 1,
  "status" TEXT CHECK ("status" IN ('pending', 'en_route', 'arrived', 'completed', 'failed', 'skipped')) not null default 'pending',
  "address" TEXT not null,
  "latitude" INTEGER,
  "longitude" INTEGER,
  "recipient_name" TEXT,
  "recipient_phone" TEXT,
  "eta_at" TEXT,
  "notified_nearby_at" TEXT,
  "arrived_at" TEXT,
  "completed_at" TEXT,
  "notes" TEXT,
  "delivery_route_id" INTEGER REFERENCES "delivery_routes"("id"),
  "order_id" INTEGER REFERENCES "orders"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "delivery_stops_uuid_unique" ON "delivery_stops" ("uuid");
