-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "auction_items" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "lot_number" INTEGER not null,
  "title" TEXT not null,
  "description" TEXT,
  "image_url" TEXT,
  "category" TEXT,
  "donor_name" TEXT,
  "fair_market_value" INTEGER,
  "starting_bid" INTEGER not null,
  "min_increment" INTEGER,
  "buy_now_price" INTEGER,
  "reserve_price" INTEGER,
  "status" TEXT CHECK ("status" IN ('open', 'closed', 'sold', 'passed')) not null default 'open',
  "closes_at" TEXT,
  "extension_count" INTEGER default 0,
  "auction_id" INTEGER REFERENCES "auctions"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "auction_items_auction_id_index" ON "auction_items" ("auction_id");
CREATE INDEX IF NOT EXISTS "auction_items_status_index" ON "auction_items" ("status");
CREATE UNIQUE INDEX IF NOT EXISTS "auction_items_uuid_unique" ON "auction_items" ("uuid");
