-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "campaign_variants" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "subject" TEXT,
  "content" TEXT not null,
  "allocation" INTEGER not null default 50,
  "sent_count" INTEGER not null default 0,
  "open_count" INTEGER not null default 0,
  "click_count" INTEGER not null default 0,
  "conversion_count" INTEGER not null default 0,
  "is_winner" INTEGER not null default 0,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "campaign_id" INTEGER REFERENCES "campaigns"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "campaign_variants_name_unique" ON "campaign_variants" ("campaign_id", "name");
CREATE UNIQUE INDEX IF NOT EXISTS "campaign_variants_uuid_unique" ON "campaign_variants" ("uuid");
