-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "email_webhook_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "provider" TEXT CHECK ("provider" IN ('mailgun', 'postmark', 'ses', 'sendgrid')) not null,
  "event_id" TEXT not null,
  "processed_at" TEXT not null,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "email_webhook_events_provider_event_unique" ON "email_webhook_events" ("provider", "event_id");
