-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "forms" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "handle" TEXT not null,
  "status" TEXT CHECK ("status" IN ('draft', 'active', 'closed')) default 'draft',
  "settings" TEXT,
  "site_id" INTEGER REFERENCES "sites"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "forms_site_handle_unique" ON "forms" ("site_id", "handle");
CREATE UNIQUE INDEX IF NOT EXISTS "forms_uuid_unique" ON "forms" ("uuid");
