-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "form_submissions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "data" TEXT not null,
  "email" TEXT,
  "name" TEXT,
  "status" TEXT CHECK ("status" IN ('pending_payment', 'complete', 'spam')) default 'complete',
  "amount_cents" INTEGER,
  "payment_intent_id" TEXT,
  "ip" TEXT,
  "submitted_at" TEXT,
  "form_id" INTEGER REFERENCES "forms"("id"),
  "site_id" INTEGER REFERENCES "sites"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "form_submissions_uuid_unique" ON "form_submissions" ("uuid");
