-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "sms_opt_outs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "phone" TEXT not null,
  "reason" TEXT default 'stop-keyword',
  "opted_out_at" TEXT not null,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "sms_opt_outs_phone_unique" ON "sms_opt_outs" ("phone");
CREATE UNIQUE INDEX IF NOT EXISTS "sms_opt_outs_phone_unique" ON "sms_opt_outs" ("phone");
