-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "courier_pings" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "latitude" INTEGER not null,
  "longitude" INTEGER not null,
  "heading" INTEGER,
  "speed" INTEGER default 0,
  "accuracy" INTEGER,
  "recorded_at" TEXT not null,
  "courier_id" INTEGER REFERENCES "couriers"("id"),
  "delivery_route_id" INTEGER REFERENCES "delivery_routes"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "courier_pings_uuid_unique" ON "courier_pings" ("uuid");
