-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "bids" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "bidder_name" TEXT not null,
  "bidder_email" TEXT not null,
  "amount" INTEGER not null,
  "max_amount" INTEGER,
  "status" TEXT CHECK ("status" IN ('leading', 'outbid', 'won', 'lost', 'invalid')) not null default 'leading',
  "placed_at" TEXT not null,
  "auction_id" INTEGER REFERENCES "auctions"("id"),
  "auction_item_id" INTEGER REFERENCES "auction_items"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "bids_auction_item_id_index" ON "bids" ("auction_item_id");
CREATE INDEX IF NOT EXISTS "bids_auction_id_index" ON "bids" ("auction_id");
CREATE INDEX IF NOT EXISTS "bids_bidder_email_index" ON "bids" ("bidder_email");
CREATE INDEX IF NOT EXISTS "bids_status_index" ON "bids" ("status");
CREATE UNIQUE INDEX IF NOT EXISTS "bids_uuid_unique" ON "bids" ("uuid");
