-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "menus" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "handle" TEXT not null,
  "name" TEXT not null,
  "site_id" INTEGER REFERENCES "sites"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "menus_site_handle_unique" ON "menus" ("site_id", "handle");
