-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "automation_runs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "status" TEXT CHECK ("status" IN ('queued', 'running', 'waiting', 'completed', 'failed', 'cancelled')) not null default 'queued',
  "current_node_id" TEXT,
  "version" INTEGER not null default 1,
  "subject_type" TEXT,
  "subject_id" TEXT,
  "context" TEXT not null,
  "idempotency_key" TEXT not null,
  "started_at" TEXT,
  "finished_at" TEXT,
  "error" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "automation_id" INTEGER REFERENCES "automations"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "automation_runs_idempotency_unique" ON "automation_runs" ("idempotency_key");
CREATE UNIQUE INDEX IF NOT EXISTS "automation_runs_uuid_unique" ON "automation_runs" ("uuid");
