-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "gdpr_requests" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "type" TEXT CHECK ("type" IN ('access', 'erasure', 'retention')) not null,
  "subject_id" INTEGER,
  "actor" TEXT,
  "status" TEXT CHECK ("status" IN ('completed', 'failed')) not null default 'completed',
  "summary" TEXT,
  "occurred_at" TEXT not null,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "gdpr_requests_subject_lookup" ON "gdpr_requests" ("subject_id", "type", "occurred_at");
CREATE UNIQUE INDEX IF NOT EXISTS "gdpr_requests_uuid_unique" ON "gdpr_requests" ("uuid");
