-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
ALTER TABLE "product_variants" ADD COLUMN "sku" TEXT;
ALTER TABLE "product_variants" ADD COLUMN "price" INTEGER;
ALTER TABLE "product_variants" ADD COLUMN "compare_at_price" INTEGER;
ALTER TABLE "product_variants" ADD COLUMN "inventory_count" INTEGER;
