-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_storage_item_tasks" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "disk" TEXT not null,
  "path" TEXT not null,
  "kind" TEXT CHECK ("kind" IN ('optimize', 'transcode', 'tag', 'preview')),
  "state" TEXT CHECK ("state" IN ('queued', 'running', 'done', 'failed', 'skipped')) default 'queued',
  "attempts" INTEGER default 0,
  "error" TEXT,
  "started_at" TEXT,
  "finished_at" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_storage_item_tasks" ("id", "disk", "path", "kind", "state", "attempts", "error", "started_at", "finished_at", "created_at", "updated_at", "uuid") SELECT "id", "disk", "path", "kind", "state", "attempts", "error", "started_at", "finished_at", "created_at", "updated_at", "uuid" FROM "storage_item_tasks";
DROP TABLE "storage_item_tasks";
ALTER TABLE "_qb_tmp_storage_item_tasks" RENAME TO "storage_item_tasks";
CREATE UNIQUE INDEX IF NOT EXISTS "storage_item_tasks_disk_path_kind_unique" ON "storage_item_tasks" ("disk", "path", "kind");
CREATE UNIQUE INDEX IF NOT EXISTS "storage_item_tasks_uuid_unique" ON "storage_item_tasks" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
