-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "feedback_tokens" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "token" TEXT not null,
  "label" TEXT not null,
  "revoked_at" TEXT,
  "expires_at" TEXT,
  "last_used_at" TEXT,
  "created_by_user_id" INTEGER,
  "board_id" INTEGER REFERENCES "boards"("id") ON DELETE CASCADE,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "feedback_tokens_token_unique" ON "feedback_tokens" ("token");
CREATE UNIQUE INDEX IF NOT EXISTS "feedback_tokens_uuid_unique" ON "feedback_tokens" ("uuid");
