import type { BunPressOptions } from '@stacksjs/bunpress'

const config: BunPressOptions = {
  verbose: false,
  docsDir: './docs',
  outDir: './dist/docs',

  // Navigation
  nav: [
    {
      text: 'Skills',
      link: '/skills',
    },
    {
      text: 'Changelog',
      link: 'https://github.com/stacksjs/stacks/blob/main/CHANGELOG.md',
    },
    {
      text: 'Resources',
      items: [
        { text: 'Team', link: '/team' },
        { text: 'Sponsors', link: '/sponsors' },
        { text: 'Partners', link: '/partners' },
        { text: 'Postcardware', link: '/postcardware' },
        { text: 'Awesome Stacks', link: 'https://github.com/stacksjs/awesome-stacks' },
        { text: 'Contributing', link: 'https://github.com/stacksjs/stacks/blob/main/.github/CONTRIBUTING.md' },
      ],
    },
  ],

  // Markdown configuration
  markdown: {
    title: 'Stacks Documentation',
    meta: {
      description: 'Rapid application, cloud & library development framework.',
      author: 'Stacks.js',
    },
    syntaxHighlightTheme: 'github-dark',
    toc: {
      enabled: true,
      minDepth: 2,
      maxDepth: 3,
    },
    sidebar: {
      '/': [
        {
          text: 'Prologue',
          collapsed: true,
          items: [
            { text: 'Release Notes', link: '/release-notes' },
            { text: 'Upgrade Guide', link: '/upgrade-guide' },
            { text: 'Contribution Guide', link: '/contribution-guide' },
            { text: 'Sponsors', link: '/sponsors' },
          ],
        },
        {
          text: 'Getting Started',
          collapsed: true,
          items: [
            { text: 'Introduction', link: '/guide/intro' },
            { text: 'Quick Start', link: '/guide/get-started' },
            { text: 'StackBlitz', link: '/guide/stackblitz' },
          ],
        },
        {
          text: 'Basics',
          collapsed: true,
          items: [
            { text: 'Routing', link: '/basics/routing' },
            { text: 'Middleware', link: '/basics/middleware' },
            { text: 'Models', link: '/basics/models' },
            { text: 'Views', link: '/basics/views' },
            { text: 'Actions', link: '/basics/actions' },
            { text: 'Commands', link: '/basics/commands' },
            { text: 'Jobs', link: '/basics/jobs' },
            { text: 'Components', link: '/basics/components' },
            { text: 'Functions', link: '/basics/functions' },
            { text: 'Validation', link: '/packages/validation' },
            { text: 'Error Handling', link: '/basics/error-handling' },
            { text: 'Logging', link: '/basics/logging' },
          ],
        },
        {
          text: 'Digging Deeper',
          collapsed: true,
          items: [
            { text: 'Authentication', link: '/guide/auth' },
            { text: 'Database', link: '/packages/database' },
            { text: 'Scaling the Database', link: '/guide/database-scaling' },
            { text: 'Cache', link: '/packages/cache' },
            { text: 'Events', link: '/packages/events' },
            { text: 'Queue', link: '/packages/queue' },
            { text: 'Notifications', link: '/packages/notifications' },
            { text: 'Payments', link: '/packages/payments' },
            { text: 'Realtime', link: '/packages/realtime' },
            { text: 'Search Engine', link: '/packages/search-engine' },
            { text: 'Storage', link: '/packages/storage' },
          ],
        },
        {
          text: 'Cloud',
          collapsed: true,
          items: [
            { text: 'Deploy', link: '/guide/cloud/deployment' },
            { text: 'Extend Cloud', link: '/guide/cloud/extend' },
          ],
        },
        {
          text: 'CLI (Buddy)',
          collapsed: true,
          items: [
            { text: 'Introduction', link: '/guide/buddy/intro' },
            { text: 'Command Reference', link: '/guide/buddy/commands' },
            { text: 'Add Stacks', link: '/guide/buddy/add' },
            { text: 'Dev', link: '/guide/buddy/dev' },
            { text: 'Build', link: '/guide/buddy/build' },
            { text: 'Deploy', link: '/guide/buddy/deploy' },
            { text: 'Make', link: '/guide/buddy/make' },
            { text: 'Migrate', link: '/guide/buddy/migrate' },
            { text: 'Database Backups', link: '/guide/buddy/db' },
            { text: 'Test', link: '/guide/buddy/test' },
          ],
        },
        {
          text: 'Packages',
          collapsed: true,
          items: [
            { text: 'STX', link: '/packages/stx' },
            { text: 'Actions', link: '/packages/actions' },
            { text: 'AI', link: '/packages/ai' },
            { text: 'Auth', link: '/packages/auth' },
            { text: 'Cache', link: '/packages/cache' },
            { text: 'CLI', link: '/packages/cli' },
            { text: 'Cloud', link: '/packages/cloud' },
            { text: 'Database', link: '/packages/database' },
            { text: 'ORM', link: '/packages/orm' },
            { text: 'Query Builder', link: '/packages/query-builder' },
            { text: 'Router', link: '/packages/router' },
            { text: 'Testing', link: '/packages/testing' },
            { text: 'Validation', link: '/packages/validation' },
          ],
        },
        {
          text: 'Agent Skills',
          collapsed: true,
          items: [
            { text: 'Overview', link: '/skills' },
            { text: 'Using Skills', link: '/skills/using' },
            { text: 'Flows', link: '/skills/flows' },
            { text: 'Writing Your Own', link: '/skills/writing' },
            { text: 'Engineering craft', link: '/skills/craft' },
            { text: 'Data layer', link: '/skills/data' },
            { text: 'Backend and API', link: '/skills/backend' },
            { text: 'Messaging', link: '/skills/messaging' },
            { text: 'Frontend', link: '/skills/frontend' },
            { text: 'Design', link: '/skills/design' },
            { text: 'Domain packages', link: '/skills/domain' },
            { text: 'Toolchain', link: '/skills/toolchain' },
            { text: 'Platform', link: '/skills/platform' },
            { text: 'Utilities', link: '/skills/utilities' },
          ],
        },
        {
          text: 'Testing',
          collapsed: true,
          items: [
            { text: 'Getting Started', link: '/testing/getting-started' },
            { text: 'Unit Tests', link: '/testing/unit-tests' },
            { text: 'Feature Tests', link: '/testing/feature-tests' },
            { text: 'Http Tests', link: '/testing/http-tests' },
            { text: 'Browser Tests', link: '/testing/browser-tests' },
          ],
        },
        {
          text: 'Project',
          collapsed: true,
          items: [
            { text: 'Roadmap', link: '/project/roadmap' },
            { text: 'Contributing', link: '/contribution-guide' },
            { text: 'License', link: '/project/license' },
          ],
        },
      ],
      '/skills': [
        {
          text: 'Agent Skills',
          items: [
            { text: 'Overview', link: '/skills' },
            { text: 'Using Skills', link: '/skills/using' },
            { text: 'Flows', link: '/skills/flows' },
            { text: 'Writing Your Own', link: '/skills/writing' },
          ],
        },
        {
          text: 'Engineering craft',
          collapsed: false,
          items: [
            { text: 'All engineering craft skills', link: '/skills/craft' },
            { text: 'Browse', link: '/skills/craft/browse' },
            { text: 'Codebase design', link: '/skills/craft/codebase-design' },
            { text: 'Domain modeling', link: '/skills/craft/domain-modeling' },
            { text: 'Flow', link: '/skills/craft/flow' },
            { text: 'Grilling', link: '/skills/craft/grilling' },
            { text: 'Guard', link: '/skills/craft/guard' },
            { text: 'Handoff', link: '/skills/craft/handoff' },
            { text: 'Investigate', link: '/skills/craft/investigate' },
            { text: 'New feature', link: '/skills/craft/new-feature' },
            { text: 'Office hours', link: '/skills/craft/office-hours' },
            { text: 'Plan review', link: '/skills/craft/plan-review' },
            { text: 'Prototype', link: '/skills/craft/prototype' },
            { text: 'Retro', link: '/skills/craft/retro' },
            { text: 'Review', link: '/skills/craft/review' },
            { text: 'Security audit', link: '/skills/craft/security-audit' },
            { text: 'TDD', link: '/skills/craft/tdd' },
            { text: 'Wizard', link: '/skills/craft/wizard' },
            { text: 'Writing for agents', link: '/skills/craft/writing-for-agents' },
          ],
        },
        {
          text: 'Data layer',
          collapsed: true,
          items: [
            { text: 'All data layer skills', link: '/skills/data' },
            { text: 'Database', link: '/skills/data/database' },
            { text: 'Faker', link: '/skills/data/faker' },
            { text: 'Migrations', link: '/skills/data/migrations' },
            { text: 'Models', link: '/skills/data/models' },
            { text: 'ORM', link: '/skills/data/orm' },
            { text: 'Query builder', link: '/skills/data/query-builder' },
            { text: 'Search engine', link: '/skills/data/search-engine' },
          ],
        },
        {
          text: 'Backend and API',
          collapsed: true,
          items: [
            { text: 'All backend and api skills', link: '/skills/backend' },
            { text: 'Actions', link: '/skills/backend/actions' },
            { text: 'AI', link: '/skills/backend/ai' },
            { text: 'API', link: '/skills/backend/api' },
            { text: 'Auth', link: '/skills/backend/auth' },
            { text: 'Cache', link: '/skills/backend/cache' },
            { text: 'Cron', link: '/skills/backend/cron' },
            { text: 'Error handling', link: '/skills/backend/error-handling' },
            { text: 'Events', link: '/skills/backend/events' },
            { text: 'Health', link: '/skills/backend/health' },
            { text: 'HTTP', link: '/skills/backend/http' },
            { text: 'Jobs', link: '/skills/backend/jobs' },
            { text: 'Listeners', link: '/skills/backend/listeners' },
            { text: 'Logging', link: '/skills/backend/logging' },
            { text: 'Middleware', link: '/skills/backend/middleware' },
            { text: 'Queue', link: '/skills/backend/queue' },
            { text: 'Realtime', link: '/skills/backend/realtime' },
            { text: 'Router', link: '/skills/backend/router' },
            { text: 'Routes', link: '/skills/backend/routes' },
            { text: 'Scheduler', link: '/skills/backend/scheduler' },
            { text: 'Security', link: '/skills/backend/security' },
            { text: 'Socials', link: '/skills/backend/socials' },
            { text: 'Storage', link: '/skills/backend/storage' },
            { text: 'Validation', link: '/skills/backend/validation' },
          ],
        },
        {
          text: 'Messaging',
          collapsed: true,
          items: [
            { text: 'All messaging skills', link: '/skills/messaging' },
            { text: 'Calendar', link: '/skills/messaging/calendar' },
            { text: 'Chat', link: '/skills/messaging/chat' },
            { text: 'Email', link: '/skills/messaging/email' },
            { text: 'Mail', link: '/skills/messaging/mail' },
            { text: 'Notifications', link: '/skills/messaging/notifications' },
            { text: 'Push', link: '/skills/messaging/push' },
            { text: 'SMS', link: '/skills/messaging/sms' },
          ],
        },
        {
          text: 'Frontend',
          collapsed: true,
          items: [
            { text: 'All frontend skills', link: '/skills/frontend' },
            { text: 'Browser', link: '/skills/frontend/browser' },
            { text: 'Composables', link: '/skills/frontend/composables' },
            { text: 'Crosswind', link: '/skills/frontend/crosswind' },
            { text: 'Desktop', link: '/skills/frontend/desktop' },
            { text: 'Mobile', link: '/skills/frontend/mobile' },
            { text: 'stx', link: '/skills/frontend/stx' },
            { text: 'UI', link: '/skills/frontend/ui' },
          ],
        },
        {
          text: 'Design',
          collapsed: true,
          items: [
            { text: 'All design skills', link: '/skills/design' },
            { text: 'Brand kit', link: '/skills/design/brandkit' },
            { text: 'Design: brutalist', link: '/skills/design/design-brutalist' },
            { text: 'Design: minimalist', link: '/skills/design/design-minimalist' },
            { text: 'Design: full output', link: '/skills/design/design-output' },
            { text: 'Design: soft', link: '/skills/design/design-soft' },
            { text: 'Design taste', link: '/skills/design/design-taste' },
            { text: 'Design taste (Codex)', link: '/skills/design/design-taste-codex' },
            { text: 'Image to code', link: '/skills/design/image-to-code' },
            { text: 'Image generation: mobile', link: '/skills/design/imagegen-mobile' },
            { text: 'Image generation: web', link: '/skills/design/imagegen-web' },
            { text: 'Redesign', link: '/skills/design/redesign' },
            { text: 'Technical diagrams', link: '/skills/design/technical-diagrams' },
          ],
        },
        {
          text: 'Domain packages',
          collapsed: true,
          items: [
            { text: 'All domain packages skills', link: '/skills/domain' },
            { text: 'CMS', link: '/skills/domain/cms' },
            { text: 'Commerce', link: '/skills/domain/commerce' },
            { text: 'Dashboard', link: '/skills/domain/dashboard' },
            { text: 'i18n', link: '/skills/domain/i18n' },
            { text: 'Payments', link: '/skills/domain/payments' },
          ],
        },
        {
          text: 'Toolchain',
          collapsed: true,
          items: [
            { text: 'All toolchain skills', link: '/skills/toolchain' },
            { text: 'Analytics', link: '/skills/toolchain/analytics' },
            { text: 'Buddy', link: '/skills/toolchain/buddy' },
            { text: 'Build', link: '/skills/toolchain/build' },
            { text: 'CLI', link: '/skills/toolchain/cli' },
            { text: 'Cloud', link: '/skills/toolchain/cloud' },
            { text: 'Deploy', link: '/skills/toolchain/deploy' },
            { text: 'Development', link: '/skills/toolchain/development' },
            { text: 'DNS', link: '/skills/toolchain/dns' },
            { text: 'Docs', link: '/skills/toolchain/docs' },
            { text: 'Git', link: '/skills/toolchain/git' },
            { text: 'Lint', link: '/skills/toolchain/lint' },
            { text: 'Plugins', link: '/skills/toolchain/plugins' },
            { text: 'Registry', link: '/skills/toolchain/registry' },
            { text: 'REPL', link: '/skills/toolchain/repl' },
            { text: 'Scaffolding', link: '/skills/toolchain/scaffolding' },
            { text: 'Server', link: '/skills/toolchain/server' },
            { text: 'Shell', link: '/skills/toolchain/shell' },
            { text: 'Testing', link: '/skills/toolchain/testing' },
            { text: 'Tunnel', link: '/skills/toolchain/tunnel' },
            { text: 'WHOIS', link: '/skills/toolchain/whois' },
          ],
        },
        {
          text: 'Platform',
          collapsed: true,
          items: [
            { text: 'All platform skills', link: '/skills/platform' },
            { text: 'Alias', link: '/skills/platform/alias' },
            { text: 'Auto-imports', link: '/skills/platform/auto-imports' },
            { text: 'Config', link: '/skills/platform/config' },
            { text: 'Configuration', link: '/skills/platform/configuration' },
            { text: 'Dependencies', link: '/skills/platform/dependencies' },
            { text: 'Enums', link: '/skills/platform/enums' },
            { text: 'Env', link: '/skills/platform/env' },
            { text: 'Path', link: '/skills/platform/path' },
            { text: 'Types', link: '/skills/platform/types' },
          ],
        },
        {
          text: 'Utilities',
          collapsed: true,
          items: [
            { text: 'All utilities skills', link: '/skills/utilities' },
            { text: 'Arrays', link: '/skills/utilities/arrays' },
            { text: 'Collections', link: '/skills/utilities/collections' },
            { text: 'DateTime', link: '/skills/utilities/datetime' },
            { text: 'Objects', link: '/skills/utilities/objects' },
            { text: 'Slug', link: '/skills/utilities/slug' },
            { text: 'Strings', link: '/skills/utilities/strings' },
            { text: 'Utils', link: '/skills/utilities/utils' },
          ],
        },
      ],
    },
    themeConfig: {
      logo: '/images/logos/logo-transparent.svg',
      footer: {
        message: 'Released under the MIT License.',
        copyright: 'Copyright 2024-present Stacks.js, Inc.',
      },
      socialLinks: [
        { icon: 'twitter', link: 'https://twitter.com/stacksjs' },
        { icon: 'github', link: 'https://github.com/stacksjs/stacks' },
        { icon: 'discord', link: 'https://stacksjs.com/discord' },
      ],
    },
  },

  // SEO Configuration
  sitemap: {
    enabled: true,
    baseUrl: 'https://stacksjs.com/docs',
  },

  robots: {
    enabled: true,
  },
}

export default config
