import type { FeaturesConfig } from '@stacksjs/types'

/**
 * **Stacks Feature Bundles**
 *
 * Each entry below activates a framework feature bundle. A feature is only
 * loaded when its flag is `true` — apps that leave a flag `false` (or omit
 * it) pay nothing for that feature at boot. No eager model load, no
 * route flood, no action-import errors for things they don't ship.
 *
 * Manage this list with the install commands rather than editing directly:
 *
 *   ./buddy dashboard:install     # flips dashboard → true
 *   ./buddy commerce:install      # flips commerce → true
 *   ./buddy commerce:uninstall    # flips commerce → false
 *
 * The install commands also run any feature-specific migrations and copy
 * starter files into your app/.
 *
 * This file (`config/features.ts`) is the canonical reference manifest —
 * Stacks ships every bundle enabled here as a fully-typed scaffold.
 * New apps generated by `./buddy new` will start with only `core` and
 * `auth` active and add the rest via install commands.
 */
export default {
  core: true,
  auth: true,
  marketing: true,
  cms: true,
  commerce: true,
  dashboard: true,
  monitoring: true,
  realtime: true,
  queue: true,
} satisfies FeaturesConfig
