import { alias, defineBuildConfig, withCjsEntries as entries } from '@stacksjs/development'

export default defineBuildConfig({
  alias,
  entries,

  externals: [
    'stacks',
    'stacks/utils',
    'stacks/validation',
    'stacks/path',
    '@stacksjs/ai',
    '@stacksjs/alias',
    '@stacksjs/analytics',
    '@stacksjs/auth',
    '@stacksjs/buddy',
    '@stacksjs/build',
    '@stacksjs/chat',
    '@stacksjs/database',
    '@stacksjs/datetime',
    '@stacksjs/desktop',
    '@stacksjs/email',
    '@stacksjs/events',
    '@stacksjs/health',
    '@stacksjs/notifications',
    '@stacksjs/objects',
    '@stacksjs/orm',
    '@stacksjs/payments',
    '@stacksjs/push',
    '@stacksjs/queue',
    '@stacksjs/realtime',
    '@stacksjs/router',
    '@stacksjs/scheduler',
    '@stacksjs/security',
    '@stacksjs/slug',
    '@stacksjs/sms',
    '@stacksjs/dns',
    '@stacksjs/cloud',
    '@stacksjs/cache',
    '@stacksjs/query-builder',
    '@stacksjs/actions',
    '@stacksjs/server',
    '@stacksjs/signals',
    '@stacksjs/search-engine',
    '@stacksjs/arrays',
    '@stacksjs/strings',
    '@stacksjs/cli',
    '@stacksjs/docs',
    '@stacksjs/repl',
    '@stacksjs/vite',
    '@stacksjs/ui',
    '@stacksjs/lint',
    '@stacksjs/logging',
    '@stacksjs/collections',
    '@stacksjs/faker',
    '@stacksjs/git',
    '@stacksjs/error-handling',
    '@stacksjs/storage',
    '@stacksjs/path',
    '@stacksjs/types',
    '@stacksjs/utils',
    '@stacksjs/validation',
    '@stacksjs/development',
    '@stacksjs/testing',
  ],

  rollup: {
    alias,
  },

  declaration: true,
  clean: true,
})
