/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Demo: typeof import('./components/Demo.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./components/Table.vue')['default']
    TableBody: typeof import('./components/TableBody.vue')['default']
    TableCellActionItems: typeof import('./components/TableCellActionItems.vue')['default']
    TableFilters: typeof import('./components/TableFilters.vue')['default']
    TableHead: typeof import('./components/TableHead.vue')['default']
    TablePagination: typeof import('./components/TablePagination.vue')['default']
    TableRow: typeof import('./components/TableRow.vue')['default']
    TableSearch: typeof import('./components/TableSearch.vue')['default']
    Tooltip: typeof import('./components/Tooltip.vue')['default']
  }
}
