/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Checkout: typeof import('./src/components/Checkout.vue')['default']
    OneTimePayment: typeof import('./src/components/OneTimePayment.vue')['default']
    PaymentSection: typeof import('./src/components/PaymentSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    Subscription: typeof import('./src/components/Subscription.vue')['default']
  }
}
