// The desktop support matrix, and the promise it is allowed to make
// (stacksjs/stacks#2059).
//
// The matrix is the honest record of what Craft output supports, and the thing
// that keeps it honest is `assertDesktopReleaseChannel` refusing a stable
// release of a target that has not earned one. What was missing was any check
// that the two agree with each other - a row could be marked `stable` with
// `signing: 'pending'` and nothing would say so until a release shipped an
// unsigned app.

import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { assertDesktopReleaseChannel, desktopSupport, desktopSupportMatrix } from '../src/support'

const page = join(import.meta.dir, '../../../../../docs/packages/desktop.md')

describe('the support matrix is internally consistent', () => {
  test('a stable row would have to carry the evidence for it', () => {
    // The property, asserted over the matrix rather than over today's four
    // rows: whatever is marked stable must be signed, notarized where that
    // applies, and have install and update evidence. A row that claims stable
    // without them is the failure this guards.
    for (const row of desktopSupportMatrix) {
      if (row.status !== 'stable')
        continue

      expect(row.signing).toBe('enforced')
      expect(row.installLaunchEvidence).toBeTruthy()
      expect(row.updateRollbackEvidence).toBeTruthy()
      if (row.platform === 'darwin')
        expect(row.notarization).toBe('enforced')
    }
  })

  test('every row says what it was tested on and what it is blocked by', () => {
    for (const row of desktopSupportMatrix) {
      expect(row.osVersions.length).toBeGreaterThan(0)
      expect(row.packageFormat.length).toBeGreaterThan(0)
      expect(row.packagingEvidence).toContain('http')

      // An experimental row without a blocking issue is a row nobody is going
      // to move, and reads as a decision rather than a state.
      if (row.status === 'experimental')
        expect(row.blockingIssues.length).toBeGreaterThan(0)
    }
  })

  test('notarization is only not-applicable off macOS', () => {
    for (const row of desktopSupportMatrix) {
      if (row.notarization === 'not-applicable')
        expect(row.platform).not.toBe('darwin')
    }
  })

  test('no two rows describe the same target', () => {
    const targets = desktopSupportMatrix.map(row => `${row.platform}/${row.architecture}`)
    expect(new Set(targets).size).toBe(targets.length)
  })
})

describe('assertDesktopReleaseChannel', () => {
  test('refuses a target that is not in the matrix', () => {
    expect(() => assertDesktopReleaseChannel('experimental', 'sunos', 'sparc')).toThrow(/unsupported/)
  })

  test('refuses a stable release while every target is experimental', () => {
    // The guard that stops an unsigned app being handed to the public. If this
    // ever passes, a row moved to stable and the docs page must have moved with
    // it - which is what the freshness check below is for.
    for (const row of desktopSupportMatrix)
      expect(() => assertDesktopReleaseChannel('stable', row.platform, row.architecture)).toThrow(/cannot be released as stable/)
  })

  test('allows an experimental release of a target in the matrix', () => {
    const first = desktopSupportMatrix[0]!
    expect(assertDesktopReleaseChannel('experimental', first.platform, first.architecture)).toEqual(first)
  })

  test('desktopSupport answers undefined rather than throwing for an unknown target', () => {
    expect(desktopSupport('sunos', 'sparc')).toBeUndefined()
  })
})

describe('the published page agrees with the source', () => {
  const published = readFileSync(page, 'utf8')

  test('names every target', () => {
    // Generated by `buddy docs:desktop-matrix` and checked in CI; this catches
    // the case where the page was deleted or the markers removed, which the
    // generator reports but nothing else would.
    expect(published).toContain('<!-- desktop-support-matrix:begin -->')
    for (const row of desktopSupportMatrix)
      expect(published).toContain(row.packageFormat)
  })

  test('does not present desktop as stable in its prose', () => {
    // #2059's last acceptance criterion, and the one a generated table cannot
    // enforce on its own: the words around it must not say otherwise.
    expect(published).toContain('Every desktop target is experimental')
  })
})
