await Bun.build({
  entrypoints: [
    './src/index.ts',
    // './src/build/component-libs.ts',
    // './src/build/core.ts',
    // './src/build/stacks.ts',
    // './src/dev/index.ts',
    // './src/dev/components.ts',
    // './src/dev/docs.ts',
    // './src/generate/index.ts',
    // './src/generate/component-meta.ts',
    // './src/generate/ide-helpers.ts',
    // './src/generate/lib-entries.ts',
    // './src/generate/types.ts',
    // './src/generate/migrations.ts',
    // './src/generate/vscode-custom-data.ts',
    // './src/generate/vue-compat.ts',
    // './src/helpers/index.ts',
    // './src/helpers/component-meta.ts',
    // './src/helpers/lib-entries.ts',
    // './src/helpers/package-json.ts',
    // './src/helpers/utils.ts',
    // './src/helpers/vscode-custom-data.ts',
    // './src/helpers/vue-compat.ts',
    // './src/lint/index.ts',
    // './src/lint/fix.ts',
    // './src/test/coverage.ts',
    // './src/test/ui.ts',
    // './src/test/unit.ts',
    // './src/upgrade/dependencies.ts',
    // './src/upgrade/framework.ts',
    // './src/upgrade/index.ts',
    // './src/index.ts',
    // './src/add.ts',
    // // './src/build.ts', // we need to be specific here because we have a build folder
    // './src/bump.ts',
    // './src/changelog.ts',
    // './src/clean.ts',
    // './src/commit.ts',
    // './src/copy-types.ts',
    // './src/examples.ts',
    // './src/fresh.ts',
    // './src/key-generate.ts',
    // './src/make.ts',
    // './src/migrate.ts',
    // './src/preinstall.ts',
    // './src/prepublish.ts',
    // './src/release.ts',
    // './src/seed.ts',
    // './src/test.ts', // we need to be specific here because we have a build folder
    // './src/tinker.ts',
    // './src/typecheck.ts',
    // './src/types.ts',
    // './src/upgrade.ts', // we need to be specific here because we have a build folder
  ],
  outdir: './dist',
})
