import { alias, defineBuildConfig } from '@stacksjs/development'

export default defineBuildConfig({
  alias,

  entries: [
    './src/index',
    './src/build/component-libs',
    './src/build/core',
    './src/build/stacks',
    './src/deploy/domains',
    './src/dev/components',
    './src/dev/docs',
    './src/dev/index',
    './src/generate',
    './src/generate/component-meta',
    './src/generate/ide-helpers',
    './src/generate/lib-entries',
    './src/generate/settings',
    './src/generate/vscode-custom-data',
    './src/generate/vue-compat',
    './src/helpers',
    './src/helpers/component-meta',
    './src/helpers/lib-entries',
    './src/helpers/package-json',
    './src/helpers/utils',
    './src/helpers/vscode-custom-data',
    './src/helpers/vue-compat',
    './src/lint',
    './src/lint/fix',
    './src/test/coverage',
    './src/test/feature',
    './src/test/ui',
    './src/test/unit',
    './src/upgrade/dependencies',
    './src/upgrade/framework',
    // './src/upgrade/index',
    './src/upgrade/node',
    './src/upgrade/package-manager',
    './src/add',
    './src/build',
    './src/bump',
    './src/changelog',
    './src/clean',
    './src/commit',
    './src/copy-types',
    './src/deploy',
    './src/examples',
    './src/fresh',
    './src/key-generate',
    './src/make',
    './src/migrate',
    './src/preinstall',
    './src/prepublish',
    './src/release',
    './src/seed',
    // './src/test',
    // './src/tinker',
    // './src/typecheck',
    // './src/types',
    // './src/upgrade',
  ],

  externals: [
    '@stacksjs/cli',
    '@stacksjs/database',
    '@stacksjs/logging',
    '@stacksjs/path',
    '@stacksjs/utils',
    '@stacksjs/storage',
    '@stacksjs/types',
  ],

  rollup: {
    esbuild: {
      target: 'esnext',
    },
  },

  clean: true,
  declaration: true,
})
