import assert from 'node:assert/strict'
import { SQL } from 'bun'
import { mock } from 'bun:test'
import { createHash } from 'node:crypto'
import { basename, dirname } from 'node:path'

const dialect = process.env.DB_CONNECTION
assert(dialect === 'sqlite' || dialect === 'postgres' || dialect === 'mysql')
const configPath = process.env.STACKS_MAGIC_OWNER_CONFIG
assert(configPath && basename(dirname(configPath)).startsWith('stacks-magic-owner-'))
if (dialect === 'sqlite') assert.equal(dirname(process.env.DB_DATABASE_PATH!), dirname(configPath))
else {
  assert.equal(process.env.DB_DATABASE_PATH, ':memory:')
  assert(process.env.DB_DATABASE?.startsWith('stacks_magic_owner_'))
  assert(['127.0.0.1', 'localhost', '[::1]'].includes(process.env.DB_HOST!))
  assert(process.env.DB_PORT && !['5432', '3306'].includes(process.env.DB_PORT))
}
const { config, overridesReady } = await import('@stacksjs/config')
await overridesReady
config.auth.magicLink = { ...config.auth.magicLink, enabled: true }
const { db, initializeDbConfig, ensureDatabaseConfigLoaded, closeDatabaseConnection, sqlDateTime } = await import('@stacksjs/database/runtime')
await ensureDatabaseConfigLoaded()
initializeDbConfig({ app: { env: 'test' }, database: {
  default: dialect, connections: dialect === 'sqlite' ? { sqlite: { database: process.env.DB_DATABASE_PATH } } : {
    [dialect]: { name: process.env.DB_DATABASE, host: process.env.DB_HOST, port: Number(process.env.DB_PORT), username: process.env.DB_USERNAME, password: process.env.DB_PASSWORD },
  }, queryLogging: { enabled: false },
} })
if (process.env.STACKS_MAGIC_OWNER_WORKER === 'change') {
  try { await db.updateTable('users').set({ email: 'replacement@example.invalid' }).where('id', '=', 1).execute() }
  finally { await closeDatabaseConnection() }
  console.log('email change committed')
  process.exit(0)
}
const { configureOrm, releaseOrm } = await import('bun-query-builder')
if (dialect === 'sqlite') configureOrm({ database: process.env.DB_DATABASE_PATH! })
const { ormReady } = await import('@stacksjs/orm')
await ormReady
const realEmail = { ...await import('@stacksjs/email') }
mock.module('@stacksjs/email', () => ({ ...realEmail, mail: { sendOrFail: async () => { throw new Error('fixture must not send email') } } }))
const { Auth } = await import('../../src/authentication')
const { findToken } = await import('../../src/tokens')
const { ensureFrameworkAuthTables } = await import('../helpers/auth-schema')
const { registerPersistentQueryHooks } = await import('@stacksjs/query-builder')
const ConsumeAction = (await import('../../../../defaults/app/Actions/Auth/MagicLinkConsumeAction')).default
const originalLogin = Auth.loginUsingId
const email = (id: number) => `owner-${id}@example.invalid`
const failures: string[] = []
async function seed(raw: string, id = 1, ttl = 120_000) {
  await db.insertInto('magic_link_tokens').values({ email: email(id), user_id: id,
    token: createHash('sha256').update(raw).digest('hex'), expires_at: sqlDateTime(new Date(Date.now() + ttl)),
    redirect_to: '/portal', consumed_at: null, created_at: sqlDateTime(),
  }).execute()
}
async function consume(raw: string): Promise<Response> {
  return ConsumeAction.handle({ get: () => raw } as never) as Promise<Response>
}
async function check(name: string, run: () => Promise<void>) {
  try {
    for (const table of ['magic_link_tokens', 'oauth_refresh_tokens', 'oauth_access_tokens', 'users']) await db.deleteFrom(table).execute()
    for (const id of [1, 2]) await db.insertInto('users').values({ id, name: 'Synthetic', email: email(id) }).execute()
    await run()
    console.log(`PASS ${name}`)
  }
  catch (error) { failures.push(`${name}: ${error}`) }
  finally { Auth.loginUsingId = originalLogin }
}
try {
  await db.unsafe('CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT, email VARCHAR(255), password TEXT, created_at TIMESTAMP, updated_at TIMESTAMP)').execute()
  await ensureFrameworkAuthTables()
  await db.unsafe('CREATE TABLE magic_link_tokens (id INTEGER PRIMARY KEY, email VARCHAR(255), user_id INTEGER, token VARCHAR(64) UNIQUE, expires_at TIMESTAMP, consumed_at TIMESTAMP, redirect_to TEXT, created_at TIMESTAMP, updated_at TIMESTAMP)').execute()
  // Server dialects require an identity column for the link rows.
  if (dialect === 'postgres') await db.unsafe('ALTER TABLE magic_link_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY').execute()
  if (dialect === 'mysql') await db.unsafe('ALTER TABLE magic_link_tokens MODIFY id INTEGER NOT NULL AUTO_INCREMENT').execute()

  await check('removed email rejects login while the other account still signs in', async () => {
    await seed('synthetic-stale-email')
    await seed('synthetic-bystander', 2)
    await db.updateTable('users').set({ email: 'replacement@example.invalid' }).where('id', '=', 1).execute()
    assert.equal((await consume('synthetic-stale-email')).status, 401)
    const response = await consume('synthetic-bystander')
    assert.equal(response.status, 200)
    assert(response.headers.get('Set-Cookie'))
    const result = await response.json() as { access_token: string }
    assert(await findToken(result.access_token))
    await db.updateTable('users').set({ email: email(1) }).where('id', '=', 1).execute()
    assert.equal((await consume('synthetic-stale-email')).status, 401)
  })
  await check('an independent email change before the owner lock rejects the in-flight link', async () => {
    await seed('synthetic-before-claim')
    let changed = false
    const stop = registerPersistentQueryHooks({ onQueryStart(event) {
      if (changed || event.kind !== 'select' || !event.sql.includes('users')) return
      changed = true
      const child = Bun.spawnSync([process.execPath, `--config=${configPath}`, '--no-env-file', import.meta.path], {
        env: { ...process.env, STACKS_MAGIC_OWNER_WORKER: 'change' }, stdout: 'pipe', stderr: 'pipe', timeout: 10_000,
      })
      assert.equal(child.exitCode, 0, new TextDecoder().decode(child.stderr))
      assert(new TextDecoder().decode(child.stdout).includes('email change committed'))
    } })
    try { assert.equal((await consume('synthetic-before-claim')).status, 401); assert(changed) }
    finally { stop() }
  })
  await check('an enclosing rollback restores the grant and removes the issued credentials', async () => {
    await seed('synthetic-outer-rollback')
    let bearer = ''
    await assert.rejects(db.transaction(async () => {
      const response = await consume('synthetic-outer-rollback')
      assert.equal(response.status, 200)
      bearer = (await response.json() as { access_token: string }).access_token
      throw new Error('fixture rollback')
    }), /fixture rollback/)
    assert.equal(await findToken(bearer), null)
    assert.equal((await consume('synthetic-outer-rollback')).status, 200)
  })
  await check('failed issuance rolls back partial credentials without reviving the grant', async () => {
    await seed('synthetic-failed-issue')
    Auth.loginUsingId = async (...args) => { await originalLogin.apply(Auth, args); throw new Error('fixture issuance failed') }
    await assert.rejects(consume('synthetic-failed-issue'), /fixture issuance failed/)
    Auth.loginUsingId = originalLogin
    assert.equal((await db.primary.selectFrom('oauth_access_tokens').select('id').execute()).length, 0)
    assert.equal((await db.primary.selectFrom('oauth_refresh_tokens').select('id').execute()).length, 0)
    assert.equal((await consume('synthetic-failed-issue')).status, 401)
  })
  await check('concurrent login has one winner and missing owners cannot sign in', async () => {
    await seed('synthetic-concurrent-login')
    const responses = await Promise.all(Array.from({ length: 8 }, () => consume('synthetic-concurrent-login')))
    assert.equal(responses.filter(response => response.status === 200).length, 1)
    assert.equal(responses.filter(response => response.status === 401).length, 7)
    await seed('synthetic-deleted-owner', 2)
    await db.deleteFrom('users').where('id', '=', 2).execute()
    assert.equal((await consume('synthetic-deleted-owner')).status, 401)
  })
  if (dialect !== 'sqlite') {
    for (const state of ['used', 'expired'] as const) {
      await check(`${state} links do not wait on the owner's unrelated transaction`, async () => {
        const raw = `synthetic-already-${state}`
        await seed(raw, 1, state === 'expired' ? -10_000 : 120_000)
        if (state === 'used') assert.equal((await consume(raw)).status, 200)
        const observer = new SQL({ adapter: dialect, hostname: process.env.DB_HOST,
          port: Number(process.env.DB_PORT), database: process.env.DB_DATABASE,
          username: process.env.DB_USERNAME, password: process.env.DB_PASSWORD,
          tls: process.env.DB_SSL === 'true' ? 'require' : 'disable' })
        const blocker = await observer.reserve()
        let held = false
        let done = false
        let pending: Promise<Response> | undefined
        try {
          await blocker.unsafe('BEGIN'); held = true
          await blocker.unsafe('SELECT id FROM users WHERE id = 1 FOR UPDATE')
          pending = consume(raw).finally(() => { done = true })
          void pending.catch(() => {})
          const deadline = performance.now() + 5000
          while (!done && performance.now() < deadline) {
            const rows = await observer.unsafe(dialect === 'postgres'
              ? "SELECT COUNT(*) AS count FROM pg_stat_activity WHERE datname = current_database() AND wait_event_type = 'Lock'"
              : "SELECT COUNT(*) AS count FROM performance_schema.data_locks WHERE OBJECT_SCHEMA = DATABASE() AND LOCK_STATUS = 'WAITING'")
            assert.equal(Number(rows[0].count), 0, 'an unusable link must not request its owner lock')
            await Bun.sleep(10)
          }
          assert(done)
          assert.equal((await pending).status, 401)
        }
        finally {
          if (held) await blocker.unsafe('ROLLBACK')
          await pending?.catch(() => {})
          blocker.release()
          await observer.close()
        }
      })
    }
    await check('the owner lock covers actual login issuance, not just link consumption', async () => {
      await seed('synthetic-issuance-race')
      const observer = new SQL({ adapter: dialect, hostname: process.env.DB_HOST,
        port: Number(process.env.DB_PORT), database: process.env.DB_DATABASE,
        username: process.env.DB_USERNAME, password: process.env.DB_PASSWORD,
        tls: process.env.DB_SSL === 'true' ? 'require' : 'disable' })
      let pending: Promise<unknown> | undefined
      let changed = false
      let waited = false
      Auth.loginUsingId = async (...args) => {
        pending = observer.unsafe(`UPDATE users SET email = ${dialect === 'postgres' ? '$1' : '?'} WHERE id = 1`, ['replacement@example.invalid'])
          .then(() => { changed = true })
        void pending.catch(() => {})
        const deadline = performance.now() + 5000
        while (!changed && performance.now() < deadline) {
          const rows = await observer.unsafe(dialect === 'postgres'
            ? "SELECT COUNT(*) AS count FROM pg_stat_activity WHERE datname = current_database() AND wait_event_type = 'Lock'"
            : "SELECT COUNT(*) AS count FROM performance_schema.data_locks WHERE OBJECT_SCHEMA = DATABASE() AND OBJECT_NAME = 'users' AND LOCK_STATUS = 'WAITING'")
          if (Number(rows[0].count) > 0) { waited = true; break }
          await Bun.sleep(10)
        }
        assert(waited && !changed, 'changing ownership must wait until issuance completes')
        return originalLogin.apply(Auth, args)
      }
      try {
        assert.equal((await consume('synthetic-issuance-race')).status, 200)
        await pending
        assert(changed)
      }
      finally { Auth.loginUsingId = originalLogin; await pending?.catch(() => {}); await observer.close() }
    })
  }
  assert.deepEqual(failures, [])
  console.log('magic-link ownership OK')
}
finally { Auth.loginUsingId = originalLogin; mock.module('@stacksjs/email', () => realEmail); await releaseOrm(); await closeDatabaseConnection() }
