/**
 * No large build artifact is tracked in git.
 *
 * `storage/framework/desktop-dmg/Postline-0.1.0.dmg` was 28MB of output from a
 * local July `build:dmg` run, committed and then carried by every clone and CI
 * checkout since. Its sibling `desktop-dist` was gitignored from the start;
 * `desktop-dmg` was simply missed, and nothing was watching (stacksjs/stacks#2056).
 *
 * A size ceiling is the check that would have caught it. Deleting a committed
 * binary does not reclaim the history, so the cheap win is refusing the next
 * one rather than auditing for the last one.
 */
import { describe, expect, it } from 'bun:test'
import { statSync } from 'node:fs'
import { join } from 'node:path'
import { $ } from 'bun'

const root = new URL('../../../../../', import.meta.url).pathname

/** Deliberate exceptions, each with the reason it earns its bytes. */
const allowed = new Set<string>([
  // Published API contract, regenerated by `buddy generate:openapi` and read by
  // consumers who are not building the framework.
  'storage/framework/api/openapi.json',
])

const limitBytes = 5 * 1024 * 1024

describe('tracked files', () => {
  it('carry no build artifact over the size ceiling', async () => {
    const tracked = (await $`git ls-files`.cwd(root).quiet()).text().split('\n').filter(Boolean)

    const oversized = tracked
      .filter(file => !allowed.has(file))
      .map((file) => {
        // A tracked path can be absent from the working tree mid-rebase; that
        // is not this test's business.
        try {
          return { file, bytes: statSync(join(root, file)).size }
        }
        catch {
          return { file, bytes: 0 }
        }
      })
      .filter(({ bytes }) => bytes > limitBytes)
      .map(({ file, bytes }) => `${file} (${(bytes / 1048576).toFixed(1)}MB)`)

    expect(oversized.sort()).toEqual([])
  })
})
