export * as alias from '../../config/alias'
export * as styles from '../../config/styles'
export * as icons from '../../config/icons'
export * as docs from '../../config/docs'
export * as library from '../../config/library'
