// finish this and then ensure it is used to simplify the auto-imports

export * from '../core/actions/src'
export * as actions from '../core/actions/src'
export * from '../core/ai/src'
export * as ai from '../core/ai/src'
export * from '../core/alias/src'
export * from '../core/analytics/src'
export * as analytics from '../core/analytics/src'
export * from '../core/arrays/src'
export * as arrays from '../core/arrays/src'
export * from '../core/auth/src'
export * as auth from '../core/auth/src'
// export * from '../core/buddy/src'
export * as buddy from '../core/buddy/src'
export * from '../core/build/src'
export * as build from '../core/build/src'
export * from '../core/cache/src'
export * as cache from '../core/cache/src'
export * from '../core/chat/src'
export * as chat from '../core/chat/src'
export * from '../core/cli/src'
export * as cli from '../core/cli/src'
export * from '../core/cloud/src'
export * as cloud from '../core/cloud/src'
export * from '../core/collections/src'
export * as collections from '../core/collections/src'
export * from '../core/config/src'
export * as config from '../core/config/src'
export * from '../core/database/src'
export * as database from '../core/database/src'
export * from '../core/datetime/src'
export * as datetime from '../core/datetime/src'
export * from '../core/desktop/src'
export * as desktop from '../core/desktop/src'
export * from '../core/development/src'
export * as development from '../core/development/src'
export * from '../core/dns/src'
export * as dns from '../core/dns/src'
export * from '../core/docs/src'
export * as docs from '../core/docs/src'
export * from '../core/email/src'
export * as email from '../core/email/src'
export * from '../core/error-handling/src'
export * as errorHandling from '../core/error-handling/src'
export * from '../core/events/src'
export * as events from '../core/events/src'
export * from '../core/faker/src'
export * as faker from '../core/faker/src'
export * from '../core/git/src'
export * as git from '../core/git/src'
export * from '../core/health/src'
export * as health from '../core/health/src'
export * from '../core/lint/src'
export * as lint from '../core/lint/src'
export * from '../core/logging/src'
export * as logging from '../core/logging/src'
// export * from '../core/modules/src'
// export * as modules from '../core/modules/src'
export * from '../core/notifications/src'
export * as notifications from '../core/notifications/src'
export * from '../core/objects/src'
export * as objects from '../core/objects/src'
export * from '../core/orm/src'
export * as orm from '../core/orm/src'
// export * from '../core/permissions/src'
// export * as permissions from '../core/permissions/src'
export * from '../core/path/src'
export * as path from '../core/path/src'
export * from '../core/payments/src'
export * as payments from '../core/payments/src'
export * from '../core/push/src'
export * as push from '../core/push/src'
export * from '../core/query-builder/src'
export * as queryBuilder from '../core/query-builder/src'
export * from '../core/queue/src'
export * as queue from '../core/queue/src'
export * from '../core/realtime/src'
export * as realtime from '../core/realtime/src'
export * from '../core/repl/src'
export * as repl from '../core/repl/src'
export * from '../core/router/src'
export * as router from '../core/router/src'
export * from '../core/scheduler/src'
export * as scheduler from '../core/scheduler/src'
export * from '../core/search-engine/src'
export * as searchEngine from '../core/search-engine/src'
export * from '../core/security/src'
export * as security from '../core/security/src'
export * from '../core/server/src'
export * as server from '../core/server/src'
export * from '../core/signals/src'
export * as signals from '../core/signals/src'
export * from '../core/slug/src'
export * as slug from '../core/slug/src'
export * from '../core/sms/src'
export * as sms from '../core/sms/src'
export * from '../core/storage/src'
export * as storage from '../core/storage/src'
export * from '../core/strings/src'
export * as strings from '../core/strings/src'
export * from '../core/testing/src'
export * as testing from '../core/testing/src'
export * from '../core/types/src'
export * as types from '../core/types/src'
export * from '../core/ui/src'
export * as ui from '../core/ui/src'
export * from '../core/utils/src'
export * as utils from '../core/utils/src'
export * from '../core/validation/src'
export * as validation from '../core/validation/src'
// export * from '../core/vite-plugin/src'
