import type { AutoImportsOptions } from 'bun-plugin-auto-imports'
import { existsSync } from 'node:fs'
import { dirname, relative } from 'node:path'
import { plugin } from 'bun'
import { log } from '@stacksjs/logging'
import { path } from '@stacksjs/path'
import { autoImports, generateRuntimeIndex, generateGlobalsScript } from 'bun-plugin-auto-imports'
import { globSync } from '@stacksjs/storage'

interface ExportInfo {
  name: string
  file: string
  isDefault?: boolean
}

/**
 * Feature-module subdirectories under storage/framework/defaults/app/Models
 * that are only included when the project opts into the module via config.
 * Key = subdir name, value = list of config files (any one present = enabled).
 *
 * Add new feature modules here when the framework introduces them. Always-on
 * top-level infra models (User, Notification, Job, FailedJob, Log, Error, …)
 * are NOT listed; they're scanned unconditionally.
 */
const OPTIONAL_MODEL_MODULES: Record<string, string[]> = {
  commerce: ['config/commerce.ts'],
  Content: ['config/cms.ts', 'config/blog.ts'],
  realtime: ['config/realtime.ts'],
}

function configEnabled(configRelPaths: string[]): boolean {
  return configRelPaths.some(rel => existsSync(path.projectPath(rel)))
}

/**
 * Resolve the set of directories to scan for framework-default models.
 * Always returns the Models root itself (for top-level files), then includes
 * each opt-in subdir only if its gating config file exists in the project.
 */
function resolveDefaultModelDirs(): string[] {
  const root = path.storagePath('framework/defaults/app/Models')
  const dirs = [root]
  for (const [subdir, configPaths] of Object.entries(OPTIONAL_MODEL_MODULES)) {
    if (configEnabled(configPaths))
      dirs.push(`${root}/${subdir}`)
  }
  return dirs
}

/**
 * Non-recursive scan of a single directory's direct `.ts` children.
 * Used for both root-level and opt-in subdir scanning so that e.g. disabling
 * commerce correctly excludes `commerce/**` even if the directory exists.
 */
function scanDirTopLevel(dir: string): string[] {
  try {
    return globSync(`${dir}/*.ts`, { ignore: ['**/*.d.ts', '**/index.ts', '**/README*'] })
  }
  catch {
    return []
  }
}

/**
 * Scan defineModel()-based model definition files (export default).
 * These files export their model as the default export.
 *
 * When `recursive` is false, only direct children are scanned — used for the
 * framework defaults root so that opt-in subdirs don't leak in unless the
 * caller explicitly includes them.
 */
function scanDefineModelExports(dir: string, opts: { recursive?: boolean } = {}): ExportInfo[] {
  const { recursive = true } = opts
  let files: string[] = []
  try {
    const pattern = recursive ? `${dir}/**/*.ts` : `${dir}/*.ts`
    files = globSync(pattern, { ignore: ['**/*.d.ts', '**/index.ts', '**/README*'] })
  }
  catch {
    return []
  }

  const exports: ExportInfo[] = []
  const seen = new Set<string>()

  for (const file of files) {
    const basename = file.split('/').pop()?.replace('.ts', '') || ''
    if (basename && !seen.has(basename)) {
      seen.add(basename)
      exports.push({ name: basename, file, isDefault: true })
    }
  }

  return exports
}

// Names that would shadow built-in JavaScript globals if injected into
// globalThis. Skip them at codegen so `instanceof Error` / `instanceof Request`
// / `new Response(...)` keep working inside user actions. Users who need the
// underlying model can still import it directly by file path.
const GLOBAL_SHADOW_BLOCKLIST = new Set([
  'Error',
  'Request',
  'Response',
  'URL',
  'Map',
  'Set',
  'Object',
  'Array',
  'Number',
  'String',
  'Date',
  'Promise',
  'Symbol',
])

/**
 * Generate a runtime index file for defineModel() models.
 * These use `export default defineModel(...)`, so we re-export each default as a named export.
 *
 * Each entry is either a plain string (recursive scan) or `{ dir, recursive: false }`
 * for non-recursive scans. The defaults root passes the non-recursive form so
 * that feature-module subdirs (commerce/, Content/, …) only ship when the
 * project opted into them via config.
 */
type ScanEntry = string | { dir: string, recursive: boolean }

async function generateDefineModelIndex(entries: ScanEntry[], outputPath: string): Promise<void> {
  const lines: string[] = ['// Generated by bun-plugin-auto-imports']
  const seen = new Set<string>()

  for (const entry of entries) {
    const dir = typeof entry === 'string' ? entry : entry.dir
    const recursive = typeof entry === 'string' ? true : entry.recursive
    let files: string[] = []
    try {
      const pattern = recursive ? `${dir}/**/*.ts` : `${dir}/*.ts`
      files = globSync(pattern, { ignore: ['**/*.d.ts', '**/index.ts', '**/README*'] })
    }
    catch {
      continue
    }

    for (const file of files) {
      const basename = file.split('/').pop()?.replace('.ts', '') || ''
      if (!basename || seen.has(basename))
        continue
      seen.add(basename)
      const relativePath = relative(dirname(outputPath), file).replace(/\.ts$/, '')
      if (GLOBAL_SHADOW_BLOCKLIST.has(basename)) {
        lines.push(`// Skipped '${basename}' — would shadow a built-in global. Import directly if needed.`)
        lines.push(`// export { default as ${basename} } from '${relativePath}'`)
        continue
      }
      lines.push(`export { default as ${basename} } from '${relativePath}'`)
    }
  }

  await Bun.write(outputPath, lines.join('\n') + '\n')
}

/**
 * Generate runtime auto-import files for Bun runtime execution.
 * This creates index files that can be imported to get all auto-imports,
 * including defineModel()-based model definitions and resource functions.
 */
export async function generateAutoImportFiles(): Promise<void> {
  const functionsPath = path.resourcesPath('functions')
  const outputDir = path.storagePath('framework/auto-imports')

  // defineModel() model definition directories. User models override framework
  // defaults. The legacy storage/framework/models/ cache has been removed —
  // models are imported directly from their canonical source (user or defaults).
  const userModelsPath = path.userModelsPath()
  const defaultModelDirs = resolveDefaultModelDirs()

  // Job definition directory
  const userJobsPath = path.userJobsPath()

  // Controller definition directories (user controllers take priority)
  const userControllersPath = path.userControllersPath()
  const defaultControllersPath = path.storagePath('framework/defaults/app/Controllers')

  // Ensure output directory exists
  await Bun.write(`${outputDir}/.gitkeep`, '')

  // Generate runtime index for functions
  const functionsIndexPath = `${outputDir}/functions.ts`
  await (generateRuntimeIndex as any)([functionsPath], functionsIndexPath)

  // Generate runtime index for defineModel models (default exports).
  // Defaults root is scanned NON-recursively (so gated subdirs stay opt-in),
  // each enabled module subdir is then added explicitly.
  const modelsIndexPath = `${outputDir}/models.ts`
  const modelScan: ScanEntry[] = [
    userModelsPath,
    { dir: defaultModelDirs[0], recursive: false },
    ...defaultModelDirs.slice(1).map(d => ({ dir: d, recursive: true })),
  ]
  await generateDefineModelIndex(modelScan, modelsIndexPath)

  // Generate runtime index for jobs (default exports, same pattern as models)
  const jobsIndexPath = `${outputDir}/jobs.ts`
  await generateDefineModelIndex([userJobsPath], jobsIndexPath)

  // Generate runtime index for controllers (default exports, user overrides defaults)
  const controllersIndexPath = `${outputDir}/controllers.ts`
  await generateDefineModelIndex([userControllersPath, defaultControllersPath], controllersIndexPath)

  // Generate combined index
  const combinedContent = `// Generated by bun-plugin-auto-imports
export * from './functions'
export * from './models'
export * from './jobs'
export * from './controllers'
`
  await Bun.write(`${outputDir}/index.ts`, combinedContent)

  // Generate globals injection script
  const globalsPath = `${outputDir}/globals.ts`
  await generateGlobalsScript(
    [functionsPath],
    globalsPath,
    `${outputDir}/index.ts`,
  )

  log.debug('Auto-import files generated successfully')
}

/**
 * Initialize auto-imports for both bundler and runtime.
 *
 * Scans defineModel() model files and resource functions, making them
 * available globally without explicit imports.
 */
export function initiateImports(): void {
  const functionsPath = path.resourcesPath('functions')

  // defineModel() model definition directories (user models take priority).
  // Defaults root is non-recursive so opt-in subdirs must be explicitly added.
  const userModelsPath = path.userModelsPath()
  const defaultModelDirs = resolveDefaultModelDirs()
  const [defaultsRoot, ...enabledSubdirs] = defaultModelDirs

  // Job definition directory
  const userJobsPath = path.userJobsPath()

  // Controller definition directories
  const userControllersPath = path.userControllersPath()
  const defaultControllersPath = path.storagePath('framework/defaults/app/Controllers')

  // Scan defineModel() models (default exports from model definitions)
  const defineModelExports = [
    ...scanDefineModelExports(userModelsPath),
    ...scanDefineModelExports(defaultsRoot, { recursive: false }),
    ...enabledSubdirs.flatMap(d => scanDefineModelExports(d)),
  ]

  // Scan job definitions (default exports, same pattern as models)
  const jobExports = scanDefineModelExports(userJobsPath)

  // Deduplicate: user models override framework models override defaults
  const seen = new Set<string>()
  const uniqueDefineModelExports = defineModelExports.filter(exp => {
    if (seen.has(exp.name)) return false
    seen.add(exp.name)
    return true
  })

  // Build imports array for defineModel models (import default as ModelName)
  // Use relative paths from the .d.ts output directory for portability
  const dtsDir = dirname(path.storagePath('framework/types/server-auto-imports.d.ts'))
  const defineModelImports = uniqueDefineModelExports.map(exp => ({
    from: `./${relative(dtsDir, exp.file).replace(/\\/g, '/').replace(/\.ts$/, '')}`,
    name: 'default',
    as: exp.name,
  }))

  // Build imports array for jobs (import default as JobName)
  const jobImports = jobExports.map(exp => ({
    from: `./${relative(dtsDir, exp.file).replace(/\\/g, '/').replace(/\.ts$/, '')}`,
    name: 'default',
    as: exp.name,
  }))

  // Scan controller definitions (default exports, user overrides defaults)
  const controllerExports = [
    ...scanDefineModelExports(userControllersPath),
    ...scanDefineModelExports(defaultControllersPath),
  ]
  const seenControllers = new Set<string>()
  const uniqueControllerExports = controllerExports.filter(exp => {
    if (seenControllers.has(exp.name)) return false
    seenControllers.add(exp.name)
    return true
  })
  const controllerImports = uniqueControllerExports.map(exp => ({
    from: `./${relative(dtsDir, exp.file).replace(/\\/g, '/').replace(/\.ts$/, '')}`,
    name: 'default',
    as: exp.name,
  }))

  const options: AutoImportsOptions = {
    dts: path.storagePath('framework/types/server-auto-imports.d.ts'),
    imports: [...defineModelImports, ...jobImports, ...controllerImports],
    // Use dirs to auto-scan and import all exports from resources/functions
    dirs: [functionsPath],
    eslint: {
      enabled: true,
      filepath: path.storagePath('framework/server-auto-imports.json'),
    },
  }

  // Register bundler plugin (for Bun bundler)
  plugin(autoImports(options))

  // Generate runtime files — fire-and-forget but log errors visibly
  generateAutoImportFiles().catch(err => {
    console.error('[Server] Failed to generate auto-import files:', err)
  })
}

/**
 * Import and inject all auto-imports into globalThis for runtime access.
 * Call this early in your application startup.
 *
 * This makes all models, plus framework primitives used by actions
 * (Action, response, schema, Auth), available globally, matching the
 * "no imports needed" ergonomics of framework default actions.
 */
export async function injectGlobalAutoImports(): Promise<void> {
  const errors: Error[] = []

  // Framework primitives FIRST. User models, jobs, mail classes, etc. read
  // these at module-evaluation time — `schema.number()` in a model's
  // attribute definition, `mail.send(...)` in a job, `class Foo extends
  // Controller` in a controller. If we loaded the auto-imports barrel before
  // these, any user file in that barrel would resolve `schema` / `Controller`
  // / `defineModel` against a still-evaluating namespace and trigger TDZ.
  // Listing primitives here gives every framework user the same "no imports"
  // ergonomics that framework defaults already enjoy. Type-only symbols
  // (UserModel, Attributes, CLI, Events, …) are picked up through the
  // bundler-plugin-generated `framework/types/server-auto-imports.d.ts`
  // so they remain typecheck-visible without polluting runtime.
  const primitiveModules: Array<[string, string[]]> = [
    ['@stacksjs/types', ['Every', 'ExitCode']],
    ['@stacksjs/path', ['path']],
    ['@stacksjs/error-handling', ['HttpError', 'handleError']],
    ['@stacksjs/logging', ['log']],
    ['@stacksjs/config', ['config']],
    ['@stacksjs/validation', ['schema']],
    ['@stacksjs/router', ['response', 'request', 'route', 'Middleware', 'url']],
    ['@stacksjs/storage', ['storage', 'fs']],
    ['@stacksjs/orm', ['defineModel', 'toAttrs']],
    ['@stacksjs/database', ['db', 'sql']],
    ['@stacksjs/email', ['mail', 'template']],
    ['@stacksjs/queue', ['Job']],
    ['@stacksjs/scheduler', ['schedule']],
    ['@stacksjs/actions', ['Action']],
    ['@stacksjs/auth', ['Auth', 'register', 'sessionCheck']],
    ['@stacksjs/events', ['dispatch', 'listen', 'emitter']],
    ['@stacksjs/security', ['makeHash', 'verifyHash']],
    ['@stacksjs/collections', ['collect']],
    ['@stacksjs/cli', ['quotes']],
    ['@stacksjs/notifications', ['notify', 'useNotification', 'useEmail', 'useSMS', 'useChat', 'useDatabase']],
    ['@stacksjs/realtime', ['emit', 'emitToUser', 'emitToUsers', 'createChannel', 'dispatchBroadcast']],
    ['@stacksjs/i18n', ['I18n', 'setLocale', 'getLocale']],
  ]

  // Per-package timeout so a single misbehaving module (e.g. one that opens
  // a Redis socket at module-eval time) doesn't deadlock dev startup.
  // Anything that doesn't load in 4s gets logged and skipped — the package
  // can still be reached via explicit `import` from user code.
  const importWithTimeout = async (pkg: string) => {
    return Promise.race([
      import(pkg),
      new Promise<never>((_, reject) =>
        setTimeout(() => reject(new Error(`auto-import timed out: ${pkg}`)), 4000),
      ),
    ])
  }

  for (const [pkg, names] of primitiveModules) {
    try {
      const mod = await importWithTimeout(pkg)
      for (const name of names) {
        if (mod[name] !== undefined)
          (globalThis as any)[name] = mod[name]
      }
    }
    catch (err) {
      errors.push(err as Error)
    }
  }

  // Now that every framework primitive is fully evaluated and globalThis-ed,
  // it's safe to load the user's auto-import barrel: models can read
  // `schema`, jobs can read `mail`, controllers can extend `Controller`,
  // etc. without hitting a TDZ caused by mid-evaluation namespace access.
  try {
    const autoImportsPath = path.storagePath('framework/auto-imports/index.ts')
    const autoImports = await import(autoImportsPath)
    Object.assign(globalThis, autoImports)
  }
  catch (err) {
    errors.push(err as Error)
  }

  if (errors.length) {
    // Non-fatal — framework parts the project doesn't install can be missing.
    for (const err of errors)
      console.warn('[auto-imports]', err.message)
  }
}
