import type { AutoImportsOptions } from 'bun-plugin-auto-imports'
import { dirname, relative } from 'node:path'
import { plugin } from 'bun'
import { path } from '@stacksjs/path'
import { autoImports, generateRuntimeIndex, generateGlobalsScript } from 'bun-plugin-auto-imports'
import { globSync } from '@stacksjs/storage'

interface ExportInfo {
  name: string
  file: string
  isDefault?: boolean
}

function scanModelExports(dir: string): ExportInfo[] {
  const files = globSync(`${dir}/**/*.ts`, { ignore: ['**/*.d.ts', '**/index.ts'] })
  const exports: ExportInfo[] = []

  for (const file of files) {
    // For model files, use the filename as the model name
    const basename = file.split('/').pop()?.replace('.ts', '') || ''
    if (basename) {
      exports.push({ name: basename, file }) // e.g., Territory from Territory.ts
      exports.push({ name: `${basename}Model`, file }) // e.g., TerritoryModel
    }
  }

  return exports
}

/**
 * Scan defineModel()-based model definition files (export default).
 * These files export their model as the default export.
 */
function scanDefineModelExports(dir: string): ExportInfo[] {
  let files: string[] = []
  try {
    files = globSync(`${dir}/**/*.ts`, { ignore: ['**/*.d.ts', '**/index.ts', '**/README*'] })
  }
  catch {
    // Directory may not exist
    return []
  }

  const exports: ExportInfo[] = []
  const seen = new Set<string>()

  for (const file of files) {
    const basename = file.split('/').pop()?.replace('.ts', '') || ''
    if (basename && !seen.has(basename)) {
      seen.add(basename)
      exports.push({ name: basename, file, isDefault: true })
    }
  }

  return exports
}

/**
 * Generate a runtime index file for defineModel() models.
 * These use `export default defineModel(...)`, so we re-export each default as a named export.
 */
async function generateDefineModelIndex(dirs: string[], outputPath: string): Promise<void> {
  const lines: string[] = ['// Generated by bun-plugin-auto-imports']
  const seen = new Set<string>()

  for (const dir of dirs) {
    let files: string[] = []
    try {
      files = globSync(`${dir}/**/*.ts`, { ignore: ['**/*.d.ts', '**/index.ts', '**/README*'] })
    }
    catch {
      continue
    }

    for (const file of files) {
      const basename = file.split('/').pop()?.replace('.ts', '') || ''
      if (basename && !seen.has(basename)) {
        seen.add(basename)
        // Use relative path from output dir to the model file
        const relativePath = relative(dirname(outputPath), file).replace(/\.ts$/, '')
        lines.push(`export { default as ${basename} } from '${relativePath}'`)
      }
    }
  }

  await Bun.write(outputPath, lines.join('\n') + '\n')
}

/**
 * Generate runtime auto-import files for Bun runtime execution.
 * This creates index files that can be imported to get all auto-imports,
 * including both generated ORM models and defineModel()-based model definitions.
 */
export async function generateAutoImportFiles(): Promise<void> {
  const generatedModelsPath = path.storagePath('framework/orm/src/models')
  const functionsPath = path.resourcesPath('functions')
  const outputDir = path.storagePath('framework/auto-imports')

  // defineModel() model definition directories (user models take priority)
  const userModelsPath = path.userModelsPath()
  const frameworkModelsPath = path.storagePath('framework/models')
  const defaultModelsPath = path.storagePath('framework/defaults/models')

  // Ensure output directory exists
  await Bun.write(`${outputDir}/.gitkeep`, '')

  // Generate runtime index for functions
  const functionsIndexPath = `${outputDir}/functions.ts`
  await (generateRuntimeIndex as any)([functionsPath], functionsIndexPath)

  // Generate runtime index for generated models (named exports)
  const generatedModelsIndexPath = `${outputDir}/generated-models.ts`
  await generateRuntimeIndex([generatedModelsPath], generatedModelsIndexPath)

  // Generate runtime index for defineModel models (default exports)
  const defineModelIndexPath = `${outputDir}/models.ts`
  await generateDefineModelIndex([userModelsPath, frameworkModelsPath, defaultModelsPath], defineModelIndexPath)

  // Generate combined index
  const combinedContent = `// Generated by bun-plugin-auto-imports
export * from './functions'
export * from './generated-models'
export * from './models'
`
  await Bun.write(`${outputDir}/index.ts`, combinedContent)

  // Generate globals injection script
  const globalsPath = `${outputDir}/globals.ts`
  await generateGlobalsScript(
    [functionsPath, generatedModelsPath],
    globalsPath,
    `${outputDir}/index.ts`,
  )

  console.log('Auto-import files generated successfully')
}

/**
 * Initialize auto-imports for both bundler and runtime
 */
export function initiateImports(): void {
  const generatedModelsPath = path.storagePath('framework/orm/src/models')
  const requestsPath = path.storagePath('framework/requests')
  const functionsPath = path.resourcesPath('functions')

  // defineModel() model definition directories (user models take priority)
  const userModelsPath = path.userModelsPath()
  const frameworkModelsPath = path.storagePath('framework/models')
  const defaultModelsPath = path.storagePath('framework/defaults/models')

  // Scan generated models (named exports from BaseOrm classes)
  const generatedModelExports = scanModelExports(generatedModelsPath)
  const requestExports = scanModelExports(requestsPath)

  // Scan defineModel() models (default exports from model definitions)
  const defineModelExports = [
    ...scanDefineModelExports(userModelsPath),
    ...scanDefineModelExports(frameworkModelsPath),
    ...scanDefineModelExports(defaultModelsPath),
  ]

  // Deduplicate: user models override framework models with same name
  const seen = new Set<string>()
  const uniqueDefineModelExports = defineModelExports.filter(exp => {
    if (seen.has(exp.name)) return false
    seen.add(exp.name)
    return true
  })

  // Build imports array for generated models
  const generatedModelImports = generatedModelExports.map(exp => ({
    from: exp.file,
    name: exp.name,
    as: exp.name,
  }))

  // Build imports array for defineModel models (import default as ModelName)
  const defineModelImports = uniqueDefineModelExports.map(exp => ({
    from: exp.file,
    name: 'default',
    as: exp.name,
  }))

  const requestImports = requestExports.map(exp => ({
    from: exp.file,
    name: exp.name,
    as: exp.name,
  }))

  const options: AutoImportsOptions = {
    dts: path.storagePath('framework/types/server-auto-imports.d.ts'),
    imports: [...generatedModelImports, ...defineModelImports, ...requestImports],
    // Use dirs to auto-scan and import all exports from resources/functions
    dirs: [functionsPath],
    eslint: {
      enabled: true, // TODO: not needed in production envs
      filepath: path.storagePath('framework/server-auto-imports.json'),
    },
  }

  // Register bundler plugin (for Bun bundler)
  plugin(autoImports(options))

  // Generate runtime files asynchronously
  generateAutoImportFiles().catch(err => {
    console.warn('Failed to generate auto-import files:', err)
  })
}

/**
 * Import and inject all auto-imports into globalThis for runtime access.
 * Call this early in your application startup.
 *
 * This makes all models (both generated and defineModel-based) available
 * globally, so users can write `Post.where('title', 'test')` without imports.
 */
export async function injectGlobalAutoImports(): Promise<void> {
  try {
    const autoImportsPath = path.storagePath('framework/auto-imports/index.ts')
    const autoImports = await import(autoImportsPath)
    Object.assign(globalThis, autoImports)
  }
  catch (err) {
    console.warn('Failed to inject global auto-imports:', err)
  }
}
