import type { AutoImportsOptions } from 'bun-plugin-auto-imports'
import { existsSync, statSync } from 'node:fs'
import { dirname, relative } from 'node:path'
import { plugin } from 'bun'
import { log } from '@stacksjs/logging'
import { path } from '@stacksjs/path'
import { autoImports, generateRuntimeIndex, generateGlobalsScript } from 'bun-plugin-auto-imports'
import { globSync } from '@stacksjs/storage'
import { primitiveAutoImportEntries, primitiveModules } from './primitive-imports'

interface ExportInfo {
  name: string
  file: string
  isDefault?: boolean
}

/**
 * Feature-module subdirectories under storage/framework/defaults/app/Models
 * that are only included when the project opts into the module via config.
 * Key = subdir name, value = list of config files (any one present = enabled).
 *
 * Add new feature modules here when the framework introduces them. Always-on
 * top-level infra models (User, Notification, Job, FailedJob, Log, Error, …)
 * are NOT listed; they're scanned unconditionally.
 */
const OPTIONAL_MODEL_MODULES: Record<string, string[]> = {
  commerce: ['config/commerce.ts'],
  Content: ['config/cms.ts', 'config/blog.ts'],
  realtime: ['config/realtime.ts'],
}

function configEnabled(configRelPaths: string[]): boolean {
  return configRelPaths.some(rel => existsSync(path.projectPath(rel)))
}

/**
 * Resolve the set of directories to scan for framework-default models.
 * Always returns the Models root itself (for top-level files), then includes
 * each opt-in subdir only if its gating config file exists in the project.
 */
function resolveDefaultModelDirs(): string[] {
  const root = path.storagePath('framework/defaults/app/Models')
  const dirs = [root]
  for (const [subdir, configPaths] of Object.entries(OPTIONAL_MODEL_MODULES)) {
    if (configEnabled(configPaths))
      dirs.push(`${root}/${subdir}`)
  }
  return dirs
}

/**
 * Non-recursive scan of a single directory's direct `.ts` children.
 * Used for both root-level and opt-in subdir scanning so that e.g. disabling
 * commerce correctly excludes `commerce/**` even if the directory exists.
 */
function scanDirTopLevel(dir: string): string[] {
  try {
    return globSync(`${dir}/*.ts`, { ignore: ['**/*.d.ts', '**/index.ts', '**/README*'] })
  }
  catch {
    return []
  }
}

/**
 * Scan defineModel()-based model definition files (export default).
 * These files export their model as the default export.
 *
 * When `recursive` is false, only direct children are scanned — used for the
 * framework defaults root so that opt-in subdirs don't leak in unless the
 * caller explicitly includes them.
 */
function scanDefineModelExports(dir: string, opts: { recursive?: boolean } = {}): ExportInfo[] {
  const { recursive = true } = opts
  let files: string[] = []
  try {
    const pattern = recursive ? `${dir}/**/*.ts` : `${dir}/*.ts`
    files = globSync(pattern, { ignore: ['**/*.d.ts', '**/index.ts', '**/README*'] })
  }
  catch {
    return []
  }

  const exports: ExportInfo[] = []
  const seen = new Set<string>()

  for (const file of files) {
    const basename = file.split('/').pop()?.replace('.ts', '') || ''
    if (basename && !seen.has(basename)) {
      seen.add(basename)
      exports.push({ name: basename, file, isDefault: true })
    }
  }

  return exports
}

// Names that would shadow built-in JavaScript globals if injected into
// globalThis. Skip them at codegen so `instanceof Error` / `instanceof Request`
// / `new Response(...)` keep working inside user actions. Users who need the
// underlying model can still import it directly by file path.
const GLOBAL_SHADOW_BLOCKLIST = new Set([
  'Error',
  'Request',
  'Response',
  'URL',
  'Map',
  'Set',
  'Object',
  'Array',
  'Number',
  'String',
  'Date',
  'Promise',
  'Symbol',
])

/**
 * Generate a runtime index file for defineModel() models.
 * These use `export default defineModel(...)`, so we re-export each default as a named export.
 *
 * Each entry is either a plain string (recursive scan) or `{ dir, recursive: false }`
 * for non-recursive scans. The defaults root passes the non-recursive form so
 * that feature-module subdirs (commerce/, Content/, …) only ship when the
 * project opted into them via config.
 */
type ScanEntry = string | { dir: string, recursive: boolean }

async function generateDefineModelIndex(entries: ScanEntry[], outputPath: string): Promise<void> {
  const lines: string[] = ['// Generated by bun-plugin-auto-imports']
  const seen = new Set<string>()

  for (const entry of entries) {
    const dir = typeof entry === 'string' ? entry : entry.dir
    const recursive = typeof entry === 'string' ? true : entry.recursive
    let files: string[] = []
    try {
      const pattern = recursive ? `${dir}/**/*.ts` : `${dir}/*.ts`
      files = globSync(pattern, { ignore: ['**/*.d.ts', '**/index.ts', '**/README*'] })
    }
    catch {
      continue
    }

    for (const file of files) {
      const basename = file.split('/').pop()?.replace('.ts', '') || ''
      if (!basename || seen.has(basename))
        continue
      seen.add(basename)
      const relativePath = relative(dirname(outputPath), file).replace(/\.ts$/, '')
      if (GLOBAL_SHADOW_BLOCKLIST.has(basename)) {
        lines.push(`// Skipped '${basename}' — would shadow a built-in global. Import directly if needed.`)
        lines.push(`// export { default as ${basename} } from '${relativePath}'`)
        continue
      }
      lines.push(`export { default as ${basename} } from '${relativePath}'`)
    }
  }

  await Bun.write(outputPath, lines.join('\n') + '\n')
}

/**
 * Every directory the auto-import manifest is generated from.
 *
 * Shared by the generator and the staleness check below so the two can
 * never disagree about what the manifest is derived from.
 */
function autoImportSourceDirs(): string[] {
  return [
    path.resourcesPath('functions'),
    path.storagePath('framework/defaults/functions'),
    path.userModelsPath(),
    ...resolveDefaultModelDirs(),
    path.userJobsPath(),
    path.userControllersPath(),
    path.storagePath('framework/defaults/app/Controllers'),
  ]
}

/**
 * Has anything the manifest is built from changed since it was written?
 *
 * The manifest used to be regenerated only when it was missing, so once
 * written it never refreshed. Files moved, were renamed, or were deleted
 * underneath it and the stale entries survived: a project on a
 * months-old manifest carried exports pointing at paths that no longer
 * existed, plus duplicates when a file was moved into a subdirectory of
 * the same name (`functions/commerce/products.ts` becoming
 * `functions/commerce/products/products.ts` produced two `useProducts`
 * exports and the `Cannot export a duplicate name` warning on every boot).
 *
 * Regenerating unconditionally is not the alternative: a watcher on the
 * auto-imports directory sees the write, restarts, writes again, and the
 * dev server loops. Comparing mtimes only writes when something actually
 * moved, and the manifest is the newest file afterwards, so the next boot
 * is a no-op and the loop cannot start.
 */
export function autoImportsAreStale(): boolean {
  const manifest = path.storagePath('framework/auto-imports/functions.ts')
  if (!existsSync(manifest))
    return true

  let manifestTime: number
  try {
    manifestTime = statSync(manifest).mtimeMs
  }
  catch {
    return true
  }

  // Directory mtimes catch adds, renames, and deletes; file mtimes catch
  // edits to a file's exports. A source newer than the manifest means the
  // manifest is describing a tree that has since changed.
  for (const dir of autoImportSourceDirs()) {
    if (!existsSync(dir))
      continue

    try {
      if (statSync(dir).mtimeMs > manifestTime)
        return true

      for (const file of globSync(`${dir}/**/*.ts`, { ignore: ['**/*.d.ts'] })) {
        if (statSync(file).mtimeMs > manifestTime)
          return true
      }
    }
    catch {
      // An unreadable source directory is not a reason to regenerate on
      // every boot; the next successful read will catch any real change.
      continue
    }
  }

  return false
}

/**
 * Generate runtime auto-import files for Bun runtime execution.
 * This creates index files that can be imported to get all auto-imports,
 * including defineModel()-based model definitions and resource functions.
 */
export async function generateAutoImportFiles(): Promise<void> {
  await generateServerAutoImportTypes()

  const userFunctionsPath = path.resourcesPath('functions')
  // Framework-default functions (e.g. storage/framework/defaults/functions/
  // commerce/coupons.ts → useCoupons) are also auto-importable so dashboard
  // pages can call them without an explicit `import` line. User functions
  // come first so a project-level helper of the same name shadows the
  // default.
  const defaultFunctionsPath = path.storagePath('framework/defaults/functions')
  const functionsPath = userFunctionsPath
  const outputDir = path.storagePath('framework/auto-imports')

  // defineModel() model definition directories. User models override framework
  // defaults. The legacy storage/framework/models/ cache has been removed —
  // models are imported directly from their canonical source (user or defaults).
  const userModelsPath = path.userModelsPath()
  const defaultModelDirs = resolveDefaultModelDirs()
  const [defaultsRoot = path.storagePath('framework/defaults/app/Models'), ...enabledSubdirs] = defaultModelDirs

  // Job definition directory
  const userJobsPath = path.userJobsPath()

  // Controller definition directories (user controllers take priority)
  const userControllersPath = path.userControllersPath()
  const defaultControllersPath = path.storagePath('framework/defaults/app/Controllers')

  // Ensure output directory exists
  await Bun.write(`${outputDir}/.gitkeep`, '')

  // Generate runtime index for functions
  const functionsIndexPath = `${outputDir}/functions.ts`
  await (generateRuntimeIndex as any)([userFunctionsPath, defaultFunctionsPath], functionsIndexPath)

  // Generate runtime index for defineModel models (default exports).
  // Defaults root is scanned NON-recursively (so gated subdirs stay opt-in),
  // each enabled module subdir is then added explicitly.
  const modelsIndexPath = `${outputDir}/models.ts`
  const modelScan: ScanEntry[] = [
    userModelsPath,
    { dir: defaultsRoot, recursive: false },
    ...defaultModelDirs.slice(1).map(d => ({ dir: d, recursive: true })),
  ]
  await generateDefineModelIndex(modelScan, modelsIndexPath)

  // Generate runtime index for jobs (default exports, same pattern as models)
  const jobsIndexPath = `${outputDir}/jobs.ts`
  await generateDefineModelIndex([userJobsPath], jobsIndexPath)

  // Generate runtime index for controllers (default exports, user overrides defaults)
  const controllersIndexPath = `${outputDir}/controllers.ts`
  await generateDefineModelIndex([userControllersPath, defaultControllersPath], controllersIndexPath)

  // Generate combined index
  const combinedContent = `// Generated by bun-plugin-auto-imports
export * from './functions'
export * from './models'
export * from './jobs'
export * from './controllers'
`
  await Bun.write(`${outputDir}/index.ts`, combinedContent)

  // Generate globals injection script
  const globalsPath = `${outputDir}/globals.ts`
  await generateGlobalsScript(
    [functionsPath],
    globalsPath,
    `${outputDir}/index.ts`,
  )

  log.debug('Auto-import files generated successfully')
}

/**
 * Initialize auto-imports for both bundler and runtime.
 *
 * Scans defineModel() model files and resource functions, making them
 * available globally without explicit imports.
 */
export function initiateImports(): void {
  const functionsPath = path.resourcesPath('functions')
  // Framework-default helpers (`storage/framework/defaults/functions/...`)
  // are also surfaced globally so dashboard pages can call `useCoupons()`,
  // `useCustomers()`, etc. without an explicit import.
  const defaultFunctionsPath = path.storagePath('framework/defaults/functions')

  // defineModel() model definition directories (user models take priority).
  // Defaults root is non-recursive so opt-in subdirs must be explicitly added.
  const userModelsPath = path.userModelsPath()
  const defaultModelDirs = resolveDefaultModelDirs()
  const [defaultsRoot = path.storagePath('framework/defaults/app/Models'), ...enabledSubdirs] = defaultModelDirs

  // Job definition directory
  const userJobsPath = path.userJobsPath()

  // Controller definition directories
  const userControllersPath = path.userControllersPath()
  const defaultControllersPath = path.storagePath('framework/defaults/app/Controllers')

  // Scan defineModel() models (default exports from model definitions)
  const defineModelExports = [
    ...scanDefineModelExports(userModelsPath),
    ...scanDefineModelExports(defaultsRoot, { recursive: false }),
    ...enabledSubdirs.flatMap(d => scanDefineModelExports(d)),
  ]

  // Scan job definitions (default exports, same pattern as models)
  const jobExports = scanDefineModelExports(userJobsPath)

  // Deduplicate: user models override framework models override defaults
  const seen = new Set<string>()
  const uniqueDefineModelExports = defineModelExports.filter(exp => {
    if (seen.has(exp.name)) return false
    seen.add(exp.name)
    return true
  })

  // Build imports array for defineModel models (import default as ModelName)
  // Use relative paths from the .d.ts output directory for portability
  const dtsDir = dirname(path.storagePath('framework/types/server-auto-imports.d.ts'))
  const defineModelImports = uniqueDefineModelExports.map(exp => ({
    from: `./${relative(dtsDir, exp.file).replace(/\\/g, '/').replace(/\.ts$/, '')}`,
    name: 'default',
    as: exp.name,
  }))

  // Build imports array for jobs (import default as JobName)
  const jobImports = jobExports.map(exp => ({
    from: `./${relative(dtsDir, exp.file).replace(/\\/g, '/').replace(/\.ts$/, '')}`,
    name: 'default',
    as: exp.name,
  }))

  // Scan controller definitions (default exports, user overrides defaults)
  const controllerExports = [
    ...scanDefineModelExports(userControllersPath),
    ...scanDefineModelExports(defaultControllersPath),
  ]
  const seenControllers = new Set<string>()
  const uniqueControllerExports = controllerExports.filter(exp => {
    if (seenControllers.has(exp.name)) return false
    seenControllers.add(exp.name)
    return true
  })
  const controllerImports = uniqueControllerExports.map(exp => ({
    from: `./${relative(dtsDir, exp.file).replace(/\\/g, '/').replace(/\.ts$/, '')}`,
    name: 'default',
    as: exp.name,
  }))

  const options: AutoImportsOptions = {
    dts: path.storagePath('framework/types/server-auto-imports.d.ts'),
    imports: [
      ...primitiveAutoImportEntries(),
      ...defineModelImports,
      ...jobImports,
      ...controllerImports,
    ],
    // Use dirs to auto-scan and import all exports from resources/functions
    // (user) plus storage/framework/defaults/functions (framework defaults).
    dirs: [functionsPath, defaultFunctionsPath],
    eslint: {
      enabled: true,
      filepath: path.storagePath('framework/server-auto-imports.json'),
    },
  }

  // Register bundler plugin (for Bun bundler)
  plugin(autoImports(options))

  // Generate runtime files — fire-and-forget but log errors visibly
  generateAutoImportFiles().catch(err => {
    console.error('[Server] Failed to generate auto-import files:', err)
  })
}

/** Generate TypeScript declarations for the globals injected by the server. */
export async function generateServerAutoImportTypes(): Promise<void> {
  const userModelsPath = path.userModelsPath()
  const defaultModelDirs = resolveDefaultModelDirs()
  const [defaultsRoot = path.storagePath('framework/defaults/app/Models'), ...enabledSubdirs] = defaultModelDirs
  const modelExports = [
    ...scanDefineModelExports(userModelsPath),
    ...scanDefineModelExports(defaultsRoot, { recursive: false }),
    ...enabledSubdirs.flatMap(dir => scanDefineModelExports(dir)),
  ]
  const jobExports = scanDefineModelExports(path.userJobsPath())
  const controllerExports = [
    ...scanDefineModelExports(path.userControllersPath()),
    ...scanDefineModelExports(path.storagePath('framework/defaults/app/Controllers')),
  ]

  const seen = new Set<string>()
  const valueExports = [...modelExports, ...jobExports, ...controllerExports]
    .filter(exp => !GLOBAL_SHADOW_BLOCKLIST.has(exp.name))
    .filter((exp) => {
      if (seen.has(exp.name)) return false
      seen.add(exp.name)
      return true
    })

  const outputPath = path.storagePath('framework/types/server-auto-imports.d.ts')
  const outputDir = dirname(outputPath)
  const declaredValues = new Set(valueExports.map(exp => exp.name))
  const lines = [
    '// Generated by Stacks server auto-imports',
    '// This file is regenerated automatically when the API starts.',
    'export {}',
    'declare global {',
  ]

  for (const { from, name, as } of primitiveAutoImportEntries()) {
    if (!declaredValues.has(as))
      lines.push(`  const ${as}: typeof import('${from}')['${name}']`)
  }

  for (const exp of valueExports) {
    const importPath = relative(outputDir, exp.file).replace(/\\/g, '/').replace(/\.ts$/, '')
    const relativePath = importPath.startsWith('.') ? importPath : `./${importPath}`
    lines.push(`  const ${exp.name}: typeof import('${relativePath}')['default']`)
  }

  lines.push('}', '')
  await Bun.write(outputPath, lines.join('\n'))
}

/**
 * Import and inject all auto-imports into globalThis for runtime access.
 * Call this early in your application startup.
 *
 * This makes all models, plus framework primitives used by actions
 * (Action, response, schema, Auth), available globally, matching the
 * "no imports needed" ergonomics of framework default actions.
 */
export async function injectGlobalAutoImports(): Promise<void> {
  // Idempotency guard. Bun's hot-reload re-evaluates this module on every
  // file change; without this guard each cycle would re-`Object.assign` the
  // primitive bundle onto globalThis, which is fine for replacements but
  // causes the auto-import barrel re-eval to leak duplicates of every
  // user model/job/controller into the global namespace and slowly bloat
  // the dev process. Once is enough.
  if ((globalThis as { __stacksAutoImportsInjected?: boolean }).__stacksAutoImportsInjected) return
  ;(globalThis as { __stacksAutoImportsInjected?: boolean }).__stacksAutoImportsInjected = true

  const errors: Error[] = []

  // Framework primitives FIRST. User models, jobs, mail classes, etc. read
  // these at module-evaluation time — `schema.number()` in a model's
  // attribute definition, `mail.send(...)` in a job, `class Foo extends
  // Controller` in a controller. If we loaded the auto-imports barrel before
  // these, any user file in that barrel would resolve `schema` / `Controller`
  // / `defineModel` against a still-evaluating namespace and trigger TDZ.
  // Listing primitives here gives every framework user the same "no imports"
  // ergonomics that framework defaults already enjoy. Type-only symbols
  // (UserModel, Attributes, CLI, Events, …) remain available through the
  // framework's static type declarations without polluting runtime.
  // Per-package timeout so a single misbehaving module (e.g. one that opens
  // a Redis socket at module-eval time) doesn't deadlock dev startup.
  // Anything that doesn't load in 4s gets logged and skipped — the package
  // can still be reached via explicit `import` from user code.
  const importWithTimeout = async (pkg: string) => {
    return Promise.race([
      import(pkg),
      new Promise<never>((_, reject) =>
        setTimeout(() => reject(new Error(`auto-import timed out: ${pkg}`)), 4000),
      ),
    ])
  }

  // Import every primitive concurrently. They're independent packages that
  // export distinct global names, so the order they resolve in doesn't matter —
  // only that all of them land on globalThis before the user barrel loads (the
  // await below). Parallelizing overlaps their module I/O instead of paying for
  // each import end-to-end in sequence.
  await Promise.all(primitiveModules.map(async ([pkg, names]) => {
    try {
      const mod = await importWithTimeout(pkg)
      for (const name of names) {
        if (mod[name] !== undefined)
          (globalThis as any)[name] = mod[name]
      }
    }
    catch (err) {
      errors.push(err as Error)
    }
  }))

  // Project `locales/*.yml` — used by STX `{{ t('key') }}` and actions.
  try {
    const { ensureLocalesLoaded } = await import('@stacksjs/i18n')
    await ensureLocalesLoaded()
  }
  catch (err) {
    errors.push(err as Error)
  }

  // Now that every framework primitive is fully evaluated and globalThis-ed,
  // it's safe to load the user's auto-import barrel: models can read
  // `schema`, jobs can read `mail`, controllers can extend `Controller`,
  // etc. without hitting a TDZ caused by mid-evaluation namespace access.
  // Each barrel is loaded separately, not through the combined `index.ts`.
  //
  // `index.ts` re-exports all four with `export *`, so a single duplicate name
  // in any one of them makes the whole module fail to link and NOTHING reaches
  // globalThis — every model, job and controller in the project disappears at
  // once. That is how an app ended up with `HtrSample is not defined` in its
  // stx views while `functions.ts` merely had `useProducts` exported twice: the
  // generator emitted a name collision between `commerce/products` and
  // `commerce/products/products`, and the only trace was a one-line warning
  // that read like a lint nit rather than "no models exist".
  //
  // Split, a broken barrel costs only its own names. The order matches
  // `index.ts` so shadowing behaviour is unchanged.
  const barrels = ['functions', 'models', 'jobs', 'controllers'] as const
  const injected: string[] = []

  for (const barrel of barrels) {
    const barrelPath = path.storagePath(`framework/auto-imports/${barrel}.ts`)

    if (!existsSync(barrelPath))
      continue

    try {
      const mod = await import(barrelPath)
      Object.assign(globalThis, mod)
      injected.push(barrel)
    }
    catch (err) {
      // Named loudly. The consequence of losing a barrel is not obvious from
      // the linker's message: "Cannot export a duplicate name" says nothing
      // about every model in the app becoming undefined in templates.
      log.warn(
        `[auto-imports] ${barrel}.ts failed to load, so nothing it exports is available. `
        + `Views and actions referencing them will throw "is not defined". Cause: ${(err as Error).message}`,
      )
    }
  }

  // A project with models on disk and none injected is broken in a way that is
  // invisible until a template renders empty, so it is reported up front.
  if (!injected.includes('models') && existsSync(path.storagePath('framework/auto-imports/models.ts')))
    log.warn('[auto-imports] No models were injected. Every model reference in stx views and actions will be undefined.')

  // Listeners last, and after the barrel deliberately: a listener reads models
  // and jobs at module-evaluation time exactly as an action does, so it has to
  // be imported once those are on globalThis.
  //
  // Here rather than in the router because listeners are not an HTTP concern -
  // `buddy seed`, a scheduled job and a console command all dispatch events,
  // and every one of those paths comes through this function. Before this call
  // existed, nothing registered listeners anywhere: `app/Events.ts` was read
  // only by a test, `discoverListeners` was exported and never called, and
  // `dispatch` succeeded into an emitter with no handlers on it.
  try {
    const { registerAppListeners } = await import('@stacksjs/events')
    await registerAppListeners()
  }
  catch (err) {
    errors.push(err as Error)
  }

  if (errors.length) {
    // Non-fatal — framework parts the project doesn't install can be missing.
    for (const err of errors)
      console.warn('[auto-imports]', err.message)
  }
}
