import { fs } from '@stacksjs/storage'
import { filesize } from 'filesize'
import { markdownTable } from 'markdown-table'
import { version } from '../package.json'
import { getExportsSize } from '../src/export-size'

interface PackageEntry {
  name: string
  display: string
  description?: string
  external?: string[]
}

export const packages: PackageEntry[] = [
  {
    name: 'shared',
    display: 'Shared utilities',
  },
  {
    name: 'core',
    display: 'Core',
    description: 'Collection of essential Stacks utilities',
  },
]

async function run() {
  let md = '# Export size\n\n'
  const mdJSON: { [name: string]: string } = {}
  md += 'generated by [export-size](https://github.com/antfu/export-size)<br>\n'
  md += `version: ${version}<br>\n`
  md += `date: ${new Date().toISOString()}\n\n`

  md += '> Please note this is bundle size for each individual APIs (excluding Vue). '
  md += 'Since we have a lot shared utilities underneath each function, importing two '
  md += 'different functions does NOT necessarily mean the bundle size will be the sum of them (usually smaller). '
  md += 'Depends on the bundler and minifier you use, the final result might vary, this list is for reference only.'
  md += '\n\n'

  for (const pkg of packages) {
    const { exports, packageJSON } = await (getExportsSize as any)({
      pkg: `./packages/${pkg.name}/dist`,
      output: false,
      bundler: 'rollup',
      external: ['vue-demi', ...(pkg.external || [])],
    } as any)

    md += `<kbd>${(packageJSON as any).name}</kbd>\n\n`

    md += markdownTable([
      ['Function', 'min+gzipped'],
      ...(exports as any[]).map((i: any) => {
        mdJSON[i.name] = filesize(i.minzipped) as string
        return [`\`${i.name}\``, filesize(i.minzipped) as string]
      }),
    ])

    md += '\n\n'
  }

  await (fs as any).writeFile('../export-size.md', md, 'utf-8')
  await (fs as any).writeJSON('../export-size.json', mdJSON, { spaces: 2 })
}

await run()
