import { build } from './commands/build'
import { clean } from './commands/clean'
import { commit } from './commands/commit'
import { create } from './commands/create'
import { dev } from './commands/dev'
import { example } from './commands/example'
import { fresh } from './commands/fresh'
import { generate } from './commands/generate'
import { lint } from './commands/lint'
import { key } from './commands/key'
import { make } from './commands/make'
import { prepublish } from './commands/prepublish'
import { preinstall } from './commands/preinstall'
import { release } from './commands/release'
import { setup } from './commands/setup'
import { test } from './commands/test'
import { types } from './commands/types'
import { update } from './commands/update'

export { dev, build, fresh, make, example, test, create, update, generate, key, types, preinstall, prepublish, setup, clean, commit, release, lint }
