import { assertFrameworkRepo } from './framework-repo'
import type { BuddyCommandInventoryEntry, BuddyCommandInventoryOption } from '../list'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

interface BuddyInventory {
  commands: BuddyCommandInventoryEntry[]
  total: number
}

const root = resolve(import.meta.dir, '../../../../../../..')
const outputPath = resolve(root, 'docs/guide/buddy/commands.md')
const cliPath = resolve(root, 'storage/framework/core/buddy/src/cli.ts')

function markdown(value: unknown): string {
  return String(value).replaceAll('\\', '\\\\').replaceAll('|', '\\|').replaceAll('\n', '<br>')
}

function code(value: unknown): string {
  return `\`${String(value).replaceAll('`', '\\`')}\``
}

/**
 * Strip the absolute path of whoever generated the file.
 *
 * A default that comes from `process.cwd()` renders as the generating
 * machine's checkout - a home directory on a laptop, `/home/runner/work/...`
 * on CI - so the committed reference could never match what CI generated, and
 * the check failed for everyone with a message that only said "stale". It
 * also meant a contributor's directory layout was published in the docs.
 */
function stablePath(value: unknown): unknown {
  if (typeof value !== 'string' || !value.includes(root))
    return value

  return value.replaceAll(root, '<project root>')
}


function optionFlags(option: BuddyCommandInventoryOption): string {
  return option.flags.map(flag => code(`${flag.length === 1 ? '-' : '--'}${flag}`)).join(', ')
}

function optionKind(option: BuddyCommandInventoryOption): string {
  const traits = [
    option.boolean ? 'boolean' : 'value',
    option.required ? 'required' : 'optional',
    ...(option.negated ? ['negated'] : []),
  ]
  return traits.join(', ')
}

function argumentSyntax(argument: BuddyCommandInventoryEntry['arguments'][number]): string {
  const value = `${argument.name}${argument.variadic ? '...' : ''}`
  return code(argument.required ? `<${value}>` : `[${value}]`)
}

function commandSection(command: BuddyCommandInventoryEntry): string {
  const lines = [
    `### ${code(command.name)}`,
    '',
    command.description || 'No description provided.',
    '',
    `- Usage: ${code(command.usage)}`,
    `- Namespace: ${command.namespace ? code(command.namespace) : 'none'}`,
    `- Aliases: ${command.aliases.length ? command.aliases.map(code).join(', ') : 'none'}`,
    `- Arguments: ${command.arguments.length ? command.arguments.map(argumentSyntax).join(', ') : 'none'}`,
  ]

  if (command.options.length) {
    lines.push(
      '',
      '| Option | Description | Contract | Default |',
      '| --- | --- | --- | --- |',
      ...command.options.map(option => `| ${optionFlags(option)} | ${markdown(option.description || '-')} | ${optionKind(option)} | ${option.default === undefined ? '-' : code(JSON.stringify(stablePath(option.default)))} |`),
    )
  }

  if (command.examples.length) {
    lines.push('', 'Examples:', '', '```bash', ...command.examples, '```')
  }

  return lines.join('\n')
}

export function renderBuddyCommandReference(inventory: BuddyInventory): string {
  const commands = [...inventory.commands].sort((a, b) => a.name.localeCompare(b.name))
  if (inventory.total !== commands.length)
    throw new Error(`Buddy inventory total ${inventory.total} does not match ${commands.length} commands`)
  if (new Set(commands.map(command => command.name)).size !== commands.length)
    throw new Error('Buddy inventory contains duplicate canonical command names')

  const groups = new Map<string, BuddyCommandInventoryEntry[]>()
  for (const command of commands) {
    const group = command.namespace || (command.name.includes(':') ? command.name.split(':')[0]! : 'general')
    const entries = groups.get(group) || []
    entries.push(command)
    groups.set(group, entries)
  }

  const groupSummary = [...groups.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([group, entries]) => `| ${code(group)} | ${entries.length} |`)

  const document = [
    '---',
    'title: Buddy Command Reference',
    'description: Generated reference for every Buddy command, argument, option, alias, default, and example.',
    '---',
    '<!-- Generated by storage/framework/core/buddy/src/commands/docs/buddy-commands.ts. Do not edit by hand. -->',
    '',
    '# Buddy Command Reference',
    '',
    `This reference is generated from Buddy's runtime command registry and currently contains **${commands.length} commands**. Run \`bun run docs:buddy\` after changing the registry; CI rejects stale output.`,
    '',
    '## Command groups',
    '',
    '| Group | Commands |',
    '| --- | ---: |',
    ...groupSummary,
    '',
    '## Commands',
    '',
    ...commands.flatMap(command => [commandSection(command), '']),
  ].join('\n')

  return `${document.split('\n').map(line => line.trimEnd()).join('\n').trimEnd()}\n`
}

export function loadBuddyInventory(): BuddyInventory {
  const result = Bun.spawnSync([process.execPath, cliPath, 'list', '--json'], {
    cwd: root,
    env: { ...process.env, NO_COLOR: '1' },
    stdout: 'pipe',
    stderr: 'pipe',
  })
  const stdout = result.stdout.toString()
  const stderr = result.stderr.toString().trim()
  if (result.exitCode !== 0)
    throw new Error(`Buddy command inventory failed (${result.exitCode}): ${stderr}`)

  // A first run in a fresh checkout prints startup notices — env warnings, an
  // APP_KEY being generated — and some of them land on stdout, ahead of the
  // payload. Reading the whole stream as JSON turned that into `JSON Parse
  // error: Unexpected EOF`, which named neither the command that misbehaved
  // nor what it actually printed. Take the JSON document out of the stream,
  // and when there isn't one, say what we got instead.
  const start = stdout.indexOf('{')
  const end = stdout.lastIndexOf('}')
  if (start === -1 || end <= start) {
    const noise = (stdout.trim() || stderr || '(no output)').split('\n').slice(0, 10).join('\n')
    throw new Error(`Buddy command inventory printed no JSON payload. \`buddy list --json\` said:\n${noise}`)
  }

  let inventory: BuddyInventory
  try {
    inventory = JSON.parse(stdout.slice(start, end + 1)) as BuddyInventory
  }
  catch (error) {
    throw new Error(`Buddy command inventory returned unparseable JSON: ${(error as Error).message}`)
  }
  if (!Array.isArray(inventory.commands) || !Number.isInteger(inventory.total))
    throw new Error('Buddy command inventory returned an invalid payload')
  return inventory
}

export async function run(): Promise<void> {
  // This tool writes into the framework repository. See framework-repo.ts:
  // run from an application it would edit another project's files.
  assertFrameworkRepo(root, 'docs:buddy')

  const mode = process.argv.includes('--write') ? 'write' : process.argv.includes('--check') ? 'check' : null
  if (!mode) {
    console.error('usage: bun storage/framework/core/buddy/src/commands/docs/buddy-commands.ts --write | --check')
    process.exit(2)
  }

  const expected = renderBuddyCommandReference(loadBuddyInventory())
  if (mode === 'write') {
    mkdirSync(dirname(outputPath), { recursive: true })
    writeFileSync(outputPath, expected)
    console.log(`Wrote ${outputPath}`)
  }
  else {
    if (!existsSync(outputPath)) throw new Error('Buddy command reference is missing; run bun run docs:buddy')

    const current = readFileSync(outputPath, 'utf8')
    if (current !== expected) {
      // Say what differs. "Stale" on its own sends whoever sees it to
      // regenerate and commit, which is no help at all when the file already
      // matches on their machine and the difference is the environment the
      // registry was enumerated in.
      const currentLines = current.split('\n')
      const expectedLines = expected.split('\n')
      const differences: string[] = []

      for (let i = 0; i < Math.max(currentLines.length, expectedLines.length) && differences.length < 6; i++) {
        if (currentLines[i] !== expectedLines[i])
          differences.push(`  line ${i + 1}:\n    committed: ${JSON.stringify(currentLines[i] ?? '<end of file>')}\n    generated: ${JSON.stringify(expectedLines[i] ?? '<end of file>')}`)
      }

      throw new Error(`Buddy command reference is stale; run bun run docs:buddy\n${differences.join('\n')}`)
    }
    console.log('Buddy command reference matches the runtime registry')
  }
}

if (import.meta.main)
  await run()
