/**
 * The driver capability matrix, published from its registry (stacksjs/stacks#2056).
 *
 * `capabilityRegistry` in `@stacksjs/config` is the allowlist: `checkCapability`
 * validates a configured driver name against it, and `assertCapabilityAvailable`
 * refuses an unsupported one. It carries the maturity of every driver, the
 * evidence behind that judgement, and what each cannot do.
 *
 * #2056 asks that capability pages expose maturity consistently, and there was
 * no capability page - the registry was reachable only by reading a TypeScript
 * file. Written by hand it would be a second set of claims with no owner, so
 * this generates it and `--check` fails CI when the two disagree. The same
 * shape as `docs:desktop-matrix` next door (#2059).
 *
 * Usage: `bun storage/framework/core/buddy/src/commands/docs/capabilities.ts [--check|--write]`
 */

import type { CapabilityCategory, CapabilityDriver } from '../../../../config/src/capabilities'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { capabilityRegistry } from '../../../../config/src/capabilities'
import { assertFrameworkRepo } from './framework-repo'

const root = new URL('../../../../../../../', import.meta.url).pathname
const page = join(root, 'docs/features/capabilities.md')

const BEGIN = '<!-- capability-matrix:begin -->'
const END = '<!-- capability-matrix:end -->'

/** Category order and heading, so the page reads the way the config does. */
const CATEGORIES: ReadonlyArray<[CapabilityCategory, string]> = [
  ['database', 'Database'],
  ['queue', 'Queue'],
  ['cache', 'Cache'],
  ['storage', 'Storage'],
  ['mail', 'Mail'],
  ['realtime', 'Realtime'],
  ['deploy', 'Deploy'],
]

const STATUS_NOTE: Record<CapabilityDriver['status'], string> = {
  supported: 'Contract evidence runs in CI.',
  partial: 'Works, with the gaps named below.',
  experimental: 'Usable, but without retained evidence.',
  unsupported: 'Cannot be selected; configuring it fails loudly.',
}

function row(driver: CapabilityDriver): string {
  const evidence = driver.testEvidence.length === 0
    ? 'none retained'
    : driver.testEvidence.map(path => `\`${path.split('/').pop()}\``).join('<br>')

  const live = driver.liveServiceContract
    ? `${driver.liveServiceContract.service} ${driver.liveServiceContract.version}`
    : '-'

  return `| \`${driver.name}\` | **${driver.status}** | ${driver.topology} | ${live} | ${evidence} |`
}

function section(category: CapabilityCategory, heading: string): string[] {
  const drivers = capabilityRegistry.filter(driver => driver.category === category)
  if (drivers.length === 0)
    return []

  const limitations = drivers.flatMap(driver =>
    driver.limitations.map(limitation => `- **\`${driver.name}\`** - ${limitation}`),
  )

  return [
    `### ${heading}`,
    '',
    '| Driver | Status | Topology | Live service | Evidence |',
    '|---|---|---|---|---|',
    ...drivers.map(row),
    '',
    ...(limitations.length > 0 ? ['**Limitations**', '', ...limitations, ''] : []),
  ]
}

/**
 * How current this page is, and why.
 *
 * #2056 asks capability pages to expose a last-verified revision. A git-derived
 * stamp was the obvious answer and the wrong one: the revision changes when the
 * registry changes, so every commit touching `capabilities.ts` would leave this
 * page stale and `docs:capabilities:check` red until a second commit
 * regenerated it. A freshness marker that breaks CI to stay fresh is worse than
 * none, and a hand-maintained date is the first thing to rot.
 *
 * What a reader is actually asking - "can I trust this today?" - has a stronger
 * answer than a date. The page is generated from the registry and CI fails when
 * the two disagree, so it is verified at every commit rather than at one.
 */
function verifiedLine(): string[] {
  return [
    '> **How current is this?** This table is generated from `capabilityRegistry`',
    '> in `@stacksjs/config`, and `docs:capabilities:check` fails CI when the two',
    '> disagree - so it is verified at every commit, not as of some date.',
    '>',
    '> The claims themselves are checked by `capabilities.test.ts`: every cited',
    '> file must exist, anything short of `supported` must give a reason, and a',
    '> `supported` driver on a remote topology must name the provider version it',
    '> was proven against.',
    '',
  ]
}

export function render(): string {
  const statuses = Object.entries(STATUS_NOTE).map(([status, note]) => `- **${status}** - ${note}`)

  return [
    BEGIN,
    '',
    '<!-- Generated by `buddy docs:capabilities` from `@stacksjs/config`\'s',
    '     `capabilityRegistry`. Edit that, not this. -->',
    '',
    ...statuses,
    '',
    ...verifiedLine(),
    ...CATEGORIES.flatMap(([category, heading]) => section(category, heading)),
    END,
  ].join('\n')
}

function current(): string | null {
  let contents: string
  try {
    contents = readFileSync(page, 'utf8')
  }
  catch {
    return null
  }

  const start = contents.indexOf(BEGIN)
  const end = contents.indexOf(END)
  if (start === -1 || end === -1)
    return null

  return contents.slice(start, end + END.length)
}

function write(): boolean {
  const contents = readFileSync(page, 'utf8')
  const start = contents.indexOf(BEGIN)
  const end = contents.indexOf(END)

  if (start === -1 || end === -1)
    throw new Error(`[docs:capabilities] ${page} is missing the ${BEGIN} / ${END} markers`)

  const next = contents.slice(0, start) + render() + contents.slice(end + END.length)
  if (next === contents)
    return false

  writeFileSync(page, next)
  return true
}

export async function run(): Promise<void> {
  // This tool writes into the framework repository. See framework-repo.ts:
  // run from an application it would edit another project's files.
  assertFrameworkRepo(root, 'docs:capabilities')

  if (process.argv.includes('--write')) {
    console.log(write()
      ? '✓ rewrote the capability matrix in docs/features/capabilities.md'
      : '✓ the capability matrix was already current')
    return
  }

  if (current() === render()) {
    console.log(`✓ the capability matrix is current (${capabilityRegistry.length} drivers)`)
    return
  }

  console.error(current() === null
    ? '✗ docs/features/capabilities.md is missing its generated matrix section'
    : '✗ docs/features/capabilities.md no longer matches capabilityRegistry')
  console.error('\nRun `buddy docs:capabilities` to rewrite it from the registry.')

  if (process.argv.includes('--check'))
    process.exit(1)
}

if (import.meta.main)
  await run()
