/**
 * The desktop support matrix, published from its source (stacksjs/stacks#2059).
 *
 * `desktopSupportMatrix` in `@stacksjs/desktop` is the honest record of what
 * Craft desktop output actually supports: every row is `experimental`, signing
 * is `pending` everywhere, and each carries the evidence link and blocking
 * issue behind that judgement. `assertDesktopReleaseChannel` enforces it, so a
 * stable release of an unsigned target fails rather than shipping.
 *
 * None of which a reader ever saw. #2059 asks that supported combinations be
 * explicit and that experimental targets not be presented as stable - and they
 * were explicit only to someone reading a TypeScript file. A docs page written
 * by hand would have been the third source of truth and the first to rot, so
 * this generates it, and `--check` fails CI when the two disagree.
 *
 * Usage: `bun storage/framework/core/buddy/src/commands/docs/desktop-matrix.ts [--check|--write]`
 */

import type { DesktopSupportRow } from '../../../../desktop/src/support'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { desktopSupportMatrix } from '../../../../desktop/src/support'
import { assertFrameworkRepo } from './framework-repo'

const root = new URL('../../../../../../../', import.meta.url).pathname
const page = join(root, 'docs/packages/desktop.md')

/** The marker the generated section sits between, so hand-written prose can surround it. */
const BEGIN = '<!-- desktop-support-matrix:begin -->'
const END = '<!-- desktop-support-matrix:end -->'

const PLATFORM_NAMES: Record<DesktopSupportRow['platform'], string> = {
  darwin: 'macOS',
  linux: 'Linux',
  win32: 'Windows',
}

function link(url: string): string {
  // Issue and run URLs are long and all from two hosts; the number is the part
  // a reader scans for.
  const issue = url.match(/github\.com\/([^/]+\/[^/]+)\/issues\/(\d+)/)
  if (issue)
    return `[${issue[1]}#${issue[2]}](${url})`

  const run = url.match(/actions\/runs\/(\d+)/)
  if (run)
    return `[run ${run[1]}](${url})`

  return `[evidence](${url})`
}

function row(entry: DesktopSupportRow): string {
  const cells = [
    `${PLATFORM_NAMES[entry.platform]} ${entry.architecture}`,
    `**${entry.status}**`,
    entry.osVersions.join(', '),
    entry.packageFormat,
    entry.signing,
    entry.notarization,
    entry.installLaunchEvidence ? link(entry.installLaunchEvidence) : 'none',
    entry.blockingIssues.map(link).join(', ') || 'none',
  ]
  return `| ${cells.join(' | ')} |`
}

export function render(): string {
  const header = [
    '| Target | Status | Tested on | Package | Signing | Notarization | Install + launch | Blocked by |',
    '|---|---|---|---|---|---|---|---|',
  ]

  const limitations = desktopSupportMatrix.flatMap(entry =>
    entry.limitations.map(limitation => `- **${PLATFORM_NAMES[entry.platform]} ${entry.architecture}** - ${limitation}`),
  )

  const unique = [...new Set(limitations)]

  return [
    BEGIN,
    '',
    '<!-- Generated by `buddy docs:desktop-matrix` from `@stacksjs/desktop`\'s',
    '     `desktopSupportMatrix`. Edit that, not this. -->',
    '',
    ...header,
    ...desktopSupportMatrix.map(row),
    '',
    '### Known limitations',
    '',
    ...unique,
    '',
    END,
  ].join('\n')
}

function current(): string | null {
  let contents: string
  try {
    contents = readFileSync(page, 'utf8')
  }
  catch {
    return null
  }

  const start = contents.indexOf(BEGIN)
  const end = contents.indexOf(END)
  if (start === -1 || end === -1)
    return null

  return contents.slice(start, end + END.length)
}

function write(): boolean {
  const contents = readFileSync(page, 'utf8')
  const start = contents.indexOf(BEGIN)
  const end = contents.indexOf(END)

  if (start === -1 || end === -1)
    throw new Error(`[docs:desktop-matrix] ${page} is missing the ${BEGIN} / ${END} markers`)

  const next = contents.slice(0, start) + render() + contents.slice(end + END.length)
  if (next === contents)
    return false

  writeFileSync(page, next)
  return true
}

export async function run(): Promise<void> {
  // This tool writes into the framework repository. See framework-repo.ts:
  // run from an application it would edit another project's files.
  assertFrameworkRepo(root, 'docs:desktop-matrix')

  if (process.argv.includes('--write')) {
    console.log(write()
      ? '✓ rewrote the desktop support matrix in docs/packages/desktop.md'
      : '✓ the desktop support matrix was already current')
    return
  }

  const published = current()

  if (published === render()) {
    console.log(`✓ the desktop support matrix is current (${desktopSupportMatrix.length} targets)`)
    return
  }

  console.error(published === null
    ? '✗ docs/packages/desktop.md is missing its generated support-matrix section'
    : '✗ docs/packages/desktop.md no longer matches desktopSupportMatrix')
  console.error('\nRun `buddy docs:desktop-matrix` to rewrite it from the source.')

  if (process.argv.includes('--check'))
    process.exit(1)
}

if (import.meta.main)
  await run()
