import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import process from 'node:process'
import { capabilityRegistry } from '../../../../config/src/capabilities'
import { FEATURE_NAMES } from '../../../../features/src/names'
import { assertFrameworkRepo } from './framework-repo'

const root = new URL('../../../../../../../', import.meta.url).pathname
const core = 'storage/framework/core'
const destination = 'storage/framework/defaults/ai/skills/stacks-native'

const PACKAGE_SKILLS: Record<string, string> = {
  'action-runner': 'stacks-actions',
  'calendar-api': 'stacks-calendar',
  defaults: 'stacks-build',
  github: 'stacks-git',
  'model-meta': 'stacks-models',
  tinker: 'stacks-repl',
}

interface PackageEntry {
  name: string
  directory: string
  skill: string
  entry: string
  exports: string[]
  dependencies: string[]
  tests: string[]
}

function localSource(projectRoot: string, entry: string, specifier: string): string {
  const path = join(dirname(entry), specifier)
  const stem = path.replace(/\.js$/, '')
  const candidates = [path, `${stem}.ts`, `${stem}.tsx`, join(path, 'index.ts')]
  const resolved = candidates.find(candidate => existsSync(join(projectRoot, candidate)) && statSync(join(projectRoot, candidate)).isFile())
  if (!resolved)
    throw new Error(`Native catalog cannot resolve ${specifier} from ${entry}`)
  return resolved
}

export function nativePackageCatalog(projectRoot = root): PackageEntry[] {
  const scanner = new Bun.Transpiler({ loader: 'ts' })
  return readdirSync(join(projectRoot, core)).filter(slug => existsSync(join(projectRoot, core, slug, 'package.json')))
    .sort().map((slug) => {
      const directory = join(core, slug)
      const manifest = JSON.parse(readFileSync(join(projectRoot, directory, 'package.json'), 'utf8'))
      const skill = PACKAGE_SKILLS[slug] ?? `stacks-${slug}`
      if (!existsSync(join(projectRoot, 'storage/framework/defaults/ai/skills', skill, 'SKILL.md')))
        throw new Error(`Native package ${manifest.name} needs a skill or an explicit package-to-skill mapping`)

      const source = join(directory, 'src/index.ts')
      const entry = existsSync(join(projectRoot, source)) ? source : join(directory, 'package.json')
      const scan = entry.endsWith('.ts') ? scanner.scan(readFileSync(join(projectRoot, entry), 'utf8')) : undefined
      const tests = existsSync(join(projectRoot, directory, 'tests'))
        ? [...new Bun.Glob('**/*.{test,spec}.{ts,tsx,js}').scanSync({ cwd: join(projectRoot, directory, 'tests'), onlyFiles: true })].sort()
          .map(file => join(directory, 'tests', file))
        : []

      return {
        name: manifest.name,
        directory,
        skill,
        entry,
        exports: scan?.exports.sort() ?? [],
        dependencies: [...new Set(scan?.imports.map(item => item.path).filter(path => path.startsWith('.')) ?? [])]
          .map(path => localSource(projectRoot, entry, path)).sort(),
        tests,
      }
    })
}

function sourceLink(path: string, label = path): string {
  return `[${label}](https://github.com/stacksjs/stacks/blob/main/${path})`
}

export function renderNativeCatalog(projectRoot = root): string {
  const packages = nativePackageCatalog(projectRoot)
  return [
    '# Native Stacks package catalog',
    '',
    '<!-- Generated by buddy docs:native-skills. Edit source packages or the mapping, then regenerate. -->',
    '',
    'This indexes every current core package. It describes source surfaces and',
    'retained tests, not a promise that every export or remote provider is fully',
    'supported. Read the selected skill and implementation before choosing an API.',
    'Wildcard re-exports and type-only exports are not expanded by the source scan.',
    'Browser runtime bindings are documented separately in `stacks-auto-imports`.',
    '',
    '| Package | Task guidance | Source entry | Retained tests |',
    '|---|---|---|---|',
    ...packages.map(entry => `| \`${entry.name}\` | [\`${entry.skill}\`](../${entry.skill}/SKILL.md) | ${sourceLink(entry.entry, 'entrypoint')} | ${entry.tests.length} |`),
    '',
    '## Source surfaces',
    '',
    'Use these pointers to discover the current implementation and exact signatures.',
    'An exported name is not evidence that an operation supports every driver.',
    '',
    ...packages.flatMap(entry => [
      `### ${entry.name}`,
      '',
      `Guidance: [\`${entry.skill}\`](../${entry.skill}/SKILL.md). Source: ${sourceLink(entry.entry)}.`,
      '',
      entry.exports.length ? `Declared runtime exports: ${entry.exports.map(name => `\`${name}\``).join(', ')}.` : 'Read the entrypoint and package export map for re-exported or type-only surfaces.',
      '',
      ...(entry.dependencies.length ? [`Local source modules: ${entry.dependencies.map(path => sourceLink(path, relative(entry.directory, path))).join(', ')}.`, ''] : []),
      ...(entry.tests.length ? [`Evidence directory: ${sourceLink(`${entry.directory}/tests`, `${entry.tests.length} retained tests`)}. These files are evidence pointers, not a claim that all tests were run for this catalog.`, ''] : []),
    ]),
  ].join('\n')
}

export function renderDriverCapabilities(): string {
  return [
    '# Driver evidence and limitations',
    '',
    '<!-- Generated by buddy docs:native-skills from capabilityRegistry. -->',
    '',
    'The registry distinguishes supported, partial, experimental, and unsupported',
    'drivers. Unknown and unsupported selections fail. Partial and experimental',
    'drivers remain subject to the limitations below. Read prerequisites before',
    'deploying; a configuration type does not establish an implemented transport.',
    '',
    ...capabilityRegistry.flatMap(driver => [
      `## ${driver.category}: ${driver.name}`,
      '',
      `Status: **${driver.status}**. Topology: ${driver.topology}.`,
      '',
      ...(driver.implementation ? [`Implementation: ${sourceLink(driver.implementation)}.`, ''] : []),
      ...(driver.prerequisites.length ? ['Prerequisites:', '', ...driver.prerequisites.map(value => `- ${value}`), ''] : []),
      ...(driver.limitations.length ? ['Limitations:', '', ...driver.limitations.map(value => `- ${value}`), ''] : []),
      ...(driver.testEvidence.length ? ['Retained evidence:', '', ...driver.testEvidence.map(path => `- ${sourceLink(path)}`), ''] : []),
    ]),
    '## Optional application bundles',
    '',
    `Installable bundle names: ${FEATURE_NAMES.map(name => `\`${name}\``).join(', ')}.`,
    '',
    'Read `stacks-features` for installation, config gates, route bundles, and',
    'migration selection. These are distinct from user-targeted feature flags.',
    '',
  ].join('\n').replace(/[\u2014\u2013]/g, '-')
}

export async function run(): Promise<void> {
  assertFrameworkRepo(root, 'docs:native-skills')
  const outputs = [
    { path: join(root, destination, 'CATALOG.md'), body: renderNativeCatalog() },
    { path: join(root, destination, 'CAPABILITIES.md'), body: renderDriverCapabilities() },
  ]
  const stale = outputs.filter(file => !existsSync(file.path) || readFileSync(file.path, 'utf8') !== file.body)
  if (process.argv.includes('--write')) {
    for (const file of stale)
      writeFileSync(file.path, file.body, 'utf8')
    console.log(`Native skill references refreshed: ${stale.length} file(s).`)
  }
  else if (stale.length) {
    console.error(`Native skill references are stale: ${stale.map(file => relative(root, file.path)).join(', ')}. Run ./buddy docs:native-skills.`)
    process.exitCode = 1
  }
  else {
    console.log('Native skill package coverage and driver evidence are current.')
  }
}

if (import.meta.main)
  await run()
