/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'Carbon:cafe': typeof import('~icons/carbon/cafe')['default']
    'Carbon:logoTwitter': typeof import('~icons/carbon/logo-twitter')['default']
    Checkout: typeof import('./src/components/Checkout.vue')['default']
    CheckoutUsage: typeof import('./src/components/CheckoutUsage.vue')['default']
    copy: typeof import('./src/components/Environment copy.vue')['default']
    Environment: typeof import('./src/components/Environment.vue')['default']
    Environtment: typeof import('./src/components/Environtment.vue')['default']
    Expand: typeof import('./src/components/Expand.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HeadlessToast: typeof import('./src/components/HeadlessToast.vue')['default']
    HeadlessToastWithProps: typeof import('./src/components/HeadlessToastWithProps.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Installation: typeof import('./src/components/Installation.vue')['default']
    Loader: typeof import('./src/components/icons/Loader.vue')['default']
    'Mdi:heart': typeof import('~icons/mdi/heart')['default']
    OneTimePayment: typeof import('./src/components/OneTimePayment.vue')['default']
    Others: typeof import('./src/components/Others.vue')['default']
    PaymentUsage: typeof import('./src/components/PaymentUsage.vue')['default']
    Position: typeof import('./src/components/Position.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    Styling: typeof import('./src/components/Styling.vue')['default']
    Subscription: typeof import('./src/components/Subscription.vue')['default']
    SubscriptionUsage: typeof import('./src/components/SubscriptionUsage.vue')['default']
    Theming: typeof import('./src/components/Theming.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    Toaster: typeof import('./src/components/Toaster.vue')['default']
    Types: typeof import('./src/components/Types.vue')['default']
    Usage: typeof import('./src/components/Usage.vue')['default']
  }
}
